# Testing

In [1]:
import pandas as pd

In [2]:
CCLE_PATH = "/Users/zijiexu/GEMS-LAB/MD-syn-GEMS/CCLE_expression.csv"
df = pd.read_csv(CCLE_PATH)
df

,Unnamed: 0,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),C1orf112 (55732),FGR (2268),CFH (3075),FUCA2 (2519),GCLC (2729),...,H3C2 (8358),H3C3 (8352),AC098582.1 (8916),DUS4L-BCAP29 (115253422),C8orf44-SGK3 (100533105),ELOA3B (728929),NPBWR1 (2831),ELOA3D (100506888),ELOA3 (162699),CDR1 (1038)
0,ACH-001113,4.331992,0.000000,7.364397,2.792855,4.470537,0.028569,1.226509,3.042644,6.499686,...,2.689299,0.189034,0.201634,2.130931,0.555816,0.000000,0.275007,0.0,0.000000,0.000000
1,ACH-001289,4.566815,0.584963,7.106537,2.543496,3.504620,0.000000,0.189034,3.813525,4.221104,...,1.286881,1.049631,0.321928,1.464668,0.632268,0.000000,0.014355,0.0,0.000000,0.000000
2,ACH-001339,3.150560,0.000000,7.379032,2.333424,4.227279,0.056584,1.310340,6.687061,3.682573,...,0.594549,1.097611,0.831877,2.946731,0.475085,0.000000,0.084064,0.0,0.000000,0.042644
3,ACH-001538,5.085340,0.000000,7.154109,2.545968,3.084064,0.000000,5.868143,6.165309,4.489928,...,0.214125,0.632268,0.298658,1.641546,0.443607,0.000000,0.028569,0.0,0.000000,0.000000
4,ACH-000242,6.729145,0.000000,6.537607,2.456806,3.867896,0.799087,7.208381,5.569856,7.127014,...,1.117695,2.358959,0.084064,1.910733,0.000000,0.000000,0.464668,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,ACH-000285,0.056584,0.000000,6.604071,3.264536,4.972693,0.411426,0.097611,0.704872,4.829850,...,2.229588,0.084064,1.310340,3.039138,0.344828,0.000000,0.000000,0.0,0.475085,0.042644
1402,ACH-002669,3.109361,0.000000,7.031219,1.541019,3.664483,0.014355,3.624101,6.805292,4.472488,...,0.189034,0.400538,0.356144,1.327687,0.000000,0.000000,0.014355,0.0,0.000000,0.000000
1403,ACH-001858,4.390943,0.000000,7.013127,1.887525,3.252476,0.028569,3.286881,6.902074,5.410748,...,1.097611,0.400538,0.613532,1.992768,0.704872,0.000000,1.464668,0.0,0.000000,0.526069
1404,ACH-001997,5.057017,0.000000,7.814935,2.538538,3.893362,0.028569,4.078951,6.971429,4.469886,...,0.831877,0.847997,1.292782,2.153805,0.687061,0.000000,0.000000,0.0,0.000000,0.000000
1405,ACH-000052,4.247928,0.000000,6.174127,2.316146,3.823749,0.189034,1.321928,3.536053,3.943921,...,1.244887,1.201634,0.000000,1.956057,0.575312,0.042644,0.000000,0.0,0.176323,0.056584

In [3]:
df.shape

(1406, 19222)

In [4]:
landmarks = pd.read_csv("landmark_genes.txt", sep="\t")
landmarks

,Entrez ID,Symbol,Name,Gene Family,Type,RNA-Seq Correlation,RNA-Seq Correlation Self-Rank
0,3638,INSIG1,insulin induced gene 1,NaN,landmark,NaN,NaN
1,2309,FOXO3,forkhead box O3,Forkhead boxes,landmark,NaN,NaN
2,1001,CDH3,cadherin 3,Type I classical cadherins,landmark,NaN,NaN
3,4998,ORC1,origin recognition complex subunit 1,"AAA ATPases, Origin recognition complex",landmark,NaN,NaN
4,3682,ITGAE,integrin subunit alpha E,"CD molecules, Integrin alpha subunits",landmark,NaN,NaN
...,...,...,...,...,...,...,...
973,4925,NUCB2,nucleobindin 2,EF-hand domain containing,landmark,NaN,NaN
974,4927,NUP88,nucleoporin 88,Nucleoporins,landmark,NaN,NaN
975,4931,NVL,nuclear VCP-like,AAA ATPases,landmark,NaN,NaN
976,3611,ILK,integrin linked kinase,Ankyrin repeat domain containing,landmark,NaN,NaN
977,3628,INPP1,inositol polyphosphate-1-phosphatase,Phosphoinositide phosphatases,landmark,NaN,NaN

In [5]:
landmark_names = list(landmarks['Symbol'])
landmark_names

['INSIG1',
 'FOXO3',
 'CDH3',
 'ORC1',
 'ITGAE',
 'CDK7',
 'FOS',
 'CDK6',
 'CDK4',
 'CDK2',
 'ITGB5',
 'CDKN2A',
 'CDKN1B',
 'CDKN1A',
 'FPGS',
 'CEBPD',
 'CEBPA',
 'CENPE',
 'MICALL1',
 'CETN3',
 'UBE2C',
 'DUSP14',
 'TOPBP1',
 'B4GAT1',
 'RBM34',
 'PAPD7',
 'WDTC1',
 'XPO7',
 'AKAP8L',
 'RAB31',
 'SPEN',
 'FBXO21',
 'RAB21',
 'SLC27A3',
 'KIF2C',
 'CCDC85B',
 'TLK2',
 'KDELR2',
 'MCUR1',
 'CDK19',
 'JUN',
 'TBC1D9B',
 'PRSS23',
 'RRP1B',
 'MYCBP2',
 'CHEK1',
 'KCNK1',
 'CHN1',
 'CIRBP',
 'HDGFRP3',
 'COPS7A',
 'NSDHL',
 'ATP11B',
 'PRAF2',
 'JMJD6',
 'RRS1',
 'MPC2',
 'ARID5B',
 'POLG2',
 'CHEK2',
 'BACE2',
 'COG4',
 'SPDEF',
 'BAMBI',
 'SPRED2',
 'SLC2A6',
 'SNX13',
 'NISCH',
 'AARS',
 'ABCF1',
 'ABL1',
 'FCHO1',
 'DCUN1D4',
 'PSIP1',
 'ACAA1',
 'ACAT2',
 'ACLY',
 'PKIG',
 'CORO1A',
 'MAST2',
 'GPATCH8',
 'FBXO7',
 'LSM6',
 'PWP1',
 'KIF5C',
 'KIT',
 'FUT1',
 'FYN',
 'GAA',
 'CLTC',
 'CLTB',
 'SLC37A4',
 'GABPB1',
 'KTN1',
 'GALE',
 'GAPDH',
 'COL4A1',
 'COL1A1',
 'TRIM2',
 'TSKU',
 'WASHC4',
 'USP22',
 'HDAC6',
 'TWF2',
 'WDR7',
 'JADE2',
 'ATMIN',
 'C2CD2',
 'DDX42',
 'TIPARP',
 'GNPDA1',
 'ECD',
 'CLIC4',
 'PNKP',
 'CAMSAP2',
 'CHP1',
 'PDS5A',
 'RRP12',
 'SYNE2',
 'LAMA3',
 'STMN1',
 'LBR',
 'HEBP1',
 'GATA3',
 'GATA2',
 'LGALS8',
 'LIG1',
 'LIPA',
 'GFPT1',
 'GHR',
 'CREB1',
 'RPL39L',
 'CRKL',
 'CRK',
 'SLC35A3',
 'TRAP1',
 'G3BP1',
 'KIF20A',
 'ARL4C',
 'SIRT3',
 'TSPAN3',
 'NUDCD3',
 'SMC4',
 'ARHGEF12',
 'PPP1R13B',
 'ABCC5',
 'DNM1L',
 'ABCB6',
 'RRP8',
 'PARP2',
 'MAMLD1',
 'DNAJB6',
 'GLI2',
 'GLRX',
 'CRYZ',
 'GNAI2',
 'GNAI1',
 'GNA11',
 'GNA15',
 'GNAS',
 'CSK',
 'CSNK2A2',
 'CSNK1E',
 'CSNK1A1',
 'CSRP1',
 'SLC35B1',
 'TIMM17B',
 'KAT6B',
 'NNT',
 'ADAT1',
 'MFSD10',
 'TRIB1',
 'SUZ12',
 'TRIM13',
 'TXNDC9',
 'FASTKD5',
 'SORBS3',
 'RBM6',
 'MACF1',
 'MBNL2',
 'ICMT',
 'CEBPZ',
 'SFN',
 'SLC25A13',
 'GPC1',
 'CTNND1',
 'CTSD',
 'CTSL',
 'GPER1',
 'CYB561',
 'GRB10',
 'GRB7',
 'GRN',
 'TMEM2',
 'HMG20B',
 'ARFIP2',
 'LSM5',
 'PLA2G15',
 'TNIP1',
 'NUP62',
 'SSBP2',
 'TMEM5',
 'IKZF1',
 'NR3C1',
 'PAK4',
 'AKAP8',
 'STUB1',
 'TMEM50A',
 'KLHDC2',
 'CXCL2',
 'NET1',
 'ACOT9',
 'SMNDC1',
 'DAG1',
 'DAXX',
 'GSTM2',
 'GSTZ1',
 'GTF2A2',
 'MSH6',
 'ELAC2',
 'DCTD',
 'DCK',
 'GTF2E2',
 'DDB2',
 'GADD45A',
 'DECR1',
 'DDX10',
 'DFFB',
 'DFFA',
 'CRTAP',
 'VAT1',
 'STK25',
 'LRRC41',
 'VAV3',
 'PPIE',
 'LYPLA1',
 'MYL9',
 'DLD',
 'TUBB6',
 'DNM1',
 'CIAPIN1',
 'DNMT3A',
 'DNMT1',
 'PLSCR3',
 'TXLNA',
 'APPBP2',
 'HYOU1',
 'CHERP',
 'SNX6',
 'THAP11',
 'DRAP1',
 'RPP38',
 'SLC35A1',
 'MCOLN1',
 'DPH2',
 'DSG2',
 'TSC22D3',
 'DUSP6',
 'DUSP4',
 'DUSP3',
 'PSRC1',
 'TOR1A',
 'E2F2',
 'ECH1',
 'SQRDL',
 'LYRM1',
 'SCYL3',
 'ENOPH1',
 'PRUNE1',
 'ZMIZ1',
 'YKT6',
 'CGRRF1',
 'NPRL2',
 'IGF2BP2',
 'STAMBP',
 'ST6GALNAC2',
 'PAICS',
 'CNPY3',
 'RRAGA',
 'EBP',
 'GNB5',
 'H2AFV',
 'EDN1',
 'EGF',
 'EGR1',
 'EGFR',
 'EIF4EBP1',
 'EIF5',
 'EIF4G1',
 'ELAVL1',
 'MPZL1',
 'SLC25A14',
 'MAP7',
 'ADO',
 'ARPP19',
 'POP4',
 'ZNF274',
 'ABHD6',
 'DNAJA3',
 'USP14',
 'KDM5B',
 'YME1L1',
 'TCFL5',
 'CASC3',
 'COG2',
 'MTHFD2',
 'EML3',
 'MTA1',
 'PDLIM1',
 'PRPF4',
 'SMC3',
 'CCNB2',
 'CCNE2',
 'SYNGR3',
 'LPAR2',
 'ZW10',
 'ARHGEF2',
 'CPSF4',
 'MALT1',
 'KIAA0907',
 'CLSTN1',
 'FOXJ3',
 'PGRMC1',
 'CANT1',
 'RAB11FIP2',
 'ATF5',
 'MTF2',
 'PUF60',
 'CLPX',
 'AURKB',
 'VAPB',
 'NOLC1',
 'WASF3',
 'UTP14A',
 'FRS2',
 'GRWD1',
 'UBE2L6',
 'CYTH1',
 'MAPKAPK2',
 'COPB2',
 'ITGB1BP1',
 'BCL7B',
 'ADGRG1',
 'HERC6',
 'TMED10',
 'ASCC3',
 'PPP2R3C',
 'PIH1D1',
 'RPIA',
 'PDIA5',
 'TOMM34',
 'FKBP14',
 'EBNA1BP2',
 'CDCA4',
 'MLLT11',
 'WIPF2',
 'SACM1L',
 'ATF6',
 'TCERG1',
 'TM9SF2',
 'EPN2',
 'RNPS1',
 'PDHX',
 'FOSL1',
 'BLCAP',
 'HMGA2',
 'TRIB3',
 'PLEKHJ1',
 'HEATR1',
 'ANO10',
 'UBR7',
 'TRAPPC6A',
 'CHAC1',
 'CCDC86',
 'MAP4K4',
 'HOMER2',
 'SH3BP5',
 'METRN',
 'PIGB',
 'PSMF1',
 'ELOVL6',
 'TMEM109',
 'ITFG1',
 'FBXO11',
 'ADI1',
 'CCDC92',
 'GDPD5',
 'POLD4',
 'SPTLC2',
 'TBPL1',
 'BAG3',
 'NRIP1',
 'NCOA3',
 'POLR1C',
 'SPAG7',
 'SMC1A',
 'FAIM',
 'LAGE3',
 'MBOAT7',
 'PRR15L',
 'CRELD2',
 'MAPK1IP1L',
 'FSD1',
 'NPDC1',
 'ABCF3',
 'ERO1A',
 'TRAK2',
 'COASY',
 'CHMP4A',
 'GTPBP8',
 'IKBKE',
 'AXIN1',
 'FEZ2',
 'FZD1',
 'HS2ST1',
 'MTFR1',
 'FZD7',
 'CDC45',
 'TERT',
 'TESK1',
 'IPO13',
 'VGLL4',
 'TFDP1',
 'NUP93',
 'TFAP2A',
 'HIST2H2BE',
 'TRAM2',
 'EDEM1',
 'UBE3C',
 'TGFB3',
 'TGFBR2',
 'PIP4K2B',
 'TIMP2',
 'TIAM1',
 'TLE1',
 'TJP1',
 'TBC1D31',
 'TLR4',
 'DNAJC15',
 'TICAM1',
 'USP6NL',
 'KIAA0355',
 'CEP57',
 'KIAA0100',
 'HERPUD1',
 'ADAM10',
 'CCP110',
 'ADH5',
 'MLEC',
 'TSPAN6',
 'NCK2',
 'DUSP11',
 'DYRK3',
 'PARP1',
 'TSPAN4',
 'ADRB2',
 'TATDN2',
 'AGL',
 'TOP2A',
 'TP53BP1',
 'TP53',
 'TP53BP2',
 'RAE1',
 'TPD52L2',
 'TPM1',
 'WDR61',
 'MRPL19',
 'SCRN1',
 'EFCAB14',
 'KEAP1',
 'MELK',
 'AKT1',
 'CYCS',
 'PLEKHM1',
 'ALAS1',
 'PIK3R3',
 'NIPSNAP1',
 'HAT1',
 'KIAA0753',
 'C2CD2L',
 'ENOSF1',
 'ALDOA',
 'C2CD5',
 'TM9SF3',
 'IKBKAP',
 'ALDOC',
 'TOMM70',
 'BHLHE40',
 'MAPKAPK5',
 'WASHC5',
 'AKR7A2',
 'CASK',
 'MKNK1',
 'TSTA3',
 'SLC25A4',
 'SLC25A46',
 'TXNRD1',
 'CHMP6',
 'IARS2',
 'TERF2IP',
 'ACD',
 'CARMIL1',
 'ANKRD10',
 'DUSP22',
 'KLHL21',
 'STAP2',
 'FAM20B',
 'NCAPD2',
 'ARNT2',
 'PAN2',
 'KIF14',
 'LPGAT1',
 'OXSR1',
 'ANXA7',
 'RUVBL1',
 'APBB2',
 'TCTN1',
 'BIRC2',
 'MVP',
 'BIRC5',
 'COQ8A',
 'PSMG1',
 'APOE',
 'APP',
 'FAS',
 'UBE2A',
 'DMTF1',
 'BECN1',
 'RHEB',
 'UGDH',
 'RHOA',
 'ARHGAP1',
 'NR1H2',
 'RNH1',
 'USP1',
 'PAK6',
 'INTS3',
 'PRR7',
 'TMEM110',
 'TSEN2',
 'TMCO1',
 'CNDP2',
 'NUP133',
 'NPEPL1',
 'MBTPS1',
 'ASAH1',
 'RNMT',
 'EED',
 'GFOD1',
 'CTNNAL1',
 'KCTD5',
 'VDAC1',
 'MINDY1',
 'ATF1',
 'ATP1B1',
 'RPA1',
 'RPA3',
 'RPA2',
 'WFS1',
 'WRB',
 'XBP1',
 'MRPL12',
 'RPN1',
 'RPS5',
 'RPS6KA1',
 'RPS6',
 'FAM69A',
 'ALDH7A1',
 'EXOSC4',
 'CISD1',
 'PEX11A',
 'CREG1',
 'INPP4B',
 'ATP6V0B',
 'IQGAP1',
 'XPNPEP1',
 'DDIT4',
 'SOCS2',
 'CFLAR',
 'CDK5R1',
 'FAM57A',
 'ZNF395',
 'IER3',
 'BAD',
 'ST3GAL5',
 'ZFP36',
 'SLC5A6',
 'BAX',
 'SQSTM1',
 'CPNE3',
 'CCND1',
 'BCL2',
 'RSU1',
 'RTN2',
 'S100A4',
 'S100A13',
 'KDM3A',
 'PECR',
 'DHX29',
 'EAPP',
 'TRAPPC3',
 'RBKS',
 'CCNA1',
 'ATP2C1',
 'BDH1',
 'TIMELESS',
 'BID',
 'BLMH',
 'BLVRA',
 'TCEAL4',
 'BMP4',
 'BNIP3',
 'BNIP3L',
 'DHDDS',
 'P4HA2',
 'BPHL',
 'BRCA1',
 'NUDT9',
 'SATB1',
 'PLOD3',
 'P4HTM',
 'DENND2D',
 'NOL3',
 'BTK',
 'SCP2',
 'CCL2',
 'OXA1L',
 'OXCT1',
 'ZNF131',
 'PAFAH1B1',
 'SERPINE1',
 'PAK1',
 'PAFAH1B3',
 'SDHB',
 'PCCB',
 'PCBD1',
 'NUP85',
 'PAF1',
 'KLHL9',
 'BUB1B',
 'C5',
 'ZMYM2',
 'DDR1',
 'PCMT1',
 'PCNA',
 'SGCB',
 'PCK2',
 'PCM1',
 'SHB',
 'SHC1',
 'PDGFA',
 'SKIV2L',
 'SLC35F2',
 'ATP5S',
 'PACSIN3',
 'CALM3',
 'CALU',
 'CAPN1',
 'CAST',
 'CASP2',
 'CASP3',
 'CASP7',
 'CASP10',
 'CAT',
 'SKP1',
 'CBLB',
 'SLC1A4',
 'CBR1',
 'CBR3',
 'CXCR4',
 'TEX10',
 'PAX8',
 'CCNA2',
 'CCNB1',
 'CCND3',
 'CCNF',
 'PFKL',
 'USP7',
 'IFRD2',
 'MAPKAPK3',
 'PGAM1',
 'PGM1',
 'PHKA1',
 'PHKB',
 'PHKG2',
 'SMARCA4',
 'SMARCC1',
 'ZNF586',
 'PIK3C2B',
 'PIK3C3',
 'PIK3CA',
 'FBXL12',
 'TNFRSF21',
 'SESN1',
 'RBM15B',
 'PIK3R4',
 'CCNH',
 'DNTTIP2',
 'SCCPDH',
 'SCARB1',
 'REEP5',
 'CD40',
 'CD44',
 'CD58',
 'SENP6',
 'ADGRE5',
 'SMARCD2',
 'RAI14',
 'CDK1',
 'SNAP25',
 'PIN1',
 'CDC20',
 'CDC25A',
 'CDC25B',
 'MTERF3',
 'CDC42',
 'AMDHD2',
 'SNCA',
 'ISOC1',
 'PLA2G4A',
 'ST7',
 'MRPS16',
 'FIS1',
 'GOLT1B',
 'COG7',
 'PLCB3',
 'KAT6A',
 'GLOD4',
 'SOX2',
 'SOX4',
 'SPAG4',
 'PLP2',
 'GMNN',
 'LAP3',
 'LOXL1',
 'PLK1',
 'SPP1',
 'PMAIP1',
 'SPR',
 'PLS1',
 'PLSCR1',
 'PMM2',
 'LRPAP1',
 'NOSIP',
 'DERA',
 'YTHDF1',
 'LYN',
 'TIMM22',
 'SMAD3',
 'NENF',
 'TXNL4B',
 'HOOK2',
 'SNX11',
 'ZNF451',
 'TMEM97',
 'LRP10',
 'HTATSF1',
 'RNF167',
 'UBQLN2',
 'SPTAN1',
 'SRC',
 'POLB',
 'POLE2',
 'POLR2K',
 'STAT1',
 'STAT3',
 'POLR2I',
 'STAT5B',
 'AURKA',
 'STK10',
 'VPS28',
 'MAN2B1',
 'MAT2A',
 'HSD17B11',
 'PPARD',
 'PPARG',
 'MBNL1',
 'PPIC',
 'PPOX',
 'MCM3',
 'ATG3',
 'ZDHHC6',
 'NARFL',
 'MRPS2',
 'TES',
 'KIF1BP',
 'STX1A',
 'STX4',
 'STXBP1',
 'STXBP2',
 'SUV39H1',
 'SUPV3L1',
 'SYK',
 'MYCBP',
 'ME2',
 'SYPL1',
 'PPP2R5A',
 'PPP2R5E',
 'MEF2C',
 'MAP3K4',
 'PRCP',
 'TARBP1',
 'MEST',
 'HN1L',
 'PRKACA',
 'PRKCD',
 'PRKCH',
 'SCAND1',
 'CD320',
 'PRKCQ',
 'MIF',
 'NUSAP1',
 'PHGDH',
 'TBP',
 'TBX2',
 'TCEA2',
 'TBXA2R',
 'MAP2K5',
 'MAPK9',
 'MAPK13',
 'VPS72',
 'PRKX',
 'PROS1',
 'LGMN',
 'FOXO4',
 'MMP1',
 'MMP2',
 'DYNLT3',
 'MNAT1',
 'HTRA1',
 'TCTA',
 'SNX7',
 'ATP6V1D',
 'ZNF589',
 'PSMB8',
 'HADH',
 'HSD17B10',
 'PSMB10',
 'HDAC2',
 'HIF1A',
 'HK1',
 'UBE3B',
 'BZW2',
 'NGRN',
 'PSMD2',
 'PSMD4',
 'PSMD9',
 'PSMD10',
 'PSME1',
 'PSME2',
 'PTGS2',
 'PTK2',
 'PTPN1',
 'HLA-DMA',
 'PTPN12',
 'HLA-DRA',
 'PTPN6',
 'PTPRF',
 'PTPRK',
 'HACD3',
 'PTPRC',
 'MSRA',
 'HMGCR',
 'HMOX1',
 'HMGCS1',
 'PRKAG2',
 'ACBD3',
 'UBE2J1',
 'EVL',
 'CERK',
 'PXMP2',
 'PXN',
 'PYCR1',
 'PYGL',
 'RAB27A',
 'HOXA10',
 'HOXA5',
 'RAB4A',
 'RAC2',
 'RAD9A',
 'MOK',
 'RAD51C',
 'RALA',
 'RALB',
 'MUC1',
 'HPRT1',
 'HES1',
 'CHIC2',
 'UFM1',
 'TIMM9',
 'LSR',
 'RAP1GAP',
 'RALGDS',
 'KDM5A',
 'RASA1',
 'RB1',
 'MYC',
 'MYBL2',
 'GADD45B',
 'RELB',
 'HSPA1A',
 'DNAJB2',
 'HSPA4',
 'MYLK',
 'MYO10',
 'RFC2',
 'HSPB1',
 'HSPA8',
 'RFX5',
 'HSPD1',
 'RFC5',
 'RFNG',
 'DNAJB1',
 'RGS2',
 'CTTN',
 'NCK1',
 'EPHA3',
 'EPB41L2',
 'ICAM3',
 'ICAM1',
 'EPHB2',
 'ID2',
 'ERBB3',
 'ERBB2',
 'NR2F6',
 'EPRS',
 'NT5DC2',
 'DHRS7',
 'IDE',
 'ETFB',
 'NFE2L2',
 'NFIL3',
 'ETV1',
 'ETS1',
 'NFATC3',
 'NFATC4',
 'NFKB2',
 'NFKBIA',
 'NFKBIB',
 'NFKBIE',
 'EXT1',
 'IFNAR1',
 'IGFBP3',
 'IGF2R',
 'IGF1R',
 'EZH2',
 'PTK2B',
 'FAH',
 'FAT1',
 'ZNF318',
 'CAB39',
 'NIT1',
 'ARID4B',
 'IGHMBP2',
 'NMT1',
 'CNOT4',
 'NOS3',
 'PNP',
 'NOTCH1',
 'NPC1',
 'IKBKB',
 'SLC11A2',
 'NRAS',
 'FDFT1',
 'IL1B',
 'IL4R',
 'FGFR4',
 'FGFR2',
 'FHL2',
 'IL13RA1',
 'FKBP4',
 'ABHD4',
 'HIST1H2BK',
 'NUCB2',
 'NUP88',
 'NVL',
 'ILK',
 'INPP1']

In [6]:
column_names = [name.split()[0] for name in list(df.columns)]
column_names

['Unnamed:',
 'TSPAN6',
 'TNMD',
 'DPM1',
 'SCYL3',
 'C1orf112',
 'FGR',
 'CFH',
 'FUCA2',
 'GCLC',
 'NFYA',
 'STPG1',
 'NIPAL3',
 'LAS1L',
 'ENPP4',
 'SEMA3F',
 'CFTR',
 'ANKIB1',
 'CYP51A1',
 'KRIT1',
 'RAD52',
 'BAD',
 'LAP3',
 'CD99',
 'HS3ST1',
 'AOC1',
 'WNT16',
 'HECW1',
 'MAD1L1',
 'LASP1',
 'SNX11',
 'TMEM176A',
 'M6PR',
 'KLHL13',
 'CYP26B1',
 'ICA1',
 'DBNDD1',
 'ALS2',
 'CASP10',
 'CFLAR',
 'TFPI',
 'NDUFAF7',
 'RBM5',
 'MTMR7',
 'SLC7A2',
 'ARF5',
 'SARM1',
 'POLDIP2',
 'PLXND1',
 'AK2',
 'CD38',
 'FKBP4',
 'KDM1A',
 'RBM6',
 'CAMKK1',
 'RECQL',
 'VPS50',
 'HSPB6',
 'ARHGAP33',
 'NDUFAB1',
 'PDK4',
 'SLC22A16',
 'ZMYND10',
 'ABCB5',
 'ARX',
 'SLC25A13',
 'ST7',
 'CDC27',
 'SLC4A1',
 'CALCR',
 'HCCS',
 'DVL2',
 'PRSS22',
 'UPF1',
 'SKAP2',
 'SLC25A5',
 'MCUB',
 'HOXA11',
 'POLR2J',
 'DHX33',
 'MEOX1',
 'THSD7A',
 'LIG3',
 'RPAP3',
 'ACSM3',
 'REXO5',
 'CIAPIN1',
 'SPPL2B',
 'FAM214B',
 'COPZ2',
 'PRKAR2B',
 'MSL3',
 'CREBBP',
 'TSPOAP1',
 'MPO',
 'PON1',
 'GCFC2',
 'WDR54',
 'CROT',
 'ABCB4',
 'KMT2E',
 'RHBDD2',
 'SOX8',
 'IBTK',
 'ZNF195',
 'MYCBP2',
 'FBXL3',
 'ITGAL',
 'PDK2',
 'ITGA3',
 'ZFX',
 'LAMP2',
 'ITGA2B',
 'ASB4',
 'GDE1',
 'REX1BD',
 'CRLF1',
 'OSBPL7',
 'TMEM98',
 'YBX2',
 'KRT33A',
 'MAP3K14',
 'ABCC8',
 'CACNG3',
 'TMEM132A',
 'AP2B1',
 'TAC1',
 'ZNF263',
 'CX3CL1',
 'SPATA20',
 'CACNA1G',
 'TNFRSF12A',
 'DLX6',
 'MAP3K9',
 'RALA',
 'BAIAP2L1',
 'KDM7A',
 'ETV1',
 'AGK',
 'ALDH3B1',
 'TTC22',
 'PHTF2',
 'CCL26',
 'FARP2',
 'USH1C',
 'GGCT',
 'DBF4',
 'TBXA2R',
 'IFRD1',
 'LGALS14',
 'COX10',
 'GTF2IRD1',
 'PAF1',
 'VPS41',
 'ARHGAP44',
 'ELAC2',
 'SCIN',
 'ARSD',
 'PNPLA4',
 'MYH13',
 'ADIPOR2',
 'CDKL3',
 'UPP2',
 'PRSS21',
 'MARK4',
 'PROM1',
 'CCDC124',
 'CEACAM21',
 'PAFAH1B1',
 'NOS2',
 'DNAH9',
 'KIAA0100',
 'SLC13A2',
 'GAS7',
 'TRAPPC6A',
 'MATK',
 'CEACAM7',
 'CD79B',
 'SCN4A',
 'ST7L',
 'TKTL1',
 'PAX6',
 'RPUSD1',
 'RHBDF1',
 'LUC7L',
 'CACNA2D2',
 'BAIAP3',
 'TSR3',
 'PIGQ',
 'CRAMP1',
 'TEAD3',
 'SELE',
 'DNAJC11',
 'FMO3',
 'MYLIP',
 'NOX1',
 'E2F2',
 'PSMB1',
 'SYN1',
 'JARID2',
 'CDKL5',
 'CAMK1G',
 'CDK11A',
 'NADK',
 'TFAP2B',
 'TFAP2D',
 'DLEC1',
 'CYTH3',
 'ADAM22',
 'SYPL1',
 'CYB561',
 'SPAG9',
 'CELSR3',
 'AASS',
 'PLEKHG6',
 'SS18L2',
 'MPND',
 'MGST1',
 'CRY1',
 'PGLYRP1',
 'NFIX',
 'ST3GAL1',
 'MMP25',
 'IL32',
 'PKD1',
 'MAPK8IP2',
 'MED24',
 'RHOBTB2',
 'HEATR5B',
 'SEC62',
 'RPS20',
 'CSDE1',
 'UBE3C',
 'REV3L',
 'TENM1',
 'PAX7',
 'MASP2',
 'IYD',
 'FAM76A',
 'TRAF3IP3',
 'POMT2',
 'VTA1',
 'MLXIPL',
 'BAZ1B',
 'RANBP9',
 'ETV7',
 'SPRTN',
 'EEF1AKNMT',
 'DYRK4',
 'ZNF207',
 'UQCRC1',
 'STARD3NL',
 'CD9',
 'HHATL',
 'NCAPD2',
 'IFFO1',
 'GIPR',
 'PHF7',
 'SEMA3G',
 'NISCH',
 'STAB1',
 'FUZ',
 'SLC6A13',
 'IDS',
 'PRSS3',
 'ZNF200',
 'CD4',
 'LRRC23',
 'BTK',
 'HFE',
 'SCMH1',
 'FYN',
 'HIVEP2',
 'FMO1',
 'ELOA',
 'LYPLA2',
 'CLCN6',
 'MRC2',
 'NME1-NME2',
 'SLC6A7',
 'TSPAN9',
 'BTBD7',
 'APBA3',
 'MKS1',
 'ABHD5',
 'ANOS1',
 'AKAP8L',
 'MBTD1',
 'UTP18',
 'RNF216',
 'TTC19',
 'PTBP1',
 'DPF1',
 'SYT7',
 'LARS2',
 'PIK3C2A',
 'PLAUR',
 'ANLN',
 'WIZ',
 'RABGAP1',
 'DCN',
 'QPCTL',
 'PPP5C',
 'CEP68',
 'MAP4K3',
 'ZBTB32',
 'TYROBP',
 'TMEM159',
 'GABRA3',
 'BRCA1',
 'ERCC1',
 'CD22',
 'SEMA3B',
 'MBTPS2',
 'PRICKLE3',
 'LTF',
 'EXTL3',
 'NR1H4',
 'ELOVL5',
 'ALOX5',
 'KDM5D',
 'CALCOCO1',
 'UBR7',
 'MAP4K5',
 'EHD3',
 'PSMC4',
 'MAN2B2',
 'SLC7A14',
 'CLDN11',
 'SLC25A39',
 'MVP',
 'NUB1',
 'PGM3',
 'RWDD2A',
 'CLK1',
 'POLR3B',
 'ANGEL1',
 'RNF14',
 'DNASE1L1',
 'DDX11',
 'HEBP1',
 'GPRC5A',
 'MAMLD1',
 'CD6',
 'TACC3',
 'UFL1',
 'POLA2',
 'ZC3H3',
 'CAPN1',
 'ACP3',
 'MDH1',
 'SLC30A9',
 'MTMR11',
 'COX15',
 'CCDC88C',
 'YAF2',
 'ZMYND11',
 'WAS',
 'DPEP1',
 'BID',
 'MATR3',
 'NPC1L1',
 'XYLT2',
 'RGPD5',
 'STMN4',
 'NUDCD3',
 'ISL1',
 'CHDH',
 'IL20RA',
 'CLCA1',
 'CLCA4',
 'GLT8D1',
 'ATP2C1',
 'IGF1',
 'SLC38A5',
 'RALBP1',
 'RUFY3',
 'CNTN1',
 'SLC11A1',
 'WWTR1',
 'AGPS',
 'CXorf56',
 'ATP1A2',
 'TTC27',
 'ZNF582',
 'VSIG2',
 'PHLDB1',
 'MARCO',
 'CYP24A1',
 'PRDM11',
 'SYT13',
 'SNAI2',
 'CD74',
 'HGF',
 'ZRANB1',
 'NCDN',
 'ADGRA2',
 'ZFP64',
 'MNAT1',
 'SAMD4A',
 'RUNX3',
 'MRE11',
 'PLEKHB1',
 'SERPINB1',
 'CYP3A43',
 'SLC7A9',
 'SPAST',
 'NRXN3',
 'OSBPL5',
 'AQR',
 'CPS1',
 'C8B',
 'FHL1',
 'RTF2',
 'GABRA1',
 'NLRP2',
 'SLC45A4',
 'RNF10',
 'ZNF839',
 'ZDHHC6',
 'GRAMD1B',
 'RNH1',
 'NDUFS1',
 'RB1CC1',
 'ERP44',
 'ALAS1',
 'BIRC3',
 'AKAP11',
 'GLRX2',
 'SNAPC1',
 'DERA',
 'STRAP',
 'ABCC2',
 'DEF6',
 'PLEKHO1',
 'GCLM',
 'UBR2',
 'EHD2',
 'DEPDC1',
 'CCDC28A',
 'RRAGD',
 'HSF2',
 'PHF20',
 'HSD17B6',
 'NR1H3',
 'TYMP',
 'NCAPH2',
 'TOMM34',
 'SEC63',
 'KPNA6',
 'VIM',
 'FAS',
 'RNASET2',
 'CD44',
 'KCNG1',
 'AGPAT4',
 'SLAMF7',
 'BTN3A1',
 'MIPEP',
 'PRKCH',
 'INSRR',
 'IFNGR1',
 'B4GALT7',
 'SH2D2A',
 'VRK2',
 'TNFRSF1B',
 'VEZT',
 'POU2F2',
 'BRD9',
 'SNX1',
 'TBPL1',
 'ARNTL2',
 'BCLAF1',
 'SLC39A9',
 'ANK1',
 'IBSP',
 'TFB1M',
 'RABEP1',
 'HMGB3',
 'NUP160',
 'BAK1',
 'MUSK',
 'IKZF2',
 'GRN',
 'FAM13B',
 'ARHGAP31',
 'CENPQ',
 'SARS1',
 'RANBP3',
 'ARID4A',
 'EIPR1',
 'PNPLA6',
 'IFT88',
 'ALG1',
 'ZCCHC8',
 'ABCF2',
 'CHPF2',
 'LRRC7',
 'FUT8',
 'UBA6',
 'GAB2',
 'ATP6V0A1',
 'PIAS1',
 'SLC4A7',
 'APBA2',
 'MAP2K3',
 'EFCAB1',
 'TMSB10',
 'ASTE1',
 'RNF19A',
 'PEX3',
 'GABARAPL2',
 'MYOC',
 'SH3YL1',
 'FAM136A',
 'VCL',
 'DEPDC1B',
 'DAPK2',
 'NSMAF',
 'ADSS2',
 'STAP1',
 'TIMP2',
 'RFC1',
 'TBC1D23',
 'CUL3',
 'MYOM2',
 'OTC',
 'CYP46A1',
 'ZZZ3',
 'SLC18A1',
 'USP2',
 'CASR',
 'TUBG2',
 'RPL26L1',
 'FLT4',
 'NSUN2',
 'FBXO42',
 'MFAP3',
 'MRI1',
 'METTL1',
 'HOXC8',
 'AGA',
 'PI4K2B',
 'BOD1L1',
 'MAT2B',
 'TLL1',
 'EDC4',
 'TRIO',
 'VCAN',
 'CLEC16A',
 'MSR1',
 'CDH1',
 'MTREX',
 'DNAH5',
 'ZFYVE16',
 'RIPOR1',
 'C6',
 'RAI14',
 'SOX30',
 'PNKP',
 'BEST2',
 'PHLPP2',
 'SPDL1',
 'STAU2',
 'SLC66A1',
 'CTNS',
 'RTN4R',
 'PHF23',
 'CDH10',
 'INPP4A',
 'RAB27B',
 'PSMA4',
 'MYO16',
 'LSG1',
 'PARP3',
 'TNC',
 'THAP3',
 'RIPOR3',
 'TDP1',
 'AIFM2',
 'C2orf83',
 'SPATA7',
 'MED17',
 'RETSAT',
 'CAPG',
 'AP2S1',
 'USH2A',
 'ZPBP',
 'TG',
 'ADAM28',
 'BARX2',
 'DCUN1D1',
 'JADE2',
 'ZIC2',
 'LCP2',
 'TRIT1',
 'ADRB1',
 'GUCA2B',
 'CUL7',
 'CTNNA1',
 'PHKA2',
 'CNTLN',
 'EPHA3',
 'HSPA5',
 'DSG2',
 'GEMIN8',
 'OFD1',
 'GPM6B',
 'MAGEC2',
 'PREX2',
 'WDR37',
 'YTHDC2',
 'CTPS2',
 'ATP6V1H',
 'POLR2B',
 'FAM214A',
 'ARAP2',
 'TPR',
 'CP',
 'KATNIP',
 'DTNBP1',
 'XK',
 'ANO2',
 'C12orf4',
 'SCML1',
 'WWC3',
 'ARHGAP6',
 'FAM184B',
 'MAP4',
 'GOPC',
 'ROS1',
 'USP28',
 'HDAC9',
 'TSPAN17',
 'NOP16',
 'CC2D2A',
 'RRM2B',
 'ZNF800',
 'TNFRSF17',
 'SNX29',
 'LMO3',
 'MRPS10',
 'GUCA1A',
 'RSF1',
 'VPS13D',
 'CELF2',
 'FAM120A',
 'R3HDM1',
 'COL9A2',
 'KITLG',
 'ERCC8',
 'ADAMTS6',
 'H6PD',
 'VAMP3',
 'PER3',
 'UTS2',
 'TNFRSF9',
 'EPN3',
 'LTBP1',
 'RCN1',
 'ELN',
 'RFC2',
 'ARID1B',
 'CLPTM1L',
 'NEDD4L',
 'FOXP3',
 'PPP1R3F',
 'HEXB',
 'PTCD2',
 'NEXMIF',
 'JKAMP',
 'DKK3',
 'ARHGEF5',
 'NFE2L3',
 'MCUR1',
 'LIMA1',
 'LETMD1',
 'SLC4A8',
 'LAMC3',
 'PTGER3',
 'TNIP3',
 'MAPK9',
 'COL23A1',
 'BCAR1',
 'FAM160A2',
 'HERPUD1',
 'HOMER3',
 'RAD51',
 'POLQ',
 'PIK3CB',
 'CYBA',
 'THOC3',
 'HEBP2',
 'MPHOSPH9',
 'PLEKHA5',
 'PRSS8',
 'SIKE1',
 'RRP12',
 'FNIP2',
 'MSMO1',
 'TTC17',
 'ALX4',
 'FSTL4',
 'FOXN3',
 'METTL24',
 'AKR7A2',
 'MRTO4',
 'NNAT',
 'USE1',
 'MCF2L2',
 'NRIP2',
 'LAMA3',
 'AP5M1',
 'ANAPC4',
 'KCNQ1',
 'TRAPPC3',
 'THRAP3',
 'PHPT1',
 'ENTPD2',
 'LY75',
 'ARID4B',
 'OPN3',
 'SDCCAG8',
 'PTPRN',
 'HHAT',
 'KIF1B',
 'FOXC1',
 'TBC1D22A',
 'SYNE2',
 'PLEKHH1',
 'ATP9A',
 'SPO11',
 'CBLN4',
 'CHRDL2',
 'FAM168A',
 'RELT',
 'GALC',
 'NOP58',
 'SZRD1',
 'KCNH2',
 'CUL1',
 'FAM114A2',
 'CYFIP2',
 'TAB2',
 'GINM1',
 'EIF2AK2',
 'USP36',
 'KMT2C',
 'MCOLN3',
 'CCDC85A',
 'PUM2',
 'MRPL43',
 'ITIH4',
 'ITIH1',
 'HPF1',
 'ZFR',
 'ZNF280C',
 'NPFFR2',
 'PHF21B',
 'TRAF1',
 'RC3H2',
 'IL17RB',
 'TRAF3IP2',
 'GYG2',
 'DCBLD2',
 'SERPINB3',
 'SOAT1',
 'PKP2',
 'MSH4',
 'F7',
 'GDI2',
 'PRDM1',
 'ATG5',
 'TMCC3',
 'PITHD1',
 'MTA3',
 'USP13',
 'ATP11B',
 'LAMC2',
 'CDK14',
 'SEC61A1',
 'PPP1R12A',
 'RASGRF1',
 'CAMK2B',
 'CROCC',
 'POLR3E',
 'ATP2B4',
 'ZC3H11A',
 'RIOK2',
 'YIPF1',
 'NDC1',
 'DGKG',
 'FLYWCH1',
 'UNKL',
 'TBXAS1',
 'PARP12',
 'ALDH18A1',
 'TARBP1',
 'GATB',
 'MXD1',
 'CDK17',
 'DNAJC25',
 'SLC2A3',
 'PSD',
 'CTDP1',
 'YBX3',
 'STYK1',
 'WNK1',
 'CCAR1',
 'OGFR',
 'GNA15',
 'CREB3L3',
 'PIGV',
 'PTPRU',
 'SNRNP40',
 'RIMBP2',
 'COL11A1',
 'QSER1',
 'MPC1',
 'ACAA1',
 'BCAT1',
 'HDAC7',
 'LZTS1',
 'PRDM6',
 'WNT8A',
 'SPAG4',
 'NCKAP1',
 'MRPS35',
 'GUCY1B1',
 'SFSWAP',
 'TNK2',
 'MON2',
 'CDH3',
 'ARSF',
 'GPBP1',
 'DGAT2',
 'ZNF112',
 'CS',
 'LTK',
 'MRPS24',
 'ELMO2',
 'WAPL',
 'VMP1',
 'APPBP2',
 'POLD1',
 'SEZ6',
 'EIF4B',
 'SLC6A16',
 'BICRA',
 'SPHK2',
 'RPL18',
 'CA11',
 'ISOC2',
 'U2AF2',
 'EPN1',
 'MED29',
 'AHRR',
 'GSC2',
 'ZNF275',
 'MTMR1',
 'GPC1',
 'ADCK1',
 'HAGH',
 'RNF4',
 'CASP8',
 'LIMCH1',
 'INTS13',
 'TM7SF3',
 'DLX3',
 'SPA17',
 'TSPAN32',
 'CCN5',
 'DMRT3',
 'ST3GAL6',
 'ATP2C2',
 'NGFR',
 'CDON',
 'TAF2',
 'HIPK2',
 'TNPO3',
 'RFXANK',
 'TMEM161A',
 'LPAR2',
 'CTSA',
 'SUGP2',
 'SLC12A2',
 'SNX24',
 'EYA2',
 'CNN2',
 'ABCA7',
 'SNCAIP',
 'DDX20',
 'BTBD1',
 'FAR2',
 'BCAS1',
 'POU1F1',
 'CHI3L2',
 'SBNO2',
 'PMS1',
 'HMG20B',
 'CALCRL',
 'TAF11',
 'ANKS1A',
 'AP3D1',
 'ZNF76',
 'SLC9A3R2',
 'NTHL1',
 'UHRF1BP1',
 'GNAI3',
 'IPO5',
 'OAT',
 'WDR3',
 'PKN2',
 'WDR18',
 'TRAM2',
 'NTN1',
 'GLP2R',
 'MCM10',
 'DGKA',
 'ERBB3',
 'ROPN1',
 'ANKRD44',
 'KARS1',
 'ADAT1',
 'PDIA5',
 'TBC1D22B',
 'NDUFB4',
 'SPEN',
 'MYLK',
 'ZC3H15',
 'MAP2K4',
 'PACC1',
 'SNAP91',
 'SLK',
 'CYB5R4',
 'COL17A1',
 'GSTO2',
 'SEC61A2',
 'PRKCQ',
 'TLE2',
 'ASB1',
 'FAM107B',
 'ME1',
 'TBC1D1',
 'CDK13',
 'MTHFD2',
 'SLC9A7',
 'FOXJ2',
 'YBX1',
 'PDE4A',
 'PPP2R5A',
 'CTNNA2',
 'ELAVL1',
 'TIE1',
 'DIP2B',
 'SMARCD1',
 'KDM4A',
 'NFYC',
 'ZMYND12',
 'SLC9A3',
 'NGEF',
 'ASPM',
 'CD84',
 'ELOVL1',
 'SPI1',
 'POLR1H',
 'MPPED2',
 'CLDN18',
 'ZBTB11',
 'ATXN3',
 'GOLGA5',
 'FGFR2',
 'LRRC40',
 'ISOC1',
 'EML1',
 'TRMT11',
 'THUMPD1',
 'MSANTD3',
 'KIF26A',
 'ATG2B',
 'ARFGEF1',
 'ACSM2B',
 'ZFAT',
 'MTFR1',
 'STAG3',
 'FECH',
 'MYO9A',
 'DDX3Y',
 'PFKP',
 'IDI1',
 'SP100',
 'KLF6',
 'PLPP1',
 'NEO1',
 'TRAM1',
 'PHKA1',
 'TNFRSF1A',
 'CACNB1',
 'EVI5',
 'STOML1',
 ...]

In [7]:
intersection = list(set(landmark_names) & set(column_names))

print(len(intersection))

956

In [8]:
missing = list(set(landmark_names) - set(column_names))
missing

['NARFL',
 'EPRS',
 'TMEM2',
 'H2AFV',
 'TMEM5',
 'TMEM110',
 'HIST1H2BK',
 'FAM57A',
 'PAPD7',
 'ATP5S',
 'FAM69A',
 'KIAA0355',
 'AARS',
 'SQRDL',
 'WRB',
 'KIAA0907',
 'KIF1BP',
 'TSTA3',
 'HIST2H2BE',
 'HDGFRP3',
 'HN1L',
 'IKBKAP']

In [9]:
landmark_ids = list(landmarks["Entrez ID"])
landmark_ids = [str(id) for id in landmark_ids]
print(landmark_ids)

['3638', '2309', '1001', '4998', '3682', '1022', '2353', '1021', '1019', '1017', '3693', '1029', '1027', '1026', '2356', '1052', '1050', '1062', '85377', '1070', '11065', '11072', '11073', '11041', '23029', '11044', '23038', '23039', '26993', '11031', '23013', '23014', '23011', '11000', '11004', '11007', '11011', '11014', '63933', '23097', '3725', '23061', '11098', '23076', '23077', '1111', '3775', '1123', '1153', '50810', '50813', '50814', '23200', '11230', '23210', '23212', '25874', '84159', '11232', '11200', '25825', '25839', '25803', '25805', '200734', '11182', '23161', '11188', '16', '23', '25', '23149', '23142', '11168', '30', '39', '47', '11142', '11151', '23139', '23131', '25793', '11157', '11137', '3800', '3815', '2523', '2534', '2548', '1213', '1212', '2542', '2553', '3895', '2582', '2597', '1282', '1277', '23321', '25987', '23325', '23326', '10013', '11344', '23335', '23338', '23300', '25966', '11325', '25976', '10007', '11319', '25932', '11284', '23271', '11261', '23244', '23223', '23224', '3909', '3925', '3930', '50865', '2625', '2624', '3964', '3978', '3988', '2673', '2690', '1385', '116832', '1399', '1398', '23443', '10131', '10146', '10112', '10123', '23410', '10099', '23386', '10051', '23365', '23368', '10057', '10059', '10058', '23378', '10038', '10046', '10049', '2736', '2745', '1429', '2771', '2770', '2767', '2769', '2778', '1445', '1459', '1454', '1452', '1465', '10237', '10245', '23522', '23530', '23536', '10227', '10221', '23512', '10206', '10190', '60493', '10174', '10180', '23499', '10150', '23463', '10153', '2810', '10165', '2817', '1500', '1509', '1514', '2852', '1534', '2887', '2886', '2896', '23670', '10362', '23647', '23658', '23659', '10318', '23636', '23635', '10329', '10320', '2908', '10298', '10270', '10273', '23585', '23588', '2920', '10276', '23597', '10285', '1605', '1616', '2946', '2954', '2958', '2956', '60528', '1635', '1633', '2961', '1643', '1647', '1666', '1662', '1677', '1676', '10491', '10493', '10494', '10489', '10451', '10450', '10434', '10398', '1738', '84617', '1759', '57019', '1788', '1786', '57048', '200081', '10513', '10525', '10523', '58533', '57215', '10589', '10557', '10559', '57192', '1802', '1829', '1831', '1848', '1846', '1845', '84722', '1861', '1870', '1891', '58472', '57149', '57147', '58478', '58497', '57178', '10652', '10668', '10641', '10644', '10617', '10610', '10606', '10695', '10670', '10682', '10681', '94239', '1906', '1950', '1958', '1956', '1978', '1983', '1981', '1994', '9019', '9016', '9053', '84890', '10776', '10775', '10782', '57406', '9093', '9097', '10765', '10730', '10732', '22794', '22796', '10797', '256364', '9112', '9124', '9128', '9126', '9133', '9134', '9143', '9170', '9183', '9181', '10898', '10892', '22889', '22883', '22887', '10857', '124583', '22841', '22809', '22823', '22827', '10845', '9212', '9217', '9221', '10810', '10813', '10818', '83743', '9246', '9267', '9261', '9276', '9270', '9275', '9289', '55008', '10972', '10973', '55012', '55011', '22934', '10954', '10953', '55033', '10969', '55038', '10962', '147179', '22908', '22926', '10915', '9375', '22905', '10921', '8050', '8061', '10904', '8091', '57761', '55111', '55127', '55129', '55148', '79090', '79094', '79080', '9448', '9455', '9467', '79006', '9488', '9491', '79071', '79073', '81533', '80204', '55256', '80212', '81544', '57804', '9517', '9519', '9531', '8204', '8202', '9533', '9552', '8243', '55179', '8270', '79143', '79170', '79174', '93487', '79187', '56654', '55324', '30001', '66008', '80347', '29082', '29083', '9641', '8312', '9637', '8321', '9653', '9650', '8324', '8318', '7015', '7016', '9670', '9686', '7027', '9688', '7020', '8349', '9697', '9695', '9690', '7043', '7048', '8396', '7077', '7074', '7088', '7082', '93594', '7099', '29103', '148022', '9712', '9710', '9702', '9703', '9709', '102', '9738', '128', '9761', '7105', '8440', '8446', '8444', '142', '7106', '154', '9797', '178', '7153', '7158', '7157', '7159', '8480', '7165', '7168', '80349', '9801', '9805', '9813', '9817', '9833', '207', '54205', '9842', '211', '8503', '8508', '8520', '9851', '9854', '55556', '226', '9847', '56889', '8518', '230', '9868', '8553', '8550', '9897', '8574', '8573', '8569', '7264', '291', '91137', '7296', '79643', '55699', '54386', '65057', '55604', '55608', '56940', '9903', '55620', '9917', '9918', '9915', '9924', '9928', '9926', '9943', '310', '8607', '323', '79600', '329', '9961', '332', '56997', '8624', '348', '351', '355', '7319', '9988', '8678', '6009', '7358', '387', '392', '7376', '6050', '7398', '56924', '65123', '80758', '375346', '80746', '54499', '55748', '55746', '79716', '8720', '427', '8731', '8726', '54438', '8727', '54442', '7416', '55793', '466', '481', '6117', '6119', '6118', '7466', '7485', '7494', '6182', '6184', '6193', '6195', '6194', '388650', '501', '54512', '55847', '8800', '8804', '8821', '533', '8826', '7511', '54541', '8835', '8837', '8851', '79850', '55893', '8870', '572', '8869', '7538', '8884', '581', '8878', '8895', '595', '596', '6251', '6253', '6275', '6284', '55818', '55825', '54505', '55837', '27095', '64080', '8900', '27032', '622', '8914', '637', '642', '644', '79921', '652', '664', '665', '79947', '8974', '670', '672', '53343', '6304', '8985', '54681', '79961', '8996', '695', '6342', '6347', '5018', '5019', '7690', '5048', '5054', '5058', '5050', '6390', '5096', '5092', '79902', '54623', '55958', '701', '727', '7750', '780', '5110', '5111', '6443', '5106', '5108', '6461', '6464', '5154', '6499', '54733', '27109', '29763', '808', '813', '823', '831', '835', '836', '840', '843', '847', '6500', '868', '6509', '873', '874', '7852', '54881', '7849', '890', '891', '896', '899', '5211', '7874', '7866', '7867', '5223', '5236', '5255', '5257', '5261', '6597', '6599', '54807', '5287', '5289', '5290', '54850', '27242', '27244', '29890', '30849', '902', '30836', '51097', '949', '7905', '958', '960', '965', '26054', '976', '6603', '26064', '983', '6616', '5300', '991', '993', '994', '51001', '998', '51005', '6622', '51015', '5321', '7982', '51021', '51024', '51026', '91949', '5331', '7994', '51031', '6657', '6659', '6676', '5355', '51053', '51056', '4016', '5347', '6696', '5366', '6697', '5357', '5359', '5373', '4043', '51070', '51071', '54915', '4067', '29928', '4088', '29937', '54957', '29911', '29916', '26036', '27346', '26020', '27336', '26001', '29978', '6709', '6714', '5423', '5427', '5440', '6772', '6774', '5438', '6777', '6790', '6793', '51160', '4125', '4144', '51170', '5467', '5468', '4154', '5480', '5498', '4172', '64422', '64429', '64428', '51116', '26136', '26128', '6804', '6810', '6812', '6813', '6839', '6832', '6850', '26292', '4200', '6856', '5525', '5529', '4208', '4216', '5547', '6894', '4232', '90861', '5566', '5580', '5583', '51282', '51293', '5588', '4282', '51203', '26227', '6908', '6909', '6919', '6915', '5607', '5601', '5603', '6944', '5613', '5627', '5641', '4303', '4312', '4313', '6990', '4331', '5654', '6988', '51375', '51382', '51385', '5696', '3033', '3028', '5699', '3066', '3091', '3098', '89910', '28969', '51335', '5708', '5710', '5715', '5716', '5720', '5721', '5743', '5747', '5770', '3108', '5782', '3122', '5777', '5792', '5796', '51495', '5788', '4482', '3156', '3162', '3157', '51422', '64746', '51465', '51466', '64781', '5827', '5829', '5831', '5836', '5873', '3206', '3202', '5867', '5880', '5883', '5891', '5889', '5898', '5899', '4582', '3251', '3280', '26511', '51569', '26520', '51599', '5909', '5900', '5927', '5921', '5925', '4609', '4605', '4616', '5971', '3303', '3300', '3308', '4638', '4651', '5982', '3315', '3312', '5993', '3329', '5985', '5986', '3337', '5997', '2017', '4690', '2042', '2037', '3385', '3383', '2048', '3398', '2065', '2064', '2063', '2058', '64943', '51635', '3416', '2109', '4780', '4783', '2115', '2113', '4775', '4776', '4791', '4792', '4793', '4794', '2131', '3454', '3486', '3482', '3480', '2146', '2185', '2184', '2195', '24149', '51719', '4817', '51742', '3508', '4836', '4850', '4846', '4860', '4851', '4864', '3551', '4891', '4893', '2222', '3553', '3566', '2264', '2263', '2274', '3597', '2288', '63874', '85236', '4925', '4927', '4931', '3611', '3628']

In [10]:
CCLE_ids = [name.split()[-1] for name in df.columns][1:]
CCLE_ids= [id[1:-1] for id in CCLE_ids]
print(CCLE_ids)

['7105', '64102', '8813', '57147', '55732', '2268', '3075', '2519', '2729', '4800', '90529', '57185', '81887', '22875', '6405', '1080', '54467', '1595', '889', '5893', '572', '51056', '4267', '9957', '26', '51384', '23072', '8379', '3927', '29916', '55365', '4074', '90293', '56603', '3382', '79007', '57679', '843', '8837', '7035', '55471', '10181', '9108', '6542', '381', '23098', '26073', '23129', '204', '952', '2288', '23028', '10180', '84254', '5965', '55610', '126393', '115703', '4706', '5166', '85413', '51364', '340273', '170302', '10165', '7982', '996', '6521', '799', '3052', '1856', '64063', '5976', '8935', '292', '55013', '3207', '5439', '56919', '4222', '221981', '3980', '79657', '6296', '81691', '57019', '56928', '80256', '51226', '5577', '10943', '1387', '9256', '4353', '5444', '6936', '84058', '54677', '5244', '55904', '57414', '30812', '25998', '7748', '23077', '26224', '3683', '5164', '3675', '7543', '3920', '3674', '51666', '51573', '55049', '9244', '114881', '26022', '51087', '3883', '9020', '6833', '10368', '54972', '163', '6863', '10127', '6376', '64847', '8913', '51330', '1750', '4293', '5898', '55971', '80853', '2115', '55750', '221', '55001', '57157', '10344', '9855', '10083', '79017', '10926', '6915', '3475', '56891', '1352', '9569', '54623', '27072', '9912', '60528', '85477', '414', '8228', '8735', '79602', '51265', '151531', '10942', '57787', '8842', '115098', '90273', '5048', '4843', '1770', '9703', '9058', '8522', '79090', '4145', '1087', '974', '6329', '54879', '8277', '5080', '113000', '64285', '55692', '9254', '8938', '115939', '9091', '57585', '7005', '6401', '55735', '2328', '29116', '27035', '1870', '5689', '6853', '3720', '6792', '57172', '728642', '65220', '7021', '83741', '9940', '9265', '53616', '6856', '1534', '9043', '1951', '10157', '55200', '51188', '84954', '4257', '1407', '8993', '4784', '6482', '64386', '9235', '5310', '23542', '9862', '23221', '54497', '7095', '6224', '7812', '9690', '5980', '10178', '5081', '10747', '389434', '199870', '80342', '29954', '51534', '51085', '9031', '10048', '51513', '83932', '51603', '8798', '7756', '7384', '83930', '928', '57467', '9918', '25900', '2696', '51533', '56920', '11188', '23166', '80199', '6540', '3423', '5646', '7752', '920', '10233', '695', '3077', '22955', '2534', '3097', '2326', '6924', '11313', '1185', '9902', '654364', '6534', '10867', '55727', '9546', '54903', '51099', '3730', '26993', '54799', '51096', '54476', '54902', '5725', '8193', '9066', '23395', '5286', '5329', '54443', '58525', '23637', '1634', '54814', '5536', '23177', '8491', '27033', '7305', '57146', '2556', '672', '2067', '933', '7869', '51360', '4007', '4057', '2137', '9971', '60481', '240', '8284', '57658', '55148', '11183', '30845', '5704', '23324', '57709', '5010', '51629', '9961', '51667', '5238', '112611', '1195', '55703', '23357', '9604', '1774', '1663', '50865', '9052', '10046', '923', '10460', '23376', '23649', '23144', '823', '55', '4190', '10463', '10903', '1355', '440193', '10138', '10771', '7454', '1800', '637', '9782', '29881', '64132', '84220', '81551', '23386', '3670', '55349', '53832', '1179', '22802', '55830', '27032', '3479', '92745', '10928', '22902', '1272', '6556', '25937', '8540', '63932', '477', '55622', '147948', '23584', '23187', '8685', '1591', '56981', '57586', '6591', '972', '3082', '54764', '23154', '25960', '55734', '4331', '23034', '864', '4361', '58473', '1992', '64816', '11136', '6683', '9369', '114879', '9716', '1373', '732', '2273', '51507', '2554', '55655', '57210', '9921', '55778', '64429', '57476', '6050', '4719', '9821', '23071', '211', '330', '11215', '51022', '6617', '51071', '11171', '1244', '50619', '51177', '2730', '23304', '30846', '55635', '25901', '58528', '3298', '51230', '8630', '10062', '1890', '29781', '10953', '11231', '23633', '7431', '355', '8635', '960', '3755', '56895', '57823', '11119', '4285', '5583', '3645', '3459', '11285', '9047', '7444', '7133', '55591', '5452', '65980', '6642', '9519', '56938', '9774', '55334', '286', '3381', '51106', '9135', '3149', '23279', '578', '4593', '22807', '2896', '51306', '57514', '55166', '6301', '8498', '5926', '7260', '10908', '8100', '56052', '55596', '10061', '54480', '57554', '2530', '55236', '9846', '535', '8554', '9497', '321', '5606', '79645', '9168', '28990', '25897', '8504', '11345', '4653', '26751', '84908', '7414', '55789', '23604', '8439', '159', '26228', '7077', '5981', '55773', '8452', '9172', '5009', '10858', '26009', '6570', '9099', '846', '27175', '51121', '2324', '54888', '54455', '4238', '84245', '4234', '3224', '175', '55300', '259282', '27430', '7092', '23644', '7204', '1462', '23274', '4481', '999', '23517', '1767', '9765', '79567', '729', '26064', '11063', '11284', '54831', '23035', '54908', '27067', '54896', '1497', '65078', '79142', '1008', '3631', '5874', '5685', '23026', '55341', '10039', '3371', '90326', '140876', '55775', '84883', '56918', '55812', '9440', '54884', '822', '1175', '7399', '11055', '7038', '10863', '8538', '54165', '23338', '7546', '3937', '54802', '153', '2981', '9820', '1495', '5256', '54875', '2042', '3309', '1829', '54960', '8481', '2824', '51438', '80243', '22884', '64848', '56474', '51606', '5431', '56204', '116984', '7175', '1356', '23247', '84062', '7504', '57101', '57102', '6322', '55841', '395', '27146', '4134', '57120', '6098', '57646', '9734', '26262', '51491', '57545', '50484', '168850', '608', '92017', '55885', '55173', '2978', '51773', '55187', '10659', '23196', '23518', '1298', '4254', '1161', '11174', '9563', '9341', '8863', '10911', '3604', '55040', '4052', '5954', '2006', '5982', '57492', '81037', '23327', '50943', '89801', '3074', '79810', '340533', '51528', '27122', '7984', '9603', '63933', '51474', '25875', '9498', '10319', '5733', '79931', '5601', '91522', '9564', '84067', '9709', '9454', '5888', '10721', '5291', '1535', '84321', '23593', '10198', '54477', '5652', '80143', '23223', '57600', '6307', '55761', '60529', '23105', '1112', '728464', '8574', '51154', '4826', '55850', '23101', '83714', '3909', '55745', '29945', '3784', '27095', '9967', '29085', '954', '4065', '51742', '23596', '10806', '5798', '55733', '23095', '2296', '25771', '23224', '57475', '10079', '23626', '140689', '25884', '23201', '84957', '2581', '51602', '26099', '3757', '8454', '10827', '26999', '23118', '116254', '5610', '57602', '58508', '55283', '114800', '23369', '84545', '3700', '3697', '54969', '51663', '55609', '10886', '112885', '7185', '54542', '55540', '10758', '8908', '131566', '6317', '6646', '5318', '4438', '2155', '2665', '639', '9474', '57458', '57095', '57504', '8975', '23200', '3918', '5218', '29927', '4659', '5923', '816', '9696', '55718', '493', '9877', '55781', '54432', '55706', '1608', '84256', '64718', '6916', '64761', '5832', '6894', '5188', '4084', '5128', '548645', '6515', '5662', '9150', '8531', '55359', '65125', '55749', '11054', '2769', '84699', '55650', '10076', '9410', '23504', '1301', '79832', '51660', '30', '586', '51564', '11178', '93166', '7478', '6676', '10787', '60488', '2983', '6433', '10188', '23041', '1001', '416', '65056', '84649', '7771', '1431', '4058', '64951', '63916', '23063', '81671', '10513', '5424', '124925', '1975', '28968', '29998', '56848', '6141', '770', '79763', '11338', '29924', '55588', '57491', '2928', '10838', '8776', '2817', '57143', '3029', '6047', '841', '22998', '55726', '51768', '1747', '53340', '10077', '8839', '58524', '10402', '9914', '4804', '50937', '6873', '28996', '23534', '8625', '54929', '9170', '5476', '10147', '6558', '28966', '2139', '1265', '10347', '9627', '11218', '53339', '55711', '8537', '5449', '1117', '22904', '5378', '10362', '10203', '6882', '23294', '8943', '7629', '9351', '4913', '54887', '2773', '3843', '4942', '10885', '5586', '57418', '9697', '9423', '9340', '55388', '1606', '2065', '54763', '91526', '3735', '23536', '10954', '55633', '4710', '23013', '4638', '55854', '6416', '55248', '9892', '9748', '51167', '1308', '119391', '55176', '5588', '7089', '51665', '83641', '4199', '23216', '8621', '10797', '84679', '55810', '4904', '5141', '5525', '1496', '1994', '7075', '57609', '6602', '9682', '4802', '84217', '6550', '25791', '259266', '8832', '64834', '6688', '30834', '744', '51208', '27107', '4287', '9950', '2263', '55631', '51015', '2009', '60487', '55623', '91283', '26153', '55102', '10565', '348158', '57623', '9650', '10734', '2235', '4649', '8653', '5214', '3422', '6672', '1316', '8611', '4756', '23471', '5255', '7132', '782', '7813', '9399', '5315', '54505', '30836', '79091', '7158', '7216', '51018', '387', '1659', '5590', '7544', '55699', '6857', '89795', '3421', '79641', '57595', '492', '6093', '865', '5165', '8692', '9759', '11186', '2261', '3430', '63897', '80347', '79990', '4205', '55593', '7030', '4943', '2182', '3632', '27238', '56850', '24140', '55771', '65055', '23250', '25885', '9741', '57217', '51447', '286749', '55133', '3796', '10235', '23198', '57560', '22933', '27248', '5526', '5837', '8712', '5307', '57113', '375449', '221395', '54549', '8756', '55746', '64710', '55737', '10294', '602', '8514', '10060', '51083', '29121', '139341', '4129', '6095', '1815', '7049', '8399', '54626', '483', '4734', '9488', '5597', '10681', '5873', '27440', '7353', '4040', '2984', '6343', '57661', '8518', '4925', '5217', '5774', '6710', '27071', '2255', '23446', '54916', '23293', '10640', '8218', '27006', '10272', '9993', '55658', '4335', '79364', '23210', '5423', '55808', '55062', '22844', '57704', '3340', '440', '10947', '1258', '10610', '1103', '26986', '10420', '29105', '1459', '11099', '8891', '815', '6949', '998', '26031', '2046', '6559', '56852', '490', '29850', '8440', '9448', '11320', '6160', '9948', '23161', '54860', '79658', '6196', '54556', '22846', '29995', '114049', '6400', '9319', '537', '6929', '28951', '26528', '53615', '51052', '6596', '9130', '60343', '29894', '140469', '79901', '28513', '5134', '55117', '51109', '5566', '22859', '6694', '87', '23503', '27330', '22905', '26469', '55679', '55515', '10290', '84708', '224', '7037', '6720', '7224', '27125', '7321', '64398', '9886', '8243', '3028', '2011', '3161', '55743', '29953', '8974', '2213', '4775', '51095', '37', '6793', '23291', '9744', '1400', '2121', '51009', '54847', '54820', '10335', '79041', '8907', '5817', '7515', '949', '54905', '4171', '54456', '56666', '83642', '8626', '80216', '3993', '5151', '1183', '54475', '6389', '6605', '54752', '55876', '5927', '4185', '5523', '10979', '8647', '10170', '922', '5743', '10644', '9175', '6480', '30009', '10129', '8301', '4905', '2736', '23332', '65993', '4854', '1207', '5522', '8463', '8726', '54825', '6620', '7251', '55421', '489', '771', '11343', '59277', '617', '9891', '54878', '9187', '55205', '8578', '3998', '51495', '26034', '23140', '50508', '2023', '6557', '56005', '57719', '51175', '55160', '7294', '9671', '3785', '6865', '64431', '54962', '6717', '8672', '79023', '10371', '51512', '10512', '55020', '38', '23151', '9620', '7479', '27332', '55972', '29090', '119', '2249', '9462', '9605', '7587', '4140', '5250', '64778', '2355', '27091', '27092', '285527', '23505', '6624', '60', '55034', '5337', '479', '284403', '1739', '7879', '55973', '25956', '9733', '55843', '113457', '5076', '23016', '22920', '23609', '4175', '25996', '10179', '5939', '11176', '25930', '4292', '7374', '2329', '27252', '8786', '113235', '5362', '10615', '88455', '7163', '32', '9618', '55824', '55094', '3385', '22978', '4162', '2239', '55796', '57662', '5909', '56949', '9138', '6813', '5609', '27231', '8527', '83992', '51412', '5915', '7155', '56889', '4791', '29089', '4660', '54431', '2975', '3566', '23032', '5063', '827', '1641', '6626', '9576', '56915', '1781', '54518', '4034', '143684', '51548', '7299', '10714', '88', '832', '7107', '10003', '79960', '203427', '7319', '2260', '8468', '27127', '2192', '8516', '8530', '4133', '9063', '273', '369', '56922', '27074', '2191', '10529', '55331', '3093', '5289', '55728', '57103', '7289', '8871', '108', '5527', '54715', '2782', '3205', '1906', '8028', '55063', '117', '26281', '27334', '9452', '4898', '7419', '5108', '57690', '9139', '1620', '83737', '27039', '58476', '51150', '57644', '80341', '7161', '54472', '51619', '27098', '862', '1015', '9984', '51661', '114880', '6507', '7520', '56925', '11262', '8569', '7145', '57455', '56681', '8556', '10411', '634', '29843', '51207', '23152', '3991', '2222', '5050', '4983', '173', '3835', '10590', '55604', '5236', '1653', '1785', '2037', '22999', '26002', '8417', '11158', '9817', '55510', '5794', '1638', '51006', '131544', '285220', '6344', '5991', '55183', '23011', '8671', '6595', '50700', '27244', '11043', '139212', '50509', '10847', '9933', '1361', '1136', '3781', '4850', '5663', '1371', '56650', '5891', '3320', '5933', '22839', '22997', '3080', '10403', '23431', '54665', '260425', '2920', '174', '1286', '6932', '28962', '1005', '50939', '57092', '55218', '384', '4208', '5788', '779', '5317', '79876', '9262', '8555', '22869', '4036', '440515', '65094', '11266', '65985', '9812', '6561', '93664', '56131', '56142', '56113', '51668', '23239', '5205', '3595', '6604', '55100', '2533', '58538', '55437', '9689', '5241', '114899', '4200', '55322', '905', '57579', '1310', '23136', '22837', '1741', '3776', '56256', '7188', '29093', '25929', '4986', '4779', '54437', '2932', '3693', '23085', '7514', '11342', '80036', '79728', '23033', '57226', '594', '7994', '79670', '9706', '79977', '3842', '5351', '5026', '3682', '22894', '10464', '81550', '26747', '23047', '5019', '10325', '1833', '1540', '10998', '25799', '79891', '55659', '54807', '55663', '9422', '6193', '2195', '91746', '25978', '64744', '10450', '10269', '56910', '84273', '5978', '3034', '54434', '2950', '334', '57613', '6579', '51729', '8668', '79570', '1307', '200081', '338', '8648', '60509', '22979', '3797', '10890', '2646', '3030', '22924', '790', '966', '3732', '63035', '546', '102157402', '2219', '55892', '2122', '9522', '5550', '57531', '81929', '22911', '57590', '5016', '29957', '4216', '29992', '57549', '5243', '7760', '231', '8895', '54700', '2017', '7481', '4528', '23259', '22996', '2060', '4998', '4258', '10523', '55054', '55230', '55624', '8438', '23139', '3301', '2683', '51510', '4799', '363', '27292', '51194', '2346', '27102', '51314', '54749', '29887', '22929', '10573', '3049', '80271', '4680', '2196', '55696', '10959', '56605', '54469', '3294', '55787', '5475', '7462', '10075', '9183', '79796', '4606', '50507', '8310', '8898', '23645', '51171', '7205', '43', '2512', '51593', '581', '51701', '94005', '9509', '28983', '56970', '9489', '5705', '51720', '1071', '4313', '4504', '54947', '2775', '55239', '6452', '8602', '118', '79944', '57544', '51637', '22795', '64395', '10992', '57542', '2778', '10059', '5744', '116154', '51290', '7022', '6790', '57091', '8544', '28971', '5990', '339175', '6820', '29929', '4849', '51206', '5775', '8886', '8570', '2767', '55616', '55741', '1789', '28954', '22974', '81572', '2036', '6564', '23348', '55608', '23483', '1795', '51161', '57017', '55287', '64147', '79822', '54675', '140850', '23368', '8455', '54498', '6614', '2280', '55968', '83959', '25943', '79175', '57593', '56265', '57506', '9762', '2160', '22803', '55857', '8655', '54997', '27131', '6128', '55423', '8550', '5027', '51575', '10741', '51433', '9962', '80024', '29058', '55184', '84678', '26074', '64211', '55617', '4938', '10985', '6175', '5829', '23409', '22895', '55614', '51605', '1114', '5037', '6910', '8315', '10961', '4842', '2521', '3476', '53827', '55900', '57655', '5349', '9843', '29965', '113540', '23415', '23193', '51291', '55285', '332', '3902', '8079', '78990', '57062', '7597', '25977', '393', '170961', '55760', '23186', '55668', '8425', '645', '6548', '10558', '10914', '8812', '57060', '5996', '83719', '51650', '4708', '10726', '10296', '3383', '29888', '11213', '4069', '6476', '79594', '7023', '10081', '51324', '26998', '51726', '55214', '7066', '8646', '2323', '9727', '84572', '10795', '2802', '8761', '30835', '79603', '57192', '84196', '1947', '55066', '16', '2734', '24137', '27327', '64857', '10683', '57106', '57605', '55763', '54439', '5459', '114882', '113878', '58484', '54517', '22798', '4897', '3912', '5172', '1811', '1738', '23335', '9352', '3568', '368', '54918', '3655', '11069', '51776', '23676', '2271', '23231', '7018', '55573', '51168', '54890', '350', '22861', '83394', '9552', '23594', '79776', '57084', '1357', '51530', '2099', '26575', '285', '84336', '4345', '151887', '1215', '5720', '55012', '54930', '84502', '4625', '1053', '23428', '55644', '51310', '55072', '23256', '55632', '25831', '3183', '57096', '11198', '9878', '8487', '7051', '26277', '1618', '90665', '57556', '54822', '7301', '79968', '825', '8773', '6913', '26227', '1299', '7430', '4637', '26523', '27285', '63967', '117584', '201294', '79157', '1808', '7042', '55105', '10762', '8318', '1312', '51816', '55350', '55862', '9209', '9117', '9942', '10013', '126370', '2568', '3881', '990', '139596', '8697', '8086', '23468', '2327', '51430', '4436', '4214', '1725', '29911', '120400', '372', '54566', '55151', '5711', '5742', '23511', '1384', '10044', '54187', '55357', '25861', '5146', '55280', '57715', '9044', '64376', '29760', '7093', '1592', '56165', '10580', '55118', '25805', '3589', '53904', '51322', '1390', '10101', '23430', '284422', '3096', '54209', '83795', '10321', '2289', '6732', '27154', '55168', '5225', '28978', '114327', '9436', '3326', '4295', '988', '3710', '7738', '1832', '23411', '3189', '80173', '3717', '3594', '25', '11332', '51100', '8317', '84144', '5125', '6319', '11018', '3983', '79956', '22931', '8829', '56952', '54873', '23555', '55506', '387680', '23031', '7593', '79629', '4650', '9424', '57828', '5714', '54620', '112755', '80270', '9739', '9274', '4113', '1943', '1153', '513', '255057', '83259', '266', '5616', '3483', '4670', '51257', '4713', '9524', '26517', '997', '4507', '126353', '283638', '5434', '5442', '610', '53841', '113177', '8045', '4616', '5064', '8174', '2872', '421', '27037', '5902', '29801', '84861', '51586', '3053', '9342', '1399', '8216', '4320', '27443', '6598', '9127', '91319', '6545', '23786', '100037417', '1652', '5008', '23523', '83874', '56241', '10291', '2687', '200312', '23541', '266629', '23384', '23759', '51733', '29799', '6634', '23481', '5594', '2678', '5625', '9647', '339665', '8940', '1417', '27128', '8220', '4242', '29775', '91355', '6576', '157', '50487', '3957', '26088', '7290', '23616', '23544', '3956', '89781', '113791', '402055', '23598', '11078', '24144', '23464', '91227', '1414', '129138', '51386', '4809', '85377', '5435', '6663', '79879', '9681', '9463', '23331', '23539', '79019', '55964', '6523', '6527', '11015', '1565', '10521', '11144', '6942', '150274', '25776', '56993', '27156', '7494', '51493', '9929', '25793', '9567', '84271', '9609', '7078', '9701', '6305', '25777', '1727', '10126', '25770', '55586', '91289', '25807', '11252', '25809', '10633', '162', '10042', '10043', '4744', '1120', '638', '3162', '27349', '8563', '4174', '164668', '410', '706', '23551', '23170', '23492', '5155', '49', '164633', '6122', '55954', '23543', '9145', '10454', '84164', '8897', '54471', '80832', '150379', '8542', '80339', '4627', '8911', '25813', '25828', '80020', '9402', '8664', '23112', '27352', '11020', '5816', '23313', '4689', '1439', '10478', '7380', '55007', '79734', '6767', '3560', '9978', '2033', '83746', '150356', '5905', '23264', '84844', '50', '171568', '55687', '5372', '27351', '64781', '23774', '9889', '23209', '83933', '54207', '63874', '23351', '2287', '56948', '1511', '2999', '3002', '55147', '10419', '1690', '11154', '5427', '79609', '6655', '8814', '51199', '5836', '114088', '5706', '64841', '80821', '1033', '10175', '10668', '51382', '55195', '26499', '5283', '145497', '5684', '10490', '26520', '2954', '9786', '283578', '161394', '10598', '23002', '145501', '9517', '79890', '5641', '8846', '22938', '1113', '3705', '51635', '5494', '51804', '57452', '51676', '145508', '2079', '3091', '9766', '6430', '6554', '1983', '5267', '6547', '23405', '79038', '4522

In [11]:
landmark_ids_set = set(landmark_ids)
CCLE_ids_set = set(CCLE_ids)

print(len(landmark_ids))
print(len(CCLE_ids))
print(len(landmark_ids_set))
print(len(CCLE_ids_set))

978
19221
978
19204

In [12]:
common = set(landmark_ids) & set(CCLE_ids)
missing = set(landmark_ids) - set(CCLE_ids)

print(len(common), len(missing))

978 0

In [13]:
common

{'10007',
 '1001',
 '10013',
 '10038',
 '10046',
 '10049',
 '10051',
 '10057',
 '10058',
 '10059',
 '10099',
 '10112',
 '10123',
 '10131',
 '10146',
 '10150',
 '10153',
 '10165',
 '1017',
 '10174',
 '10180',
 '1019',
 '10190',
 '102',
 '10206',
 '1021',
 '1022',
 '10221',
 '10227',
 '10237',
 '10245',
 '1026',
 '1027',
 '10270',
 '10273',
 '10276',
 '10285',
 '1029',
 '10298',
 '10318',
 '10320',
 '10329',
 '10362',
 '10398',
 '10434',
 '10450',
 '10451',
 '10489',
 '10491',
 '10493',
 '10494',
 '1050',
 '10513',
 '1052',
 '10523',
 '10525',
 '10557',
 '10559',
 '10589',
 '10606',
 '10610',
 '10617',
 '1062',
 '10641',
 '10644',
 '10652',
 '10668',
 '10670',
 '10681',
 '10682',
 '10695',
 '1070',
 '10730',
 '10732',
 '10765',
 '10775',
 '10776',
 '10782',
 '10797',
 '10810',
 '10813',
 '10818',
 '10845',
 '10857',
 '10892',
 '10898',
 '10904',
 '10915',
 '10921',
 '10953',
 '10954',
 '10962',
 '10969',
 '10972',
 '10973',
 '11000',
 '11004',
 '11007',
 '11011',
 '11014',
 '11031',
 '11041',
 '11044',
 '11065',
 '11072',
 '11073',
 '11098',
 '1111',
 '11137',
 '11142',
 '11151',
 '11157',
 '11168',
 '11182',
 '11188',
 '11200',
 '1123',
 '11230',
 '11232',
 '11261',
 '11284',
 '11319',
 '11325',
 '11344',
 '1153',
 '116832',
 '1212',
 '1213',
 '124583',
 '1277',
 '128',
 '1282',
 '1385',
 '1398',
 '1399',
 '142',
 '1429',
 '1445',
 '1452',
 '1454',
 '1459',
 '1465',
 '147179',
 '148022',
 '1500',
 '1509',
 '1514',
 '1534',
 '154',
 '16',
 '1605',
 '1616',
 '1633',
 '1635',
 '1643',
 '1647',
 '1662',
 '1666',
 '1676',
 '1677',
 '1738',
 '1759',
 '178',
 '1786',
 '1788',
 '1802',
 '1829',
 '1831',
 '1845',
 '1846',
 '1848',
 '1861',
 '1870',
 '1891',
 '1906',
 '1950',
 '1956',
 '1958',
 '1978',
 '1981',
 '1983',
 '1994',
 '200081',
 '200734',
 '2017',
 '2037',
 '2042',
 '2048',
 '2058',
 '2063',
 '2064',
 '2065',
 '207',
 '2109',
 '211',
 '2113',
 '2115',
 '2131',
 '2146',
 '2184',
 '2185',
 '2195',
 '2222',
 '226',
 '2263',
 '2264',
 '2274',
 '22794',
 '22796',
 '22809',
 '22823',
 '22827',
 '22841',
 '2288',
 '22883',
 '22887',
 '22889',
 '22905',
 '22908',
 '22926',
 '22934',
 '23',
 '230',
 '23011',
 '23013',
 '23014',
 '23029',
 '23038',
 '23039',
 '23061',
 '23076',
 '23077',
 '2309',
 '23097',
 '23131',
 '23139',
 '23142',
 '23149',
 '23161',
 '23200',
 '23210',
 '23212',
 '23223',
 '23224',
 '23244',
 '23271',
 '23300',
 '23321',
 '23325',
 '23326',
 '23335',
 '23338',
 '23365',
 '23368',
 '23378',
 '23386',
 '23410',
 '23443',
 '23463',
 '23499',
 '23512',
 '23522',
 '2353',
 '23530',
 '23536',
 '2356',
 '23585',
 '23588',
 '23597',
 '23635',
 '23636',
 '23647',
 '23658',
 '23659',
 '23670',
 '24149',
 '25',
 '2523',
 '2534',
 '2542',
 '2548',
 '2553',
 '256364',
 '25793',
 '25803',
 '25805',
 '2582',
 '25825',
 '25839',
 '25874',
 '25932',
 '25966',
 '2597',
 '25976',
 '25987',
 '26001',
 '26020',
 '26036',
 '26054',
 '26064',
 '26128',
 '26136',
 '26227',
 '2624',
 '2625',
 '26292',
 '26511',
 '26520',
 '2673',
 '2690',
 '26993',
 '27032',
 '27095',
 '27109',
 '27242',
 '27244',
 '27336',
 '27346',
 '2736',
 '2745',
 '2767',
 '2769',
 '2770',
 '2771',
 '2778',
 '2810',
 '2817',
 '2852',
 '2886',
 '2887',
 '2896',
 '28969',
 '2908',
 '29082',
 '29083',
 '291',
 '29103',
 '2920',
 '2946',
 '2954',
 '2956',
 '2958',
 '2961',
 '29763',
 '29890',
 '29911',
 '29916',
 '29928',
 '29937',
 '29978',
 '30',
 '30001',
 '3028',
 '3033',
 '3066',
 '30836',
 '30849',
 '3091',
 '3098',
 '310',
 '3108',
 '3122',
 '3156',
 '3157',
 '3162',
 '3202',
 '3206',
 '323',
 '3251',
 '3280',
 '329',
 '3300',
 '3303',
 '3308',
 '3312',
 '3315',
 '332',
 '3329',
 '3337',
 '3383',
 '3385',
 '3398',
 '3416',
 '3454',
 '348',
 '3480',
 '3482',
 '3486',
 '3508',
 '351',
 '355',
 '3551',
 '3553',
 '3566',
 '3597',
 '3611',
 '3628',
 '3638',
 '3682',
 '3693',
 '3725',
 '375346',
 '3775',
 '3800',
 '3815',
 '387',
 '388650',
 '3895',
 '39',
 '3909',
 '392',
 '3925',
 '3930',
 '3964',
 '3978',
 '3988',
 '4016',
 '4043',
 '4067',
 '4088',
 '4125',
 '4144',
 '4154',
 '4172',
 '4200',
 '4208',
 '4216',
 '4232',
 '427',
 '4282',
 '4303',
 '4312',
 '4313',
 '4331',
 '4482',
 '4582',
 '4605',
 '4609',
 '4616',
 '4638',
 '4651',
 '466',
 '4690',
 '47',
 '4775',
 '4776',
 '4780',
 '4783',
 '4791',
 '4792',
 '4793',
 '4794',
 '481',
 '4817',
 '4836',
 '4846',
 '4850',
 '4851',
 '4860',
 '4864',
 '4891',
 '4893',
 '4925',
 '4927',
 '4931',
 '4998',
 '501',
 '5018',
 '5019',
 '5048',
 '5050',
 '5054',
 '5058',
 '50810',
 '50813',
 '50814',
 '50865',
 '5092',
 '5096',
 '51001',
 '51005',
 '51015',
 '51021',
 '51024',
 '51026',
 '51031',
 '51053',
 '51056',
 '5106',
 '51070',
 '51071',
 '5108',
 '51097',
 '5110',
 '5111',
 '51116',
 '51160',
 '51170',
 '51203',
 '51282',
 '51293',
 '51335',
 '51375',
 '51382',
 '51385',
 '51422',
 '51465',
 '51466',
 '51495',
 '5154',
 '51569',
 '51599',
 '51635',
 '51719',
 '51742',
 '5211',
 '5223',
 '5236',
 '5255',
 '5257',
 '5261',
 '5287',
 '5289',
 '5290',
 '5300',
 '5321',
 '533',
 '5331',
 '53343',
 '5347',
 '5355',
 '5357',
 '5359',
 '5366',
 '5373',
 '54205',
 '5423',
 '5427',
 '5438',
 '54386',
 '5440',
 '54438',
 '54442',
 '54499',
 '54505',
 '54512',
 '54541',
 '54623',
 '5467',
 '5468',
 '54681',
 '54733',
 '5480',
 '54807',
 '54850',
 '54881',
 '54915',
 '54957',
 '5498',
 '55008',
 '55011',
 '55012',
 '55033',
 '55038',
 '55111',
 '55127',
 '55129',
 '55148',
 '55179',
 '5525',
 '55256',
 '5529',
 '55324',
 '5547',
 '55556',
 '55604',
 '55608',
 '55620',
 '5566',
 '55699',
 '55746',
 '55748',
 '55793',
 '5580',
 '55818',
 '55825',
 '5583',
 '55837',
 '55847',
 '5588',
 '55893',
 '55958',
 '5601',
 '5603',
 '5607',
 '5613',
 '5627',
 '5641',
 '5654',
 '56654',
 '56889',
 '56924',
 '56940',
 '5696',
 '5699',
 '56997',
 '57019',
 '57048',
 '5708',
 '5710',
 '57147',
 '57149',
 '5715',
 '5716',
 '57178',
 '57192',
 '572',
 '5720',
 '5721',
 '57215',
 '57406',
 '5743',
 '5747',
 '5770',
 '57761',
 '5777',
 '57804',
 '5782',
 '5788',
 '5792',
 '5796',
 '581',
 '5827',
 '5829',
 '5831',
 '5836',
 '58472',
 '58478',
 '58497',
 '58533',
 '5867',
 '5873',
 '5880',
 '5883',
 '5889',
 '5891',
 '5898',
 '5899',
 '5900',
 '5909',
 '5921',
 '5925',
 '5927',
 '595',
 '596',
 '5971',
 '5982',
 '5985',
 '5986',
 '5993',
 '5997',
 '6009',
 '60493',
 '6050',
 '60528',
 '6117',
 '6118',
 '6119',
 '6182',
 '6184',
 '6193',
 '6194',
 '6195',
 '622',
 '6251',
 '6253',
 '6275',
 '6284',
 '6304',
 '6342',
 '6347',
 '637',
 '63874',
 '6390',
 '63933',
 '64080',
 '642',
 '644',
 '64422',
 '64428',
 '64429',
 '6443',
 '6461',
 '6464',
 '64746',
 '64781',
 '64943',
 '6499',
 '6500',
 '65057',
 '6509',
 '65123',
 '652',
 '6597',
 '6599',
 '66008',
 '6603',
 '6616',
 '6622',
 '664',
 '665',
 '6657',
 '6659',
 '6676',
 '6696',
 '6697',
 '670',
 '6709',
 '6714',
 '672',
 '6772',
 '6774',
 '6777',
 '6790',
 '6793',
 '6804',
 '6810',
 '6812',
 '6813',
 '6832',
 '6839',
 '6850',
 '6856',
 '6894',
 '6908',
 '6909',
 '6915',
 '6919',
 '6944',
 '695',
 '6988',
 '6990',
 '701',
 '7015',
 '7016',
 '7020',
 '7027',
 '7043',
 '7048',
 '7074',
 '7077',
 '7082',
 '7088',
 '7099',
 '7105',
 '7106',
 '7153',
 '7157',
 '7158',
 '7159',
 '7165',
 '7168',
 '7264',
 '727',
 '7296',
 '7319',
 '7358',
 '7376',
 '7398',
 '7416',
 '7466',
 '7485',
 '7494',
 '7511',
 '7538',
 '7690',
 '7750',
 '780',
 '7849',
 '7852',
 '7866',
 '7867',
 '7874',
 '79006',
 '7905',
 '79071',
 '79073',
 '79080',
 '79090',
 '79094',
 '79143',
 '79170',
 '79174',
 '79187',
 '79600',
 '79643',
 '79716',
 '7982',
 '79850',
 '79902',
 '79921',
 '7994',
 '79947',
 '79961',
 '80204',
 '80212',
 '80347',
 '80349',
 '8050',
 '8061',
 '80746',
 '80758',
 '808',
 '8091',
 '813',
 '81533',
 '81544',
 '8202',
 '8204',
 '823',
 '8243',
 '8270',
 '831',
 '8312',
 '8318',
 '8321',
 '8324',
 '8349',
 '835',
 '836',
 '83743',
 '8396',
 '840',
 '84159',
 '843',
 '8440',
 '8444',
 '8446',
 '84617',
 '847',
 '84722',
 '8480',
 '84890',
 '8503',
 '8508',
 '8518',
 '8520',
 '85236',
 '85377',
 '8550',
 '8553',
 '8569',
 '8573',
 '8574',
 '8607',
 '8624',
 '8678',
 '868',
 '8720',
 '8726',
 '8727',
 '873',
 '8731',
 '874',
 '8800',
 '8804',
 '8821',
 '8826',
 '8835',
 '8837',
 '8851',
 '8869',
 '8870',
 '8878',
 '8884',
 '8895',
 '890',
 '8900',
 '891',
 '8914',
 '896',
 '8974',
 '8985',
 '899',
 '89910',
 '8996',
 '9016',
 '9019',
 '902',
 '9053',
 '90861',
 '9093',
 '9097',
 '9112',
 '91137',
 '9124',
 '9126',
 '9128',
 '9133',
 '9134',
 '9143',
 '9170',
 '9181',
 '9183',
 '91949',
 '9212',
 '9217',
 '9221',
 '9246',
 '9261',
 '9267',
 '9270',
 '9275',
 '9276',
 '9289',
 '93487',
 '93594',
 '9375',
 '94239',
 '9448',
 '9455',
 '9467',
 '9488',
 '949',
 '9491',
 '9517',
 '9519',
 '9531',
 '9533',
 '9552',
 '958',
 '960',
 '9637',
 '9641',
 '965',
 '9650',
 '9653',
 '9670',
 '9686',
 '9688',
 '9690',
 '9695',
 '9697',
 '9702',
 '9703',
 '9709',
 '9710',
 '9712',
 '9738',
 '976',
 '9761',
 '9797',
 '9801',
 '9805',
 '9813',
 '9817',
 '983',
 '9833',
 '9842',
 '9847',
 '9851',
 '9854',
 '9868',
 '9897',
 '9903',
 '991',
 '9915',
 '9917',
 '9918',
 '9924',
 '9926',
 '9928',
 '993',
 '994',
 '9943',
 '9961',
 '998',
 '9988'}

In [14]:
id_to_col = {}

for col in df.columns:
    id = col.split()[-1][1:-1]
    id_to_col[id] = col

id_to_col

{'': 'Unnamed: 0',
 '7105': 'TSPAN6 (7105)',
 '64102': 'TNMD (64102)',
 '8813': 'DPM1 (8813)',
 '57147': 'SCYL3 (57147)',
 '55732': 'C1orf112 (55732)',
 '2268': 'FGR (2268)',
 '3075': 'CFH (3075)',
 '2519': 'FUCA2 (2519)',
 '2729': 'GCLC (2729)',
 '4800': 'NFYA (4800)',
 '90529': 'STPG1 (90529)',
 '57185': 'NIPAL3 (57185)',
 '81887': 'LAS1L (81887)',
 '22875': 'ENPP4 (22875)',
 '6405': 'SEMA3F (6405)',
 '1080': 'CFTR (1080)',
 '54467': 'ANKIB1 (54467)',
 '1595': 'CYP51A1 (1595)',
 '889': 'KRIT1 (889)',
 '5893': 'RAD52 (5893)',
 '572': 'BAD (572)',
 '51056': 'LAP3 (51056)',
 '4267': 'CD99 (4267)',
 '9957': 'HS3ST1 (9957)',
 '26': 'AOC1 (26)',
 '51384': 'WNT16 (51384)',
 '23072': 'HECW1 (23072)',
 '8379': 'MAD1L1 (8379)',
 '3927': 'LASP1 (3927)',
 '29916': 'SNX11 (29916)',
 '55365': 'TMEM176A (55365)',
 '4074': 'M6PR (4074)',
 '90293': 'KLHL13 (90293)',
 '56603': 'CYP26B1 (56603)',
 '3382': 'ICA1 (3382)',
 '79007': 'DBNDD1 (79007)',
 '57679': 'ALS2 (57679)',
 '843': 'CASP10 (843)',
 '8837': 'CFLAR (8837)',
 '7035': 'TFPI (7035)',
 '55471': 'NDUFAF7 (55471)',
 '10181': 'RBM5 (10181)',
 '9108': 'MTMR7 (9108)',
 '6542': 'SLC7A2 (6542)',
 '381': 'ARF5 (381)',
 '23098': 'SARM1 (23098)',
 '26073': 'POLDIP2 (26073)',
 '23129': 'PLXND1 (23129)',
 '204': 'AK2 (204)',
 '952': 'CD38 (952)',
 '2288': 'FKBP4 (2288)',
 '23028': 'KDM1A (23028)',
 '10180': 'RBM6 (10180)',
 '84254': 'CAMKK1 (84254)',
 '5965': 'RECQL (5965)',
 '55610': 'VPS50 (55610)',
 '126393': 'HSPB6 (126393)',
 '115703': 'ARHGAP33 (115703)',
 '4706': 'NDUFAB1 (4706)',
 '5166': 'PDK4 (5166)',
 '85413': 'SLC22A16 (85413)',
 '51364': 'ZMYND10 (51364)',
 '340273': 'ABCB5 (340273)',
 '170302': 'ARX (170302)',
 '10165': 'SLC25A13 (10165)',
 '7982': 'ST7 (7982)',
 '996': 'CDC27 (996)',
 '6521': 'SLC4A1 (6521)',
 '799': 'CALCR (799)',
 '3052': 'HCCS (3052)',
 '1856': 'DVL2 (1856)',
 '64063': 'PRSS22 (64063)',
 '5976': 'UPF1 (5976)',
 '8935': 'SKAP2 (8935)',
 '292': 'SLC25A5 (292)',
 '55013': 'MCUB (55013)',
 '3207': 'HOXA11 (3207)',
 '5439': 'POLR2J (5439)',
 '56919': 'DHX33 (56919)',
 '4222': 'MEOX1 (4222)',
 '221981': 'THSD7A (221981)',
 '3980': 'LIG3 (3980)',
 '79657': 'RPAP3 (79657)',
 '6296': 'ACSM3 (6296)',
 '81691': 'REXO5 (81691)',
 '57019': 'CIAPIN1 (57019)',
 '56928': 'SPPL2B (56928)',
 '80256': 'FAM214B (80256)',
 '51226': 'COPZ2 (51226)',
 '5577': 'PRKAR2B (5577)',
 '10943': 'MSL3 (10943)',
 '1387': 'CREBBP (1387)',
 '9256': 'TSPOAP1 (9256)',
 '4353': 'MPO (4353)',
 '5444': 'PON1 (5444)',
 '6936': 'GCFC2 (6936)',
 '84058': 'WDR54 (84058)',
 '54677': 'CROT (54677)',
 '5244': 'ABCB4 (5244)',
 '55904': 'KMT2E (55904)',
 '57414': 'RHBDD2 (57414)',
 '30812': 'SOX8 (30812)',
 '25998': 'IBTK (25998)',
 '7748': 'ZNF195 (7748)',
 '23077': 'MYCBP2 (23077)',
 '26224': 'FBXL3 (26224)',
 '3683': 'ITGAL (3683)',
 '5164': 'PDK2 (5164)',
 '3675': 'ITGA3 (3675)',
 '7543': 'ZFX (7543)',
 '3920': 'LAMP2 (3920)',
 '3674': 'ITGA2B (3674)',
 '51666': 'ASB4 (51666)',
 '51573': 'GDE1 (51573)',
 '55049': 'REX1BD (55049)',
 '9244': 'CRLF1 (9244)',
 '114881': 'OSBPL7 (114881)',
 '26022': 'TMEM98 (26022)',
 '51087': 'YBX2 (51087)',
 '3883': 'KRT33A (3883)',
 '9020': 'MAP3K14 (9020)',
 '6833': 'ABCC8 (6833)',
 '10368': 'CACNG3 (10368)',
 '54972': 'TMEM132A (54972)',
 '163': 'AP2B1 (163)',
 '6863': 'TAC1 (6863)',
 '10127': 'ZNF263 (10127)',
 '6376': 'CX3CL1 (6376)',
 '64847': 'SPATA20 (64847)',
 '8913': 'CACNA1G (8913)',
 '51330': 'TNFRSF12A (51330)',
 '1750': 'DLX6 (1750)',
 '4293': 'MAP3K9 (4293)',
 '5898': 'RALA (5898)',
 '55971': 'BAIAP2L1 (55971)',
 '80853': 'KDM7A (80853)',
 '2115': 'ETV1 (2115)',
 '55750': 'AGK (55750)',
 '221': 'ALDH3B1 (221)',
 '55001': 'TTC22 (55001)',
 '57157': 'PHTF2 (57157)',
 '10344': 'CCL26 (10344)',
 '9855': 'FARP2 (9855)',
 '10083': 'USH1C (10083)',
 '79017': 'GGCT (79017)',
 '10926': 'DBF4 (10926)',
 '6915': 'TBXA2R (6915)',
 '3475': 'IFRD1 (3475)',
 '56891': 'LGALS14 (56891)',
 '1352': 'COX10 (1352)',
 '9569': 'GTF2IRD1 (9569)',
 '54623': 'PAF1 (54623)',
 '27072': 'VPS41 (27072)',
 '9912': 'ARHGAP44 (9912)',
 '60528': 'ELAC2 (60528)',
 '85477': 'SCIN (85477)',
 '414': 'ARSD (414)',
 '8228': 'PNPLA4 (8228)',
 '8735': 'MYH13 (8735)',
 '79602': 'ADIPOR2 (79602)',
 '51265': 'CDKL3 (51265)',
 '151531': 'UPP2 (151531)',
 '10942': 'PRSS21 (10942)',
 '57787': 'MARK4 (57787)',
 '8842': 'PROM1 (8842)',
 '115098': 'CCDC124 (115098)',
 '90273': 'CEACAM21 (90273)',
 '5048': 'PAFAH1B1 (5048)',
 '4843': 'NOS2 (4843)',
 '1770': 'DNAH9 (1770)',
 '9703': 'KIAA0100 (9703)',
 '9058': 'SLC13A2 (9058)',
 '8522': 'GAS7 (8522)',
 '79090': 'TRAPPC6A (79090)',
 '4145': 'MATK (4145)',
 '1087': 'CEACAM7 (1087)',
 '974': 'CD79B (974)',
 '6329': 'SCN4A (6329)',
 '54879': 'ST7L (54879)',
 '8277': 'TKTL1 (8277)',
 '5080': 'PAX6 (5080)',
 '113000': 'RPUSD1 (113000)',
 '64285': 'RHBDF1 (64285)',
 '55692': 'LUC7L (55692)',
 '9254': 'CACNA2D2 (9254)',
 '8938': 'BAIAP3 (8938)',
 '115939': 'TSR3 (115939)',
 '9091': 'PIGQ (9091)',
 '57585': 'CRAMP1 (57585)',
 '7005': 'TEAD3 (7005)',
 '6401': 'SELE (6401)',
 '55735': 'DNAJC11 (55735)',
 '2328': 'FMO3 (2328)',
 '29116': 'MYLIP (29116)',
 '27035': 'NOX1 (27035)',
 '1870': 'E2F2 (1870)',
 '5689': 'PSMB1 (5689)',
 '6853': 'SYN1 (6853)',
 '3720': 'JARID2 (3720)',
 '6792': 'CDKL5 (6792)',
 '57172': 'CAMK1G (57172)',
 '728642': 'CDK11A (728642)',
 '65220': 'NADK (65220)',
 '7021': 'TFAP2B (7021)',
 '83741': 'TFAP2D (83741)',
 '9940': 'DLEC1 (9940)',
 '9265': 'CYTH3 (9265)',
 '53616': 'ADAM22 (53616)',
 '6856': 'SYPL1 (6856)',
 '1534': 'CYB561 (1534)',
 '9043': 'SPAG9 (9043)',
 '1951': 'CELSR3 (1951)',
 '10157': 'AASS (10157)',
 '55200': 'PLEKHG6 (55200)',
 '51188': 'SS18L2 (51188)',
 '84954': 'MPND (84954)',
 '4257': 'MGST1 (4257)',
 '1407': 'CRY1 (1407)',
 '8993': 'PGLYRP1 (8993)',
 '4784': 'NFIX (4784)',
 '6482': 'ST3GAL1 (6482)',
 '64386': 'MMP25 (64386)',
 '9235': 'IL32 (9235)',
 '5310': 'PKD1 (5310)',
 '23542': 'MAPK8IP2 (23542)',
 '9862': 'MED24 (9862)',
 '23221': 'RHOBTB2 (23221)',
 '54497': 'HEATR5B (54497)',
 '7095': 'SEC62 (7095)',
 '6224': 'RPS20 (6224)',
 '7812': 'CSDE1 (7812)',
 '9690': 'UBE3C (9690)',
 '5980': 'REV3L (5980)',
 '10178': 'TENM1 (10178)',
 '5081': 'PAX7 (5081)',
 '10747': 'MASP2 (10747)',
 '389434': 'IYD (389434)',
 '199870': 'FAM76A (199870)',
 '80342': 'TRAF3IP3 (80342)',
 '29954': 'POMT2 (29954)',
 '51534': 'VTA1 (51534)',
 '51085': 'MLXIPL (51085)',
 '9031': 'BAZ1B (9031)',
 '10048': 'RANBP9 (10048)',
 '51513': 'ETV7 (51513)',
 '83932': 'SPRTN (83932)',
 '51603': 'EEF1AKNMT (51603)',
 '8798': 'DYRK4 (8798)',
 '7756': 'ZNF207 (7756)',
 '7384': 'UQCRC1 (7384)',
 '83930': 'STARD3NL (83930)',
 '928': 'CD9 (928)',
 '57467': 'HHATL (57467)',
 '9918': 'NCAPD2 (9918)',
 '25900': 'IFFO1 (25900)',
 '2696': 'GIPR (2696)',
 '51533': 'PHF7 (51533)',
 '56920': 'SEMA3G (56920)',
 '11188': 'NISCH (11188)',
 '23166': 'STAB1 (23166)',
 '80199': 'FUZ (80199)',
 '6540': 'SLC6A13 (6540)',
 '3423': 'IDS (3423)',
 '5646': 'PRSS3 (5646)',
 '7752': 'ZNF200 (7752)',
 '920': 'CD4 (920)',
 '10233': 'LRRC23 (10233)',
 '695': 'BTK (695)',
 '3077': 'HFE (3077)',
 '22955': 'SCMH1 (22955)',
 '2534': 'FYN (2534)',
 '3097': 'HIVEP2 (3097)',
 '2326': 'FMO1 (2326)',
 '6924': 'ELOA (6924)',
 '11313': 'LYPLA2 (11313)',
 '1185': 'CLCN6 (1185)',
 '9902': 'MRC2 (9902)',
 '654364': 'NME1-NME2 (654364)',
 '6534': 'SLC6A7 (6534)',
 '10867': 'TSPAN9 (10867)',
 '55727': 'BTBD7 (55727)',
 '9546': 'APBA3 (9546)',
 '54903': 'MKS1 (54903)',
 '51099': 'ABHD5 (51099)',
 '3730': 'ANOS1 (3730)',
 '26993': 'AKAP8L (26993)',
 '54799': 'MBTD1 (54799)',
 '51096': 'UTP18 (51096)',
 '54476': 'RNF216 (54476)',
 '54902': 'TTC19 (54902)',
 '5725': 'PTBP1 (5725)',
 '8193': 'DPF1 (8193)',
 '9066': 'SYT7 (9066)',
 '23395': 'LARS2 (23395)',
 '5286': 'PIK3C2A (5286)',
 '5329': 'PLAUR (5329)',
 '54443': 'ANLN (54443)',
 '58525': 'WIZ (58525)',
 '23637': 'RABGAP1 (23637)',
 '1634': 'DCN (1634)',
 '54814': 'QPCTL (54814)',
 '5536': 'PPP5C (5536)',
 '23177': 'CEP68 (23177)',
 '8491': 'MAP4K3 (8491)',
 '27033': 'ZBTB32 (27033)',
 '7305': 'TYROBP (7305)',
 '57146': 'TMEM159 (57146)',
 '2556': 'GABRA3 (2556)',
 '672': 'BRCA1 (672)',
 '2067': 'ERCC1 (2067)',
 '933': 'CD22 (933)',
 '7869': 'SEMA3B (7869)',
 '51360': 'MBTPS2 (51360)',
 '4007': 'PRICKLE3 (4007)',
 '4057': 'LTF (4057)',
 '2137': 'EXTL3 (2137)',
 '9971': 'NR1H4 (9971)',
 '60481': 'ELOVL5 (60481)',
 '240': 'ALOX5 (240)',
 '8284': 'KDM5D (8284)',
 '57658': 'CALCOCO1 (57658)',
 '55148': 'UBR7 (55148)',
 '11183': 'MAP4K5 (11183)',
 '30845': 'EHD3 (30845)',
 '5704': 'PSMC4 (5704)',
 '23324': 'MAN2B2 (23324)',
 '57709': 'SLC7A14 (57709)',
 '5010': 'CLDN11 (5010)',
 '51629': 'SLC25A39 (51629)',
 '9961': 'MVP (9961)',
 '51667': 'NUB1 (51667)',
 '5238': 'PGM3 (5238)',
 '112611': 'RWDD2A (112611)',
 '1195': 'CLK1 (1195)',
 '55703': 'POLR3B (55703)',
 '23357': 'ANGEL1 (23357)',
 '9604': 'RNF14 (9604)',
 '1774': 'DNASE1L1 (1774)',
 '1663': 'DDX11 (1663)',
 '50865': 'HEBP1 (50865)',
 '9052': 'GPRC5A (9052)',
 '10046': 'MAMLD1 (10046)',
 '923': 'CD6 (923)',
 '10460': 'TACC3 (10460)',
 '23376': 'UFL1 (23376)',
 '23649': 'POLA2 (23649)',
 '23144': 'ZC3H3 (23144)',
 '823': 'CAPN1 (823)',
 '55': 'ACP3 (55)',
 '4190': 'MDH1 (4190)',
 '10463': 'SLC30A9 (10463)',
 '10903': 'MTMR11 (10903)',
 '1355': 'COX15 (1355)',
 '440193': 'CCDC88C (440193)',
 '10138': 'YAF2 (10138)',
 '10771': 'ZMYND11 (10771)',
 '7454': 'WAS (7454)',
 '1800': 'DPEP1 (1800)',
 '637': 'BID (637)',
 '9782': 'MATR3 (9782)',
 '29881': 'NPC1L1 (29881)',
 '64132': 'XYLT2 (64132)',
 '84220': 'RGPD5 (84220)',
 '81551': 'STMN4 (81551)',
 '23386': 'NUDCD3 (23386)',
 '3670': 'ISL1 (3670)',
 '55349': 'CHDH (55349)',
 '53832': 'IL20RA (53832)',
 '1179': 'CLCA1 (1179)',
 '22802': 'CLCA4 (22802)',
 '55830': 'GLT8D1 (55830)',
 '27032': 'ATP2C1 (27032)',
 '3479': 'IGF1 (3479)',
 '92745': 'SLC38A5 (92745)',
 '10928': 'RALBP1 (10928)',
 '22902': 'RUFY3 (22902)',
 '1272': 'CNTN1 (1272)',
 '6556': 'SLC11A1 (6556)',
 '25937': 'WWTR1 (25937)',
 '8540': 'AGPS (8540)',
 '63932': 'CXorf56 (63932)',
 '477': 'ATP1A2 (477)',
 '55622': 'TTC27 (55622)',
 '147948': 'ZNF582 (147948)',
 '23584': 'VSIG2 (23584)',
 '23187': 'PHLDB1 (23187)',
 '8685': 'MARCO (8685)',
 '1591': 'CYP24A1 (1591)',
 '56981': 'PRDM11 (56981)',
 '57586': 'SYT13 (57586)',
 '6591': 'SNAI2 (6591)',
 '972': 'CD74 (972)',
 '3082': 'HGF (3082)',
 '54764': 'ZRANB1 (54764)',
 '23154': 'NCDN (23154)',
 '25960': 'ADGRA2 (25960)',
 '55734': 'ZFP64 (55734)',
 '4331': 'MNAT1 (4331)',
 '23034': 'SAMD4A (23034)',
 '864': 'RUNX3 (864)',
 '4361': 'MRE11 (4361)',
 '58473': 'PLEKHB1 (58473)',
 '1992': 'SERPINB1 (1992)',
 '64816': 'CYP3A43 (64816)',
 '11136': 'SLC7A9 (11136)',
 '6683': 'SPAST (6683)',
 '9369': 'NRXN3 (9369)',
 '114879': 'OSBPL5 (114879)',
 '9716': 'AQR (9716)',
 '1373': 'CPS1 (1373)',
 '732': 'C8B (732)',
 '2273': 'FHL1 (2273)',
 '51507': 'RTF2 (51507)',
 '2554': 'GABRA1 (2554)',
 '55655': 'NLRP2 (55655)',
 '57210': 'SLC45A4 (57210)',
 '9921': 'RNF10 (9921)',
 '55778': 'ZNF839 (55778)',
 '64429': 'ZDHHC6 (64429)',
 '57476': 'GRAMD1B (57476)',
 '6050': 'RNH1 (6050)',
 '4719': 'NDUFS1 (4719)',
 '9821': 'RB1CC1 (9821)',
 '23071': 'ERP44 (23071)',
 '211': 'ALAS1 (211)',
 '330': 'BIRC3 (330)',
 '11215': 'AKAP11 (11215)',
 '51022': 'GLRX2 (51022)',
 '6617': 'SNAPC1 (6617)',
 '51071': 'DERA (51071)',
 '11171': 'STRAP (11171)',
 '1244': 'ABCC2 (1244)',
 '50619': 'DEF6 (50619)',
 '51177': 'PLEKHO1 (51177)',
 '2730': 'GCLM (2730)',
 '23304': 'UBR2 (23304)',
 '30846': 'EHD2 (30846)',
 '55635': 'DEPDC1 (55635)',
 '25901': 'CCDC28A (25901)',
 '58528': 'RRAGD (58528)',
 '3298': 'HSF2 (3298)',
 '51230': 'PHF20 (51230)',
 '8630': 'HSD17B6 (8630)',
 '10062': 'NR1H3 (10062)',
 '1890': 'TYMP (1890)',
 '29781': 'NCAPH2 (29781)',
 '10953': 'TOMM34 (10953)',
 '11231': 'SEC63 (11231)',
 '23633': 'KPNA6 (23633)',
 '7431': 'VIM (7431)',
 '355': 'FAS (355)',
 '8635': 'RNASET2 (8635)',
 '960': 'CD44 (960)',
 '3755': 'KCNG1 (3755)',
 '56895': 'AGPAT4 (56895)',
 '57823': 'SLAMF7 (57823)',
 '11119': 'BTN3A1 (11119)',
 '4285': 'MIPEP (4285)',
 '5583': 'PRKCH (5583)',
 '3645': 'INSRR (3645)',
 '3459': 'IFNGR1 (3459)',
 '11285': 'B4GALT7 (11285)',
 '9047': 'SH2D2A (9047)',
 '7444': 'VRK2 (7444)',
 '7133': 'TNFRSF1B (7133)',
 '55591': 'VEZT (55591)',
 '5452': 'POU2F2 (5452)',
 '65980': 'BRD9 (65980)',
 '6642': 'SNX1 (6642)',
 '9519': 'TBPL1 (9519)',
 '56938': 'ARNTL2 (56938)',
 '9774': 'BCLAF1 (9774)',
 '55334': 'SLC39A9 (55334)',
 '286': 'ANK1 (286)',
 '3381': 'IBSP (3381)',
 '51106': 'TFB1M (51106)',
 '9135': 'RABEP1 (9135)',
 '3149': 'HMGB3 (3149)',
 '23279': 'NUP160 (23279)',
 '578': 'BAK1 (578)',
 '4593': 'MUSK (4593)',
 '22807': 'IKZF2 (22807)',
 '2896': 'GRN (2896)',
 '51306': 'FAM13B (51306)',
 '57514': 'ARHGAP31 (57514)',
 '55166': 'CENPQ (55166)',
 '6301': 'SARS1 (6301)',
 '8498': 'RANBP3 (8498)',
 '5926': 'ARID4A (5926)',
 '7260': 'EIPR1 (7260)',
 '10908': 'PNPLA6 (10908)',
 '8100': 'IFT88 (8100)',
 '56052': 'ALG1 (56052)',
 '55596': 'ZCCHC8 (55596)',
 '10061': 'ABCF2 (10061)',
 '54480': 'CHPF2 (54480)',
 '57554': 'LRRC7 (57554)',
 '2530': 'FUT8 (2530)',
 '55236': 'UBA6 (55236)',
 '9846': 'GAB2 (9846)',
 '535': 'ATP6V0A1 (535)',
 '8554': 'PIAS1 (8554)',
 '9497': 'SLC4A7 (9497)',
 '321': 'APBA2 (321)',
 '5606': 'MAP2K3 (5606)',
 '79645': 'EFCAB1 (79645)',
 '9168': 'TMSB10 (9168)',
 '28990': 'ASTE1 (28990)',
 '25897': 'RNF19A (25897)',
 '8504': 'PEX3 (8504)',
 '11345': 'GABARAPL2 (11345)',
 '4653': 'MYOC (4653)',
 '26751': 'SH3YL1 (26751)',
 '84908': 'FAM136A (84908)',
 '7414': 'VCL (7414)',
 '55789': 'DEPDC1B (55789)',
 '23604': 'DAPK2 (23604)',
 '8439': 'NSMAF (8439)',
 '159': 'ADSS2 (159)',
 '26228': 'STAP1 (26228)',
 '7077': 'TIMP2 (7077)',
 '5981': 'RFC1 (5981)',
 '55773': 'TBC1D23 (55773)',
 '8452': 'CUL3 (8452)',
 '9172': 'MYOM2 (9172)',
 '5009': 'OTC (5009)',
 '10858': 'CYP46A1 (10858)',
 '26009': 'ZZZ3 (26009)',
 '6570': 'SLC18A1 (6570)',
 '9099': 'USP2 (9099)',
 '846': 'CASR (846)',
 '27175': 'TUBG2 (27175)',
 '51121': 'RPL26L1 (51121)',
 '2324': 'FLT4 (2324)',
 '54888': 'NSUN2 (54888)',
 '54455': 'FBXO42 (54455)',
 '4238': 'MFAP3 (4238)',
 '84245': 'MRI1 (84245)',
 '4234': 'METTL1 (4234)',
 '3224': 'HOXC8 (3224)',
 '175': 'AGA (175)',
 '55300': 'PI4K2B (55300)',
 '259282': 'BOD1L1 (259282)',
 '27430': 'MAT2B (27430)',
 '7092': 'TLL1 (7092)',
 '23644': 'EDC4 (23644)',
 '7204': 'TRIO (7204)',
 '1462': 'VCAN (1462)',
 '23274': 'CLEC16A (23274)',
 '4481': 'MSR1 (4481)',
 '999': 'CDH1 (999)',
 '23517': 'MTREX (23517)',
 '1767': 'DNAH5 (1767)',
 '9765': 'ZFYVE16 (9765)',
 '79567': 'RIPOR1 (79567)',
 '729': 'C6 (729)',
 '26064': 'RAI14 (26064)',
 '11063': 'SOX30 (11063)',
 '11284': 'PNKP (11284)',
 '54831': 'BEST2 (54831)',
 '23035': 'PHLPP2 (23035)',
 '54908': 'SPDL1 (54908)',
 '27067': 'STAU2 (27067)',
 '54896': 'SLC66A1 (54896)',
 '1497': 'CTNS (1497)',
 '65078': 'RTN4R (65078)',
 '79142': 'PHF23 (79142)',
 '1008': 'CDH10 (1008)',
 '3631': 'INPP4A (3631)',
 '5874': 'RAB27B (5874)',
 '5685': 'PSMA4 (5685)',
 '23026': 'MYO16 (23026)',
 '55341': 'LSG1 (55341)',
 '10039': 'PARP3 (10039)',
 '3371': 'TNC (3371)',
 '90326': 'THAP3 (90326)',
 '140876': 'RIPOR3 (140876)',
 '55775': 'TDP1 (55775)',
 '84883': 'AIFM2 (84883)',
 '56918': 'C2orf83 (56918)',
 '55812': 'SPATA7 (55812)',
 '9440': 'MED17 (9440)',
 '54884': 'RETSAT (54884)',
 '822': 'CAPG (822)',
 '1175': 'AP2S1 (1175)',
 '7399': 'USH2A (7399)',
 '11055': 'ZPBP (11055)',
 '7038': 'TG (7038)',
 '10863': 'ADAM28 (10863)',
 '8538': 'BARX2 (8538)',
 '54165': 'DCUN1D1 (54165)',
 '23338': 'JADE2 (23338)',
 '7546': 'ZIC2 (7546)',
 '3937': 'LCP2 (3937)',
 '54802': 'TRIT1 (54802)',
 '153': 'ADRB1 (153)',
 '2981': 'GUCA2B (2981)',
 '9820': 'CUL7 (9820)',
 '1495': 'CTNNA1 (1495)',
 '5256': 'PHKA2 (5256)',
 '54875': 'CNTLN (54875)',
 '2042': 'EPHA3 (2042)',
 '3309': 'HSPA5 (3309)',
 '1829': 'DSG2 (1829)',
 '54960': 'GEMIN8 (54960)',
 '8481': 'OFD1 (8481)',
 '2824': 'GPM6B (2824)',
 '51438': 'MAGEC2 (51438)',
 '80243': 'PREX2 (80243)',
 '22884': 'WDR37 (22884)',
 '64848': 'YTHDC2 (64848)',
 '56474': 'CTPS2 (56474)',
 '51606': 'ATP6V1H (51606)',
 '5431': 'POLR2B (5431)',
 '56204': 'FAM214A (56204)',
 '116984': 'ARAP2 (116984)',
 '7175': 'TPR (7175)',
 '1356': 'CP (1356)',
 '23247': 'KATNIP (23247)',
 '84062': 'DTNBP1 (84062)',
 '7504': 'XK (7504)',
 '57101': 'ANO2 (57101)',
 '57102': 'C12orf4 (57102)',
 '6322': 'SCML1 (6322)',
 '55841': 'WWC3 (55841)',
 '395': 'ARHGAP6 (395)',
 '27146': 'FAM184B (27146)',
 '4134': 'MAP4 (4134)',
 '57120': 'GOPC (57120)',
 '6098': 'ROS1 (6098)',
 '57646': 'USP28 (57646)',
 '9734': 'HDAC9 (9734)',
 '26262': 'TSPAN17 (26262)',
 '51491': 'NOP16 (51491)',
 '57545': 'CC2D2A (57545)',
 '50484': 'RRM2B (50484)',
 '168850': 'ZNF800 (168850)',
 '608': 'TNFRSF17 (608)',
 '92017': 'SNX29 (92017)',
 '55885': 'LMO3 (55885)',
 '55173': 'MRPS10 (55173)',
 '2978': 'GUCA1A (2978)',
 '51773': 'RSF1 (51773)',
 '55187': 'VPS13D (55187)',
 '10659': 'CELF2 (10659)',
 '23196': 'FAM120A (23196)',
 '23518': 'R3HDM1 (23518)',
 '1298': 'COL9A2 (1298)',
 '4254': 'KITLG (4254)',
 '1161': 'ERCC8 (1161)',
 '11174': 'ADAMTS6 (11174)',
 '9563': 'H6PD (9563)',
 '9341': 'VAMP3 (9341)',
 '8863': 'PER3 (8863)',
 '10911': 'UTS2 (10911)',
 '3604': 'TNFRSF9 (3604)',
 '55040': 'EPN3 (55040)',
 '4052': 'LTBP1 (4052)',
 '5954': 'RCN1 (5954)',
 '2006': 'ELN (2006)',
 '5982': 'RFC2 (5982)',
 '57492': 'ARID1B (57492)',
 '81037': 'CLPTM1L (81037)',
 '23327': 'NEDD4L (23327)',
 '50943': 'FOXP3 (50943)',
 '89801': 'PPP1R3F (89801)',
 '3074': 'HEXB (3074)',
 '79810': 'PTCD2 (79810)',
 '340533': 'NEXMIF (340533)',
 '51528': 'JKAMP (51528)',
 '27122': 'DKK3 (27122)',
 '7984': 'ARHGEF5 (7984)',
 '9603': 'NFE2L3 (9603)',
 '63933': 'MCUR1 (63933)',
 '51474': 'LIMA1 (51474)',
 '25875': 'LETMD1 (25875)',
 '9498': 'SLC4A8 (9498)',
 '10319': 'LAMC3 (10319)',
 '5733': 'PTGER3 (5733)',
 '79931': 'TNIP3 (79931)',
 '5601': 'MAPK9 (5601)',
 '91522': 'COL23A1 (91522)',
 '9564': 'BCAR1 (9564)',
 '84067': 'FAM160A2 (84067)',
 '9709': 'HERPUD1 (9709)',
 '9454': 'HOMER3 (9454)',
 '5888': 'RAD51 (5888)',
 '10721': 'POLQ (10721)',
 '5291': 'PIK3CB (5291)',
 '1535': 'CYBA (1535)',
 '84321': 'THOC3 (84321)',
 '23593': 'HEBP2 (23593)',
 '10198': 'MPHOSPH9 (10198)',
 '54477': 'PLEKHA5 (54477)',
 '5652': 'PRSS8 (5652)',
 '80143': 'SIKE1 (80143)',
 '23223': 'RRP12 (23223)',
 '57600': 'FNIP2 (57600)',
 '6307': 'MSMO1 (6307)',
 '55761': 'TTC17 (55761)',
 '60529': 'ALX4 (60529)',
 '23105': 'FSTL4 (23105)',
 '1112': 'FOXN3 (1112)',
 '728464': 'METTL24 (728464)',
 '8574': 'AKR7A2 (8574)',
 '51154': 'MRTO4 (51154)',
 '4826': 'NNAT (4826)',
 '55850': 'USE1 (55850)',
 '23101': 'MCF2L2 (23101)',
 '83714': 'NRIP2 (83714)',
 '3909': 'LAMA3 (3909)',
 '55745': 'AP5M1 (55745)',
 '29945': 'ANAPC4 (29945)',
 '3784': 'KCNQ1 (3784)',
 '27095': 'TRAPPC3 (27095)',
 '9967': 'THRAP3 (9967)',
 '29085': 'PHPT1 (29085)',
 '954': 'ENTPD2 (954)',
 '4065': 'LY75 (4065)',
 '51742': 'ARID4B (51742)',
 '23596': 'OPN3 (23596)',
 '10806': 'SDCCAG8 (10806)',
 '5798': 'PTPRN (5798)',
 '55733': 'HHAT (55733)',
 '23095': 'KIF1B (23095)',
 '2296': 'FOXC1 (2296)',
 '25771': 'TBC1D22A (25771)',
 '23224': 'SYNE2 (23224)',
 '57475': 'PLEKHH1 (57475)',
 '10079': 'ATP9A (10079)',
 '23626': 'SPO11 (23626)',
 '140689': 'CBLN4 (140689)',
 '25884': 'CHRDL2 (25884)',
 '23201': 'FAM168A (23201)',
 '84957': 'RELT (84957)',
 '2581': 'GALC (2581)',
 '51602': 'NOP58 (51602)',
 '26099': 'SZRD1 (26099)',
 '3757': 'KCNH2 (3757)',
 '8454': 'CUL1 (8454)',
 '10827': 'FAM114A2 (10827)',
 '26999': 'CYFIP2 (26999)',
 '23118': 'TAB2 (23118)',
 '116254': 'GINM1 (116254)',
 '5610': 'EIF2AK2 (5610)',
 '57602': 'USP36 (57602)',
 '58508': 'KMT2C (58508)',
 '55283': 'MCOLN3 (55283)',
 '114800': 'CCDC85A (114800)',
 '23369': 'PUM2 (23369)',
 '84545': 'MRPL43 (84545)',
 '3700': 'ITIH4 (3700)',
 '3697': 'ITIH1 (3697)',
 '54969': 'HPF1 (54969)',
 '51663': 'ZFR (51663)',
 '55609': 'ZNF280C (55609)',
 '10886': 'NPFFR2 (10886)',
 '112885': 'PHF21B (112885)',
 '7185': 'TRAF1 (7185)',
 '54542': 'RC3H2 (54542)',
 '55540': 'IL17RB (55540)',

In [15]:
col_names = []
for id in landmark_ids:
    col_names.append(id_to_col[id])

col_names.append('Unnamed: 0')
col_names

['INSIG1 (3638)',
 'FOXO3 (2309)',
 'CDH3 (1001)',
 'ORC1 (4998)',
 'ITGAE (3682)',
 'CDK7 (1022)',
 'FOS (2353)',
 'CDK6 (1021)',
 'CDK4 (1019)',
 'CDK2 (1017)',
 'ITGB5 (3693)',
 'CDKN2A (1029)',
 'CDKN1B (1027)',
 'CDKN1A (1026)',
 'FPGS (2356)',
 'CEBPD (1052)',
 'CEBPA (1050)',
 'CENPE (1062)',
 'MICALL1 (85377)',
 'CETN3 (1070)',
 'UBE2C (11065)',
 'DUSP14 (11072)',
 'TOPBP1 (11073)',
 'B4GAT1 (11041)',
 'RBM34 (23029)',
 'TENT4A (11044)',
 'WDTC1 (23038)',
 'XPO7 (23039)',
 'AKAP8L (26993)',
 'RAB31 (11031)',
 'SPEN (23013)',
 'FBXO21 (23014)',
 'RAB21 (23011)',
 'SLC27A3 (11000)',
 'KIF2C (11004)',
 'CCDC85B (11007)',
 'TLK2 (11011)',
 'KDELR2 (11014)',
 'MCUR1 (63933)',
 'CDK19 (23097)',
 'JUN (3725)',
 'TBC1D9B (23061)',
 'PRSS23 (11098)',
 'RRP1B (23076)',
 'MYCBP2 (23077)',
 'CHEK1 (1111)',
 'KCNK1 (3775)',
 'CHN1 (1123)',
 'CIRBP (1153)',
 'HDGFL3 (50810)',
 'COPS7A (50813)',
 'NSDHL (50814)',
 'ATP11B (23200)',
 'PRAF2 (11230)',
 'JMJD6 (23210)',
 'RRS1 (23212)',
 'MPC2 (25874)',
 'ARID5B (84159)',
 'POLG2 (11232)',
 'CHEK2 (11200)',
 'BACE2 (25825)',
 'COG4 (25839)',
 'SPDEF (25803)',
 'BAMBI (25805)',
 'SPRED2 (200734)',
 'SLC2A6 (11182)',
 'SNX13 (23161)',
 'NISCH (11188)',
 'AARS1 (16)',
 'ABCF1 (23)',
 'ABL1 (25)',
 'FCHO1 (23149)',
 'DCUN1D4 (23142)',
 'PSIP1 (11168)',
 'ACAA1 (30)',
 'ACAT2 (39)',
 'ACLY (47)',
 'PKIG (11142)',
 'CORO1A (11151)',
 'MAST2 (23139)',
 'GPATCH8 (23131)',
 'FBXO7 (25793)',
 'LSM6 (11157)',
 'PWP1 (11137)',
 'KIF5C (3800)',
 'KIT (3815)',
 'FUT1 (2523)',
 'FYN (2534)',
 'GAA (2548)',
 'CLTC (1213)',
 'CLTB (1212)',
 'SLC37A4 (2542)',
 'GABPB1 (2553)',
 'KTN1 (3895)',
 'GALE (2582)',
 'GAPDH (2597)',
 'COL4A1 (1282)',
 'COL1A1 (1277)',
 'TRIM2 (23321)',
 'TSKU (25987)',
 'WASHC4 (23325)',
 'USP22 (23326)',
 'HDAC6 (10013)',
 'TWF2 (11344)',
 'WDR7 (23335)',
 'JADE2 (23338)',
 'ATMIN (23300)',
 'C2CD2 (25966)',
 'DDX42 (11325)',
 'TIPARP (25976)',
 'GNPDA1 (10007)',
 'ECD (11319)',
 'CLIC4 (25932)',
 'PNKP (11284)',
 'CAMSAP2 (23271)',
 'CHP1 (11261)',
 'PDS5A (23244)',
 'RRP12 (23223)',
 'SYNE2 (23224)',
 'LAMA3 (3909)',
 'STMN1 (3925)',
 'LBR (3930)',
 'HEBP1 (50865)',
 'GATA3 (2625)',
 'GATA2 (2624)',
 'LGALS8 (3964)',
 'LIG1 (3978)',
 'LIPA (3988)',
 'GFPT1 (2673)',
 'GHR (2690)',
 'CREB1 (1385)',
 'RPL39L (116832)',
 'CRKL (1399)',
 'CRK (1398)',
 'SLC35A3 (23443)',
 'TRAP1 (10131)',
 'G3BP1 (10146)',
 'KIF20A (10112)',
 'ARL4C (10123)',
 'SIRT3 (23410)',
 'TSPAN3 (10099)',
 'NUDCD3 (23386)',
 'SMC4 (10051)',
 'ARHGEF12 (23365)',
 'PPP1R13B (23368)',
 'ABCC5 (10057)',
 'DNM1L (10059)',
 'ABCB6 (10058)',
 'RRP8 (23378)',
 'PARP2 (10038)',
 'MAMLD1 (10046)',
 'DNAJB6 (10049)',
 'GLI2 (2736)',
 'GLRX (2745)',
 'CRYZ (1429)',
 'GNAI2 (2771)',
 'GNAI1 (2770)',
 'GNA11 (2767)',
 'GNA15 (2769)',
 'GNAS (2778)',
 'CSK (1445)',
 'CSNK2A2 (1459)',
 'CSNK1E (1454)',
 'CSNK1A1 (1452)',
 'CSRP1 (1465)',
 'SLC35B1 (10237)',
 'TIMM17B (10245)',
 'KAT6B (23522)',
 'NNT (23530)',
 'ADAT1 (23536)',
 'MFSD10 (10227)',
 'TRIB1 (10221)',
 'SUZ12 (23512)',
 'TRIM13 (10206)',
 'TXNDC9 (10190)',
 'FASTKD5 (60493)',
 'SORBS3 (10174)',
 'RBM6 (10180)',
 'MACF1 (23499)',
 'MBNL2 (10150)',
 'ICMT (23463)',
 'CEBPZ (10153)',
 'SFN (2810)',
 'SLC25A13 (10165)',
 'GPC1 (2817)',
 'CTNND1 (1500)',
 'CTSD (1509)',
 'CTSL (1514)',
 'GPER1 (2852)',
 'CYB561 (1534)',
 'GRB10 (2887)',
 'GRB7 (2886)',
 'GRN (2896)',
 'CEMIP2 (23670)',
 'HMG20B (10362)',
 'ARFIP2 (23647)',
 'LSM5 (23658)',
 'PLA2G15 (23659)',
 'TNIP1 (10318)',
 'NUP62 (23636)',
 'SSBP2 (23635)',
 'RXYLT1 (10329)',
 'IKZF1 (10320)',
 'NR3C1 (2908)',
 'PAK4 (10298)',
 'AKAP8 (10270)',
 'STUB1 (10273)',
 'TMEM50A (23585)',
 'KLHDC2 (23588)',
 'CXCL2 (2920)',
 'NET1 (10276)',
 'ACOT9 (23597)',
 'SMNDC1 (10285)',
 'DAG1 (1605)',
 'DAXX (1616)',
 'GSTM2 (2946)',
 'GSTZ1 (2954)',
 'GTF2A2 (2958)',
 'MSH6 (2956)',
 'ELAC2 (60528)',
 'DCTD (1635)',
 'DCK (1633)',
 'GTF2E2 (2961)',
 'DDB2 (1643)',
 'GADD45A (1647)',
 'DECR1 (1666)',
 'DDX10 (1662)',
 'DFFB (1677)',
 'DFFA (1676)',
 'CRTAP (10491)',
 'VAT1 (10493)',
 'STK25 (10494)',
 'LRRC41 (10489)',
 'VAV3 (10451)',
 'PPIE (10450)',
 'LYPLA1 (10434)',
 'MYL9 (10398)',
 'DLD (1738)',
 'TUBB6 (84617)',
 'DNM1 (1759)',
 'CIAPIN1 (57019)',
 'DNMT3A (1788)',
 'DNMT1 (1786)',
 'PLSCR3 (57048)',
 'TXLNA (200081)',
 'APPBP2 (10513)',
 'HYOU1 (10525)',
 'CHERP (10523)',
 'SNX6 (58533)',
 'THAP11 (57215)',
 'DRAP1 (10589)',
 'RPP38 (10557)',
 'SLC35A1 (10559)',
 'MCOLN1 (57192)',
 'DPH2 (1802)',
 'DSG2 (1829)',
 'TSC22D3 (1831)',
 'DUSP6 (1848)',
 'DUSP4 (1846)',
 'DUSP3 (1845)',
 'PSRC1 (84722)',
 'TOR1A (1861)',
 'E2F2 (1870)',
 'ECH1 (1891)',
 'SQOR (58472)',
 'LYRM1 (57149)',
 'SCYL3 (57147)',
 'ENOPH1 (58478)',
 'PRUNE1 (58497)',
 'ZMIZ1 (57178)',
 'YKT6 (10652)',
 'CGRRF1 (10668)',
 'NPRL2 (10641)',
 'IGF2BP2 (10644)',
 'STAMBP (10617)',
 'ST6GALNAC2 (10610)',
 'PAICS (10606)',
 'CNPY3 (10695)',
 'RRAGA (10670)',
 'EBP (10682)',
 'GNB5 (10681)',
 'H2AZ2 (94239)',
 'EDN1 (1906)',
 'EGF (1950)',
 'EGR1 (1958)',
 'EGFR (1956)',
 'EIF4EBP1 (1978)',
 'EIF5 (1983)',
 'EIF4G1 (1981)',
 'ELAVL1 (1994)',
 'MPZL1 (9019)',
 'SLC25A14 (9016)',
 'MAP7 (9053)',
 'ADO (84890)',
 'ARPP19 (10776)',
 'POP4 (10775)',
 'ZNF274 (10782)',
 'ABHD6 (57406)',
 'DNAJA3 (9093)',
 'USP14 (9097)',
 'KDM5B (10765)',
 'YME1L1 (10730)',
 'TCFL5 (10732)',
 'CASC3 (22794)',
 'COG2 (22796)',
 'MTHFD2 (10797)',
 'EML3 (256364)',
 'MTA1 (9112)',
 'PDLIM1 (9124)',
 'PRPF4 (9128)',
 'SMC3 (9126)',
 'CCNB2 (9133)',
 'CCNE2 (9134)',
 'SYNGR3 (9143)',
 'LPAR2 (9170)',
 'ZW10 (9183)',
 'ARHGEF2 (9181)',
 'CPSF4 (10898)',
 'MALT1 (10892)',
 'KHDC4 (22889)',
 'CLSTN1 (22883)',
 'FOXJ3 (22887)',
 'PGRMC1 (10857)',
 'CANT1 (124583)',
 'RAB11FIP2 (22841)',
 'ATF5 (22809)',
 'MTF2 (22823)',
 'PUF60 (22827)',
 'CLPX (10845)',
 'AURKB (9212)',
 'VAPB (9217)',
 'NOLC1 (9221)',
 'WASF3 (10810)',
 'UTP14A (10813)',
 'FRS2 (10818)',
 'GRWD1 (83743)',
 'UBE2L6 (9246)',
 'CYTH1 (9267)',
 'MAPKAPK2 (9261)',
 'COPB2 (9276)',
 'ITGB1BP1 (9270)',
 'BCL7B (9275)',
 'ADGRG1 (9289)',
 'HERC6 (55008)',
 'TMED10 (10972)',
 'ASCC3 (10973)',
 'PPP2R3C (55012)',
 'PIH1D1 (55011)',
 'RPIA (22934)',
 'PDIA5 (10954)',
 'TOMM34 (10953)',
 'FKBP14 (55033)',
 'EBNA1BP2 (10969)',
 'CDCA4 (55038)',
 'MLLT11 (10962)',
 'WIPF2 (147179)',
 'SACM1L (22908)',
 'ATF6 (22926)',
 'TCERG1 (10915)',
 'TM9SF2 (9375)',
 'EPN2 (22905)',
 'RNPS1 (10921)',
 'PDHX (8050)',
 'FOSL1 (8061)',
 'BLCAP (10904)',
 'HMGA2 (8091)',
 'TRIB3 (57761)',
 'PLEKHJ1 (55111)',
 'HEATR1 (55127)',
 'ANO10 (55129)',
 'UBR7 (55148)',
 'TRAPPC6A (79090)',
 'CHAC1 (79094)',
 'CCDC86 (79080)',
 'MAP4K4 (9448)',
 'HOMER2 (9455)',
 'SH3BP5 (9467)',
 'METRN (79006)',
 'PIGB (9488)',
 'PSMF1 (9491)',
 'ELOVL6 (79071)',
 'TMEM109 (79073)',
 'ITFG1 (81533)',
 'FBXO11 (80204)',
 'ADI1 (55256)',
 'CCDC92 (80212)',
 'GDPD5 (81544)',
 'POLD4 (57804)',
 'SPTLC2 (9517)',
 'TBPL1 (9519)',
 'BAG3 (9531)',
 'NRIP1 (8204)',
 'NCOA3 (8202)',
 'POLR1C (9533)',
 'SPAG7 (9552)',
 'SMC1A (8243)',
 'FAIM (55179)',
 'LAGE3 (8270)',
 'MBOAT7 (79143)',
 'PRR15L (79170)',
 'CRELD2 (79174)',
 'MAPK1IP1L (93487)',
 'FSD1 (79187)',
 'NPDC1 (56654)',
 'ABCF3 (55324)',
 'ERO1A (30001)',
 'TRAK2 (66008)',
 'COASY (80347)',
 'CHMP4A (29082)',
 'GTPBP8 (29083)',
 'IKBKE (9641)',
 'AXIN1 (8312)',
 'FEZ2 (9637)',
 'FZD1 (8321)',
 'HS2ST1 (9653)',
 'MTFR1 (9650)',
 'FZD7 (8324)',
 'CDC45 (8318)',
 'TERT (7015)',
 'TESK1 (7016)',
 'IPO13 (9670)',
 'VGLL4 (9686)',
 'TFDP1 (7027)',
 'NUP93 (9688)',
 'TFAP2A (7020)',
 'H2BC21 (8349)',
 'TRAM2 (9697)',
 'EDEM1 (9695)',
 'UBE3C (9690)',
 'TGFB3 (7043)',
 'TGFBR2 (7048)',
 'PIP4K2B (8396)',
 'TIMP2 (7077)',
 'TIAM1 (7074)',
 'TLE1 (7088)',
 'TJP1 (7082)',
 'TBC1D31 (93594)',
 'TLR4 (7099)',
 'DNAJC15 (29103)',
 'TICAM1 (148022)',
 'USP6NL (9712)',
 'GARRE1 (9710)',
 'CEP57 (9702)',
 'KIAA0100 (9703)',
 'HERPUD1 (9709)',
 'ADAM10 (102)',
 'CCP110 (9738)',
 'ADH5 (128)',
 'MLEC (9761)',
 'TSPAN6 (7105)',
 'NCK2 (8440)',
 'DUSP11 (8446)',
 'DYRK3 (8444)',
 'PARP1 (142)',
 'TSPAN4 (7106)',
 'ADRB2 (154)',
 'TATDN2 (9797)',
 'AGL (178)',
 'TOP2A (7153)',
 'TP53BP1 (7158)',
 'TP53 (7157)',
 'TP53BP2 (7159)',
 'RAE1 (8480)',
 'TPD52L2 (7165)',
 'TPM1 (7168)',
 'WDR61 (80349)',
 'MRPL19 (9801)',
 'SCRN1 (9805)',
 'EFCAB14 (9813)',
 'KEAP1 (9817)',
 'MELK (9833)',
 'AKT1 (207)',
 'CYCS (54205)',
 'PLEKHM1 (9842)',
 'ALAS1 (211)',
 'PIK3R3 (8503)',
 'NIPSNAP1 (8508)',
 'HAT1 (8520)',
 'KIAA0753 (9851)',
 'C2CD2L (9854)',
 'ENOSF1 (55556)',
 'ALDOA (226)',
 'C2CD5 (9847)',
 'TM9SF3 (56889)',
 'ELP1 (8518)',
 'ALDOC (230)',
 'TOMM70 (9868)',
 'BHLHE40 (8553)',
 'MAPKAPK5 (8550)',
 'WASHC5 (9897)',
 'AKR7A2 (8574)',
 'CASK (8573)',
 'MKNK1 (8569)',
 'GFUS (7264)',
 'SLC25A4 (291)',
 'SLC25A46 (91137)',
 'TXNRD1 (7296)',
 'CHMP6 (79643)',
 'IARS2 (55699)',
 'TERF2IP (54386)',
 'ACD (65057)',
 'CARMIL1 (55604)',
 'ANKRD10 (55608)',
 'DUSP22 (56940)',
 'KLHL21 (9903)',
 'STAP2 (55620)',
 'FAM20B (9917)',
 'NCAPD2 (9918)',
 'ARNT2 (9915)',
 'PAN2 (9924)',
 'KIF14 (9928)',
 'LPGAT1 (9926)',
 'OXSR1 (9943)',
 'ANXA7 (310)',
 'RUVBL1 (8607)',
 'APBB2 (323)',
 'TCTN1 (79600)',
 'BIRC2 (329)',
 'MVP (9961)',
 'BIRC5 (332)',
 'COQ8A (56997)',
 'PSMG1 (8624)',
 'APOE (348)',
 'APP (351)',
 'FAS (355)',
 'UBE2A (7319)',
 'DMTF1 (9988)',
 'BECN1 (8678)',
 'RHEB (6009)',
 'UGDH (7358)',
 'RHOA (387)',
 'ARHGAP1 (392)',
 'NR1H2 (7376)',
 'RNH1 (6050)',
 'USP1 (7398)',
 'PAK6 (56924)',
 'INTS3 (65123)',
 'PRR7 (80758)',
 'STIMATE (375346)',
 'TSEN2 (80746)',
 'TMCO1 (54499)',
 'CNDP2 (55748)',
 'NUP133 (55746)',
 'NPEPL1 (79716)',
 'MBTPS1 (8720)',
 'ASAH1 (427)',
 'RNMT (8731)',
 'EED (8726)',
 'GFOD1 (54438)',
 'CTNNAL1 (8727)',
 'KCTD5 (54442)',
 'VDAC1 (7416)',
 'MINDY1 (55793)',
 'ATF1 (466)',
 'ATP1B1 (481)',
 'RPA1 (6117)',
 'RPA3 (6119)',
 'RPA2 (6118)',
 'WFS1 (7466)',
 'GET1 (7485)',
 'XBP1 (7494)',
 'MRPL12 (6182)',
 'RPN1 (6184)',
 'RPS5 (6193)',
 'RPS6KA1 (6195)',
 'RPS6 (6194)',
 'DIPK1A (388650)',
 'ALDH7A1 (501)',
 'EXOSC4 (54512)',
 'CISD1 (55847)',
 'PEX11A (8800)',
 'CREG1 (8804)',
 'INPP4B (8821)',
 'ATP6V0B (533)',
 'IQGAP1 (8826)',
 'XPNPEP1 (7511)',
 'DDIT4 (54541)',
 'SOCS2 (8835)',
 'CFLAR (8837)',
 'CDK5R1 (8851)',
 'TLCD3A (79850)',
 'ZNF395 (55893)',
 'IER3 (8870)',
 'BAD (572)',
 'ST3GAL5 (8869)',
 'ZFP36 (7538)',
 'SLC5A6 (8884)',
 'BAX (581)',
 'SQSTM1 (8878)',
 'CPNE3 (8895)',
 'CCND1 (595)',
 'BCL2 (596)',
 'RSU1 (6251)',
 'RTN2 (6253)',
 'S100A4 (6275)',
 'S100A13 (6284)',
 'KDM3A (55818)',
 'PECR (55825)',
 'DHX29 (54505)',
 'EAPP (55837)',
 'TRAPPC3 (27095)',
 'RBKS (64080)',
 'CCNA1 (8900)',
 'ATP2C1 (27032)',
 'BDH1 (622)',
 'TIMELESS (8914)',
 'BID (637)',
 'BLMH (642)',
 'BLVRA (644)',
 'TCEAL4 (79921)',
 'BMP4 (652)',
 'BNIP3 (664)',
 'BNIP3L (665)',
 'DHDDS (79947)',
 'P4HA2 (8974)',
 'BPHL (670)',
 'BRCA1 (672)',
 'NUDT9 (53343)',
 'SATB1 (6304)',
 'PLOD3 (8985)',
 'P4HTM (54681)',
 'DENND2D (79961)',
 'NOL3 (8996)',
 'BTK (695)',
 'SCP2 (6342)',
 'CCL2 (6347)',
 'OXA1L (5018)',
 'OXCT1 (5019)',
 'ZNF131 (7690)',
 'PAFAH1B1 (5048)',
 'SERPINE1 (5054)',
 'PAK1 (5058)',
 'PAFAH1B3 (5050)',
 'SDHB (6390)',
 'PCCB (5096)',
 'PCBD1 (5092)',
 'NUP85 (79902)',
 'PAF1 (54623)',
 'KLHL9 (55958)',
 'BUB1B (701)',
 'C5 (727)',
 'ZMYM2 (7750)',
 'DDR1 (780)',
 'PCMT1 (5110)',
 'PCNA (5111)',
 'SGCB (6443)',
 'PCK2 (5106)',
 'PCM1 (5108)',
 'SHB (6461)',
 'SHC1 (6464)',
 'PDGFA (5154)',
 'SKIV2L (6499)',
 'SLC35F2 (54733)',
 'DMAC2L (27109)',
 'PACSIN3 (29763)',
 'CALM3 (808)',
 'CALU (813)',
 'CAPN1 (823)',
 'CAST (831)',
 'CASP2 (835)',
 'CASP3 (836)',
 'CASP7 (840)',
 'CASP10 (843)',
 'CAT (847)',
 'SKP1 (6500)',
 'CBLB (868)',
 'SLC1A4 (6509)',
 'CBR1 (873)',
 'CBR3 (874)',
 'CXCR4 (7852)',
 'TEX10 (54881)',
 'PAX8 (7849)',
 'CCNA2 (890)',
 'CCNB1 (891)',
 'CCND3 (896)',
 'CCNF (899)',
 'PFKL (5211)',
 'USP7 (7874)',
 'IFRD2 (7866)',
 'MAPKAPK3 (7867)',
 'PGAM1 (5223)',
 'PGM1 (5236)',
 'PHKA1 (5255)',
 'PHKB (5257)',
 'PHKG2 (5261)',
 'SMARCA4 (6597)',
 'SMARCC1 (6599)',
 'ZNF586 (54807)',
 'PIK3C2B (5287)',
 'PIK3C3 (5289)',
 'PIK3CA (5290)',
 'FBXL12 (54850)',
 'TNFRSF21 (27242)',
 'SESN1 (27244)',
 'RBM15B (29890)',
 'PIK3R4 (30849)',
 'CCNH (902)',
 'DNTTIP2 (30836)',
 'SCCPDH (51097)',
 'SCARB1 (949)',
 'REEP5 (7905)',
 'CD40 (958)',
 'CD44 (960)',
 'CD58 (965)',
 'SENP6 (26054)',
 'ADGRE5 (976)',
 'SMARCD2 (6603)',
 'RAI14 (26064)',
 'CDK1 (983)',
 'SNAP25 (6616)',
 'PIN1 (5300)',
 'CDC20 (991)',
 'CDC25A (993)',
 'CDC25B (994)',
 'MTERF3 (51001)',
 'CDC42 (998)',
 'AMDHD2 (51005)',
 'SNCA (6622)',
 'ISOC1 (51015)',
 'PLA2G4A (5321)',
 'ST7 (7982)',
 'MRPS16 (51021)',
 'FIS1 (51024)',
 'GOLT1B (51026)',
 'COG7 (91949)',
 'PLCB3 (5331)',
 'KAT6A (7994)',
 'GLOD4 (51031)',
 'SOX2 (6657)',
 'SOX4 (6659)',
 'SPAG4 (6676)',
 'PLP2 (5355)',
 'GMNN (51053)',
 'LAP3 (51056)',
 'LOXL1 (4016)',
 'PLK1 (5347)',
 'SPP1 (6696)',
 'PMAIP1 (5366)',
 'SPR (6697)',
 'PLS1 (5357)',
 'PLSCR1 (5359)',
 'PMM2 (5373)',
 'LRPAP1 (4043)',
 'NOSIP (51070)',
 'DERA (51071)',
 'YTHDF1 (54915)',
 'LYN (4067)',
 'TIMM22 (29928)',
 'SMAD3 (4088)',
 'NENF (29937)',
 'TXNL4B (54957)',
 'HOOK2 (29911)',
 'SNX11 (29916)',
 'ZNF451 (26036)',
 'TMEM97 (27346)',
 'LRP10 (26020)',
 'HTATSF1 (27336)',
 'RNF167 (26001)',
 'UBQLN2 (29978)',
 'SPTAN1 (6709)',
 'SRC (6714)',
 'POLB (5423)',
 'POLE2 (5427)',
 'POLR2K (5440)',
 'STAT1 (6772)',
 'STAT3 (6774)',
 'POLR2I (5438)',
 'STAT5B (6777)',
 'AURKA (6790)',
 'STK10 (6793)',
 'VPS28 (51160)',
 'MAN2B1 (4125)',
 'MAT2A (4144)',
 'HSD17B11 (51170)',
 'PPARD (5467)',
 'PPARG (5468)',
 'MBNL1 (4154)',
 'PPIC (5480)',
 'PPOX (5498)',
 'MCM3 (4172)',
 'ATG3 (64422)',
 'ZDHHC6 (64429)',
 'CIAO3 (64428)',
 'MRPS2 (51116)',
 'TES (26136)',
 'KIFBP (26128)',
 'STX1A (6804)',
 'STX4 (6810)',
 'STXBP1 (6812)',
 'STXBP2 (6813)',
 'SUV39H1 (6839)',
 'SUPV3L1 (6832)',
 'SYK (6850)',
 'MYCBP (26292)',
 'ME2 (4200)',
 'SYPL1 (6856)',
 'PPP2R5A (5525)',
 'PPP2R5E (5529)',
 'MEF2C (4208)',
 'MAP3K4 (4216)',
 'PRCP (5547)',
 'TARBP1 (6894)',
 'MEST (4232)',
 'JPT2 (90861)',
 'PRKACA (5566)',
 'PRKCD (5580)',
 'PRKCH (5583)',
 'SCAND1 (51282)',
 'CD320 (51293)',
 'PRKCQ (5588)',
 'MIF (4282)',
 'NUSAP1 (51203)',
 'PHGDH (26227)',
 'TBP (6908)',
 'TBX2 (6909)',
 'TCEA2 (6919)',
 'TBXA2R (6915)',
 'MAP2K5 (5607)',
 'MAPK9 (5601)',
 'MAPK13 (5603)',
 'VPS72 (6944)',
 'PRKX (5613)',
 'PROS1 (5627)',
 'LGMN (5641)',
 'FOXO4 (4303)',
 'MMP1 (4312)',
 'MMP2 (4313)',
 'DYNLT3 (6990)',
 'MNAT1 (4331)',
 'HTRA1 (5654)',
 'TCTA (6988)',
 'SNX7 (51375)',
 'ATP6V1D (51382)',
 'ZNF589 (51385)',
 'PSMB8 (5696)',
 'HADH (3033)',
 'HSD17B10 (3028)',
 'PSMB10 (5699)',
 'HDAC2 (3066)',
 'HIF1A (3091)',
 'HK1 (3098)',
 'UBE3B (89910)',
 'BZW2 (28969)',
 'NGRN (51335)',
 'PSMD2 (5708)',
 'PSMD4 (5710)',
 'PSMD9 (5715)',
 'PSMD10 (5716)',
 'PSME1 (5720)',
 'PSME2 (5721)',
 'PTGS2 (5743)',
 'PTK2 (5747)',
 'PTPN1 (5770)',
 'HLA-DMA (3108)',
 'PTPN12 (5782)',
 'HLA-DRA (3122)',
 'PTPN6 (5777)',
 'PTPRF (5792)',
 'PTPRK (5796)',
 'HACD3 (51495)',
 'PTPRC (5788)',
 'MSRA (4482)',
 'HMGCR (3156)',
 'HMOX1 (3162)',
 'HMGCS1 (3157)',
 'PRKAG2 (51422)',
 'ACBD3 (64746)',
 'UBE2J1 (51465)',
 'EVL (51466)',
 'CERK (64781)',
 'PXMP2 (5827)',
 'PXN (5829)',
 'PYCR1 (5831)',
 'PYGL (5836)',
 'RAB27A (5873)',
 'HOXA10 (3206)',
 'HOXA5 (3202)',
 'RAB4A (5867)',
 'RAC2 (5880)',
 'RAD9A (5883)',
 'MOK (5891)',
 'RAD51C (5889)',
 'RALA (5898)',
 'RALB (5899)',
 'MUC1 (4582)',
 'HPRT1 (3251)',
 'HES1 (3280)',
 'CHIC2 (26511)',
 'UFM1 (51569)',
 'TIMM9 (26520)',
 'LSR (51599)',
 'RAP1GAP (5909)',
 'RALGDS (5900)',
 'KDM5A (5927)',
 'RASA1 (5921)',
 'RB1 (5925)',
 'MYC (4609)',
 'MYBL2 (4605)',
 'GADD45B (4616)',
 'RELB (5971)',
 'HSPA1A (3303)',
 'DNAJB2 (3300)',
 'HSPA4 (3308)',
 'MYLK (4638)',
 'MYO10 (4651)',
 'RFC2 (5982)',
 'HSPB1 (3315)',
 'HSPA8 (3312)',
 'RFX5 (5993)',
 'HSPD1 (3329)',
 'RFC5 (5985)',
 'RFNG (5986)',
 'DNAJB1 (3337)',
 'RGS2 (5997)',
 'CTTN (2017)',
 'NCK1 (4690)',
 'EPHA3 (2042)',
 'EPB41L2 (2037)',
 'ICAM3 (3385)',
 'ICAM1 (3383)',
 'EPHB2 (2048)',
 'ID2 (3398)',
 'ERBB3 (2065)',
 'ERBB2 (2064)',
 'NR2F6 (2063)',
 'EPRS1 (2058)',
 'NT5DC2 (64943)',
 'DHRS7 (51635)',
 'IDE (3416)',
 'ETFB (2109)',
 'NFE2L2 (4780)',
 'NFIL3 (4783)',
 'ETV1 (2115)',
 'ETS1 (2113)',
 'NFATC3 (4775)',
 'NFATC4 (4776)',
 'NFKB2 (4791)',
 'NFKBIA (4792)',
 'NFKBIB (4793)',
 'NFKBIE (4794)',
 'EXT1 (2131)',
 'IFNAR1 (3454)',
 'IGFBP3 (3486)',
 'IGF2R (3482)',
 'IGF1R (3480)',
 'EZH2 (2146)',
 'PTK2B (2185)',
 'FAH (2184)',
 'FAT1 (2195)',
 'ZNF318 (24149)',
 'CAB39 (51719)',
 'NIT1 (4817)',
 'ARID4B (51742)',
 'IGHMBP2 (3508)',
 'NMT1 (4836)',
 'CNOT4 (4850)',
 'NOS3 (4846)',
 'PNP (4860)',
 'NOTCH1 (4851)',
 'NPC1 (4864)',
 'IKBKB (3551)',
 'SLC11A2 (4891)',
 'NRAS (4893)',
 'FDFT1 (2222)',
 'IL1B (3553)',
 'IL4R (3566)',
 'FGFR4 (2264)',
 'FGFR2 (2263)',
 'FHL2 (2274)',
 'IL13RA1 (3597)',
 'FKBP4 (2288)',
 'ABHD4 (63874)',
 'H2BC12 (85236)',
 'NUCB2 (4925)',
 'NUP88 (4927)',
 'NVL (4931)',
 'ILK (3611)',
 'INPP1 (3628)',
 'Unnamed: 0']

In [16]:
df_landmark = df[col_names]
df_landmark

,INSIG1 (3638),FOXO3 (2309),CDH3 (1001),ORC1 (4998),ITGAE (3682),CDK7 (1022),FOS (2353),CDK6 (1021),CDK4 (1019),CDK2 (1017),...,IL13RA1 (3597),FKBP4 (2288),ABHD4 (63874),H2BC12 (85236),NUCB2 (4925),NUP88 (4927),NVL (4931),ILK (3611),INPP1 (3628),Unnamed: 0
0,5.791814,3.078951,0.097611,3.981853,6.582857,5.844737,9.608920,3.785551,8.143077,6.265849,...,4.755422,6.632559,6.484460,7.925406,5.989366,6.017031,5.069960,4.966246,2.462052,ACH-001113
1,6.553821,3.068671,0.250962,3.244887,5.585263,5.726286,5.842225,5.782933,8.820626,5.837943,...,4.496335,6.336462,0.014355,8.471269,7.032321,6.405652,4.730096,6.434128,6.553975,ACH-001289
2,5.533875,3.220330,0.344828,3.490570,6.887769,4.951401,4.500802,3.339137,8.528220,7.006410,...,5.216843,5.364222,3.463361,5.226123,6.840337,6.225352,4.168321,6.897603,4.364572,ACH-001339
3,5.000901,4.510962,7.678776,3.117695,4.590362,5.954196,3.135863,3.867896,8.013518,4.858976,...,5.697941,6.442446,3.503349,6.378338,5.937109,5.694602,4.187451,6.231317,3.833902,ACH-001538
4,6.293518,2.877744,6.437794,4.193772,5.982537,4.977280,9.730215,0.310340,8.425971,6.651339,...,4.367371,6.162291,3.747387,4.048759,4.135042,4.890933,4.450221,6.272023,5.590662,ACH-000242
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,6.052459,3.007196,0.150560,4.504620,5.712596,4.813012,1.584963,3.168321,8.763909,7.108211,...,0.464668,7.425090,1.207893,5.656782,7.428109,5.706531,5.743084,5.893362,0.485427,ACH-000285
1402,4.660495,2.671293,5.514122,4.004501,4.950002,6.057234,2.963474,3.510962,7.680817,5.669027,...,5.038261,6.324091,3.493135,6.857981,5.267910,4.926474,3.870858,5.602884,4.789208,ACH-002669
1403,6.895060,4.458119,3.594549,2.805292,6.879583,5.966707,2.625270,3.577731,7.523170,5.596637,...,5.892877,4.890933,5.885086,6.522464,6.789599,5.454505,3.462052,6.692790,3.374344,ACH-001858
1404,6.649472,3.815575,4.865424,3.250962,5.525129,5.563463,5.226509,4.319762,8.485829,6.152386,...,4.942515,5.928844,5.464342,8.029011,5.282069,5.989593,3.544733,6.101398,3.734439,ACH-001997
1405,5.943687,2.615887,0.641546,4.679199,5.985728,4.613532,8.271556,1.851999,7.813204,6.303598,...,2.367371,6.286512,4.525443,6.094236,5.668743,5.646451,4.671859,6.584061,1.899176,ACH-000052

In [17]:
df_landmark = df_landmark.set_index('Unnamed: 0')
df_landmark

,INSIG1 (3638),FOXO3 (2309),CDH3 (1001),ORC1 (4998),ITGAE (3682),CDK7 (1022),FOS (2353),CDK6 (1021),CDK4 (1019),CDK2 (1017),...,FHL2 (2274),IL13RA1 (3597),FKBP4 (2288),ABHD4 (63874),H2BC12 (85236),NUCB2 (4925),NUP88 (4927),NVL (4931),ILK (3611),INPP1 (3628)
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
ACH-001113,5.791814,3.078951,0.097611,3.981853,6.582857,5.844737,9.608920,3.785551,8.143077,6.265849,...,4.707083,4.755422,6.632559,6.484460,7.925406,5.989366,6.017031,5.069960,4.966246,2.462052
ACH-001289,6.553821,3.068671,0.250962,3.244887,5.585263,5.726286,5.842225,5.782933,8.820626,5.837943,...,4.001802,4.496335,6.336462,0.014355,8.471269,7.032321,6.405652,4.730096,6.434128,6.553975
ACH-001339,5.533875,3.220330,0.344828,3.490570,6.887769,4.951401,4.500802,3.339137,8.528220,7.006410,...,5.384741,5.216843,5.364222,3.463361,5.226123,6.840337,6.225352,4.168321,6.897603,4.364572
ACH-001538,5.000901,4.510962,7.678776,3.117695,4.590362,5.954196,3.135863,3.867896,8.013518,4.858976,...,6.668176,5.697941,6.442446,3.503349,6.378338,5.937109,5.694602,4.187451,6.231317,3.833902
ACH-000242,6.293518,2.877744,6.437794,4.193772,5.982537,4.977280,9.730215,0.310340,8.425971,6.651339,...,6.371210,4.367371,6.162291,3.747387,4.048759,4.135042,4.890933,4.450221,6.272023,5.590662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-000285,6.052459,3.007196,0.150560,4.504620,5.712596,4.813012,1.584963,3.168321,8.763909,7.108211,...,0.389567,0.464668,7.425090,1.207893,5.656782,7.428109,5.706531,5.743084,5.893362,0.485427
ACH-002669,4.660495,2.671293,5.514122,4.004501,4.950002,6.057234,2.963474,3.510962,7.680817,5.669027,...,7.278264,5.038261,6.324091,3.493135,6.857981,5.267910,4.926474,3.870858,5.602884,4.789208
ACH-001858,6.895060,4.458119,3.594549,2.805292,6.879583,5.966707,2.625270,3.577731,7.523170,5.596637,...,5.258519,5.892877,4.890933,5.885086,6.522464,6.789599,5.454505,3.462052,6.692790,3.374344
ACH-001997,6.649472,3.815575,4.865424,3.250962,5.525129,5.563463,5.226509,4.319762,8.485829,6.152386,...,7.744094,4.942515,5.928844,5.464342,8.029011,5.282069,5.989593,3.544733,6.101398,3.734439
ACH-000052,5.943687,2.615887,0.641546,4.679199,5.985728,4.613532,8.271556,1.851999,7.813204,6.303598,...,2.422233,2.367371,6.286512,4.525443,6.094236,5.668743,5.646451,4.671859,6.584061,1.899176

In [18]:
df_landmark.loc['ACH-001339']

INSIG1 (3638)    5.533875
FOXO3 (2309)     3.220330
CDH3 (1001)      0.344828
ORC1 (4998)      3.490570
ITGAE (3682)     6.887769
                   ...
NUCB2 (4925)     6.840337
NUP88 (4927)     6.225352
NVL (4931)       4.168321
ILK (3611)       6.897603
INPP1 (3628)     4.364572
Name: ACH-001339, Length: 978, dtype: float64

In [19]:
col_names_actual = [name.split()[0] for name in col_names]
len(col_names_actual)
actual = set(col_names_actual)
len(actual)

actual_missing = actual - set(landmark_names)
actual_missing

{'AARS1',
 'CEMIP2',
 'CIAO3',
 'DIPK1A',
 'DMAC2L',
 'ELP1',
 'EPRS1',
 'GARRE1',
 'GET1',
 'GFUS',
 'H2AZ2',
 'H2BC12',
 'H2BC21',
 'HDGFL3',
 'JPT2',
 'KHDC4',
 'KIFBP',
 'RXYLT1',
 'SQOR',
 'STIMATE',
 'TENT4A',
 'TLCD3A',
 'Unnamed:'}

In [20]:
missing = set(landmark_names) - set(column_names)
missing

{'AARS',
 'ATP5S',
 'EPRS',
 'FAM57A',
 'FAM69A',
 'H2AFV',
 'HDGFRP3',
 'HIST1H2BK',
 'HIST2H2BE',
 'HN1L',
 'IKBKAP',
 'KIAA0355',
 'KIAA0907',
 'KIF1BP',
 'NARFL',
 'PAPD7',
 'SQRDL',
 'TMEM110',
 'TMEM2',
 'TMEM5',
 'TSTA3',
 'WRB'}

In [21]:
print(len(actual_missing))
print(len(missing))

23
22

In [22]:
actual_missing_with_ids = [name for name in col_names if name.split()[0] in actual_missing]
actual_missing_with_ids

['TENT4A (11044)',
 'HDGFL3 (50810)',
 'AARS1 (16)',
 'CEMIP2 (23670)',
 'RXYLT1 (10329)',
 'SQOR (58472)',
 'H2AZ2 (94239)',
 'KHDC4 (22889)',
 'H2BC21 (8349)',
 'GARRE1 (9710)',
 'ELP1 (8518)',
 'GFUS (7264)',
 'STIMATE (375346)',
 'GET1 (7485)',
 'DIPK1A (388650)',
 'TLCD3A (79850)',
 'DMAC2L (27109)',
 'CIAO3 (64428)',
 'KIFBP (26128)',
 'JPT2 (90861)',
 'EPRS1 (2058)',
 'H2BC12 (85236)',
 'Unnamed: 0']

In [23]:
missing_with_ids = landmarks[landmarks["Symbol"].isin(missing)][["Entrez ID", "Symbol"]]
missing_with_ids

     Entrez ID     Symbol
25       11044      PAPD7
49       50810    HDGFRP3
68          16       AARS
193      23670      TMEM2
201      10329      TMEM5
264      58472      SQRDL
281      94239      H2AFV
319      22889   KIAA0907
425       8349  HIST2H2BE
441       9710   KIAA0355
484       8518     IKBKAP
493       7264      TSTA3
538     375346    TMEM110
559       7485        WRB
566     388650     FAM69A
580      79850     FAM57A
653      27109      ATP5S
782      64428      NARFL
785      26128     KIF1BP
803      90861       HN1L
925       2058       EPRS
972      85236  HIST1H2BK

In [26]:
ppi_df = pd.read_csv('/Users/zijiexu/GEMS-LAB/jumpstart_bundle 2/data/protein_features/string_ppi.csv')
ppi_df

       protein_id_a protein_id_b  score  source
0              ARF5        ACAP1  0.825  STRING
1              ARF5         COPA  0.718  STRING
2              ARF5    RAB11FIP3  0.952  STRING
3              ARF5        COPB2  0.752  STRING
4              ARF5         COPE  0.795  STRING
...             ...          ...    ...     ...
473855         LDB1        ZFPM1  0.942  STRING
473856         LDB1         LHX4  0.944  STRING
473857         RFX7         RFX5  0.780  STRING
473858         RFX7       RFXANK  0.978  STRING
473859         RFX7       ANKRA2  0.973  STRING

[473860 rows x 4 columns]

In [27]:
landmark_names

['INSIG1',
 'FOXO3',
 'CDH3',
 'ORC1',
 'ITGAE',
 'CDK7',
 'FOS',
 'CDK6',
 'CDK4',
 'CDK2',
 'ITGB5',
 'CDKN2A',
 'CDKN1B',
 'CDKN1A',
 'FPGS',
 'CEBPD',
 'CEBPA',
 'CENPE',
 'MICALL1',
 'CETN3',
 'UBE2C',
 'DUSP14',
 'TOPBP1',
 'B4GAT1',
 'RBM34',
 'PAPD7',
 'WDTC1',
 'XPO7',
 'AKAP8L',
 'RAB31',
 'SPEN',
 'FBXO21',
 'RAB21',
 'SLC27A3',
 'KIF2C',
 'CCDC85B',
 'TLK2',
 'KDELR2',
 'MCUR1',
 'CDK19',
 'JUN',
 'TBC1D9B',
 'PRSS23',
 'RRP1B',
 'MYCBP2',
 'CHEK1',
 'KCNK1',
 'CHN1',
 'CIRBP',
 'HDGFRP3',
 'COPS7A',
 'NSDHL',
 'ATP11B',
 'PRAF2',
 'JMJD6',
 'RRS1',
 'MPC2',
 'ARID5B',
 'POLG2',
 'CHEK2',
 'BACE2',
 'COG4',
 'SPDEF',
 'BAMBI',
 'SPRED2',
 'SLC2A6',
 'SNX13',
 'NISCH',
 'AARS',
 'ABCF1',
 'ABL1',
 'FCHO1',
 'DCUN1D4',
 'PSIP1',
 'ACAA1',
 'ACAT2',
 'ACLY',
 'PKIG',
 'CORO1A',
 'MAST2',
 'GPATCH8',
 'FBXO7',
 'LSM6',
 'PWP1',
 'KIF5C',
 'KIT',
 'FUT1',
 'FYN',
 'GAA',
 'CLTC',
 'CLTB',
 'SLC37A4',
 'GABPB1',
 'KTN1',
 'GALE',
 'GAPDH',
 'COL4A1',
 'COL1A1',
 'TRIM2',
 'TSKU',
 'WASHC4',
 'USP22',
 'HDAC6',
 'TWF2',
 'WDR7',
 'JADE2',
 'ATMIN',
 'C2CD2',
 'DDX42',
 'TIPARP',
 'GNPDA1',
 'ECD',
 'CLIC4',
 'PNKP',
 'CAMSAP2',
 'CHP1',
 'PDS5A',
 'RRP12',
 'SYNE2',
 'LAMA3',
 'STMN1',
 'LBR',
 'HEBP1',
 'GATA3',
 'GATA2',
 'LGALS8',
 'LIG1',
 'LIPA',
 'GFPT1',
 'GHR',
 'CREB1',
 'RPL39L',
 'CRKL',
 'CRK',
 'SLC35A3',
 'TRAP1',
 'G3BP1',
 'KIF20A',
 'ARL4C',
 'SIRT3',
 'TSPAN3',
 'NUDCD3',
 'SMC4',
 'ARHGEF12',
 'PPP1R13B',
 'ABCC5',
 'DNM1L',
 'ABCB6',
 'RRP8',
 'PARP2',
 'MAMLD1',
 'DNAJB6',
 'GLI2',
 'GLRX',
 'CRYZ',
 'GNAI2',
 'GNAI1',
 'GNA11',
 'GNA15',
 'GNAS',
 'CSK',
 'CSNK2A2',
 'CSNK1E',
 'CSNK1A1',
 'CSRP1',
 'SLC35B1',
 'TIMM17B',
 'KAT6B',
 'NNT',
 'ADAT1',
 'MFSD10',
 'TRIB1',
 'SUZ12',
 'TRIM13',
 'TXNDC9',
 'FASTKD5',
 'SORBS3',
 'RBM6',
 'MACF1',
 'MBNL2',
 'ICMT',
 'CEBPZ',
 'SFN',
 'SLC25A13',
 'GPC1',
 'CTNND1',
 'CTSD',
 'CTSL',
 'GPER1',
 'CYB561',
 'GRB10',
 'GRB7',
 'GRN',
 'TMEM2',
 'HMG20B',
 'ARFIP2',
 'LSM5',
 'PLA2G15',
 'TNIP1',
 'NUP62',
 'SSBP2',
 'TMEM5',
 'IKZF1',
 'NR3C1',
 'PAK4',
 'AKAP8',
 'STUB1',
 'TMEM50A',
 'KLHDC2',
 'CXCL2',
 'NET1',
 'ACOT9',
 'SMNDC1',
 'DAG1',
 'DAXX',
 'GSTM2',
 'GSTZ1',
 'GTF2A2',
 'MSH6',
 'ELAC2',
 'DCTD',
 'DCK',
 'GTF2E2',
 'DDB2',
 'GADD45A',
 'DECR1',
 'DDX10',
 'DFFB',
 'DFFA',
 'CRTAP',
 'VAT1',
 'STK25',
 'LRRC41',
 'VAV3',
 'PPIE',
 'LYPLA1',
 'MYL9',
 'DLD',
 'TUBB6',
 'DNM1',
 'CIAPIN1',
 'DNMT3A',
 'DNMT1',
 'PLSCR3',
 'TXLNA',
 'APPBP2',
 'HYOU1',
 'CHERP',
 'SNX6',
 'THAP11',
 'DRAP1',
 'RPP38',
 'SLC35A1',
 'MCOLN1',
 'DPH2',
 'DSG2',
 'TSC22D3',
 'DUSP6',
 'DUSP4',
 'DUSP3',
 'PSRC1',
 'TOR1A',
 'E2F2',
 'ECH1',
 'SQRDL',
 'LYRM1',
 'SCYL3',
 'ENOPH1',
 'PRUNE1',
 'ZMIZ1',
 'YKT6',
 'CGRRF1',
 'NPRL2',
 'IGF2BP2',
 'STAMBP',
 'ST6GALNAC2',
 'PAICS',
 'CNPY3',
 'RRAGA',
 'EBP',
 'GNB5',
 'H2AFV',
 'EDN1',
 'EGF',
 'EGR1',
 'EGFR',
 'EIF4EBP1',
 'EIF5',
 'EIF4G1',
 'ELAVL1',
 'MPZL1',
 'SLC25A14',
 'MAP7',
 'ADO',
 'ARPP19',
 'POP4',
 'ZNF274',
 'ABHD6',
 'DNAJA3',
 'USP14',
 'KDM5B',
 'YME1L1',
 'TCFL5',
 'CASC3',
 'COG2',
 'MTHFD2',
 'EML3',
 'MTA1',
 'PDLIM1',
 'PRPF4',
 'SMC3',
 'CCNB2',
 'CCNE2',
 'SYNGR3',
 'LPAR2',
 'ZW10',
 'ARHGEF2',
 'CPSF4',
 'MALT1',
 'KIAA0907',
 'CLSTN1',
 'FOXJ3',
 'PGRMC1',
 'CANT1',
 'RAB11FIP2',
 'ATF5',
 'MTF2',
 'PUF60',
 'CLPX',
 'AURKB',
 'VAPB',
 'NOLC1',
 'WASF3',
 'UTP14A',
 'FRS2',
 'GRWD1',
 'UBE2L6',
 'CYTH1',
 'MAPKAPK2',
 'COPB2',
 'ITGB1BP1',
 'BCL7B',
 'ADGRG1',
 'HERC6',
 'TMED10',
 'ASCC3',
 'PPP2R3C',
 'PIH1D1',
 'RPIA',
 'PDIA5',
 'TOMM34',
 'FKBP14',
 'EBNA1BP2',
 'CDCA4',
 'MLLT11',
 'WIPF2',
 'SACM1L',
 'ATF6',
 'TCERG1',
 'TM9SF2',
 'EPN2',
 'RNPS1',
 'PDHX',
 'FOSL1',
 'BLCAP',
 'HMGA2',
 'TRIB3',
 'PLEKHJ1',
 'HEATR1',
 'ANO10',
 'UBR7',
 'TRAPPC6A',
 'CHAC1',
 'CCDC86',
 'MAP4K4',
 'HOMER2',
 'SH3BP5',
 'METRN',
 'PIGB',
 'PSMF1',
 'ELOVL6',
 'TMEM109',
 'ITFG1',
 'FBXO11',
 'ADI1',
 'CCDC92',
 'GDPD5',
 'POLD4',
 'SPTLC2',
 'TBPL1',
 'BAG3',
 'NRIP1',
 'NCOA3',
 'POLR1C',
 'SPAG7',
 'SMC1A',
 'FAIM',
 'LAGE3',
 'MBOAT7',
 'PRR15L',
 'CRELD2',
 'MAPK1IP1L',
 'FSD1',
 'NPDC1',
 'ABCF3',
 'ERO1A',
 'TRAK2',
 'COASY',
 'CHMP4A',
 'GTPBP8',
 'IKBKE',
 'AXIN1',
 'FEZ2',
 'FZD1',
 'HS2ST1',
 'MTFR1',
 'FZD7',
 'CDC45',
 'TERT',
 'TESK1',
 'IPO13',
 'VGLL4',
 'TFDP1',
 'NUP93',
 'TFAP2A',
 'HIST2H2BE',
 'TRAM2',
 'EDEM1',
 'UBE3C',
 'TGFB3',
 'TGFBR2',
 'PIP4K2B',
 'TIMP2',
 'TIAM1',
 'TLE1',
 'TJP1',
 'TBC1D31',
 'TLR4',
 'DNAJC15',
 'TICAM1',
 'USP6NL',
 'KIAA0355',
 'CEP57',
 'KIAA0100',
 'HERPUD1',
 'ADAM10',
 'CCP110',
 'ADH5',
 'MLEC',
 'TSPAN6',
 'NCK2',
 'DUSP11',
 'DYRK3',
 'PARP1',
 'TSPAN4',
 'ADRB2',
 'TATDN2',
 'AGL',
 'TOP2A',
 'TP53BP1',
 'TP53',
 'TP53BP2',
 'RAE1',
 'TPD52L2',
 'TPM1',
 'WDR61',
 'MRPL19',
 'SCRN1',
 'EFCAB14',
 'KEAP1',
 'MELK',
 'AKT1',
 'CYCS',
 'PLEKHM1',
 'ALAS1',
 'PIK3R3',
 'NIPSNAP1',
 'HAT1',
 'KIAA0753',
 'C2CD2L',
 'ENOSF1',
 'ALDOA',
 'C2CD5',
 'TM9SF3',
 'IKBKAP',
 'ALDOC',
 'TOMM70',
 'BHLHE40',
 'MAPKAPK5',
 'WASHC5',
 'AKR7A2',
 'CASK',
 'MKNK1',
 'TSTA3',
 'SLC25A4',
 'SLC25A46',
 'TXNRD1',
 'CHMP6',
 'IARS2',
 'TERF2IP',
 'ACD',
 'CARMIL1',
 'ANKRD10',
 'DUSP22',
 'KLHL21',
 'STAP2',
 'FAM20B',
 'NCAPD2',
 'ARNT2',
 'PAN2',
 'KIF14',
 'LPGAT1',
 'OXSR1',
 'ANXA7',
 'RUVBL1',
 'APBB2',
 'TCTN1',
 'BIRC2',
 'MVP',
 'BIRC5',
 'COQ8A',
 'PSMG1',
 'APOE',
 'APP',
 'FAS',
 'UBE2A',
 'DMTF1',
 'BECN1',
 'RHEB',
 'UGDH',
 'RHOA',
 'ARHGAP1',
 'NR1H2',
 'RNH1',
 'USP1',
 'PAK6',
 'INTS3',
 'PRR7',
 'TMEM110',
 'TSEN2',
 'TMCO1',
 'CNDP2',
 'NUP133',
 'NPEPL1',
 'MBTPS1',
 'ASAH1',
 'RNMT',
 'EED',
 'GFOD1',
 'CTNNAL1',
 'KCTD5',
 'VDAC1',
 'MINDY1',
 'ATF1',
 'ATP1B1',
 'RPA1',
 'RPA3',
 'RPA2',
 'WFS1',
 'WRB',
 'XBP1',
 'MRPL12',
 'RPN1',
 'RPS5',
 'RPS6KA1',
 'RPS6',
 'FAM69A',
 'ALDH7A1',
 'EXOSC4',
 'CISD1',
 'PEX11A',
 'CREG1',
 'INPP4B',
 'ATP6V0B',
 'IQGAP1',
 'XPNPEP1',
 'DDIT4',
 'SOCS2',
 'CFLAR',
 'CDK5R1',
 'FAM57A',
 'ZNF395',
 'IER3',
 'BAD',
 'ST3GAL5',
 'ZFP36',
 'SLC5A6',
 'BAX',
 'SQSTM1',
 'CPNE3',
 'CCND1',
 'BCL2',
 'RSU1',
 'RTN2',
 'S100A4',
 'S100A13',
 'KDM3A',
 'PECR',
 'DHX29',
 'EAPP',
 'TRAPPC3',
 'RBKS',
 'CCNA1',
 'ATP2C1',
 'BDH1',
 'TIMELESS',
 'BID',
 'BLMH',
 'BLVRA',
 'TCEAL4',
 'BMP4',
 'BNIP3',
 'BNIP3L',
 'DHDDS',
 'P4HA2',
 'BPHL',
 'BRCA1',
 'NUDT9',
 'SATB1',
 'PLOD3',
 'P4HTM',
 'DENND2D',
 'NOL3',
 'BTK',
 'SCP2',
 'CCL2',
 'OXA1L',
 'OXCT1',
 'ZNF131',
 'PAFAH1B1',
 'SERPINE1',
 'PAK1',
 'PAFAH1B3',
 'SDHB',
 'PCCB',
 'PCBD1',
 'NUP85',
 'PAF1',
 'KLHL9',
 'BUB1B',
 'C5',
 'ZMYM2',
 'DDR1',
 'PCMT1',
 'PCNA',
 'SGCB',
 'PCK2',
 'PCM1',
 'SHB',
 'SHC1',
 'PDGFA',
 'SKIV2L',
 'SLC35F2',
 'ATP5S',
 'PACSIN3',
 'CALM3',
 'CALU',
 'CAPN1',
 'CAST',
 'CASP2',
 'CASP3',
 'CASP7',
 'CASP10',
 'CAT',
 'SKP1',
 'CBLB',
 'SLC1A4',
 'CBR1',
 'CBR3',
 'CXCR4',
 'TEX10',
 'PAX8',
 'CCNA2',
 'CCNB1',
 'CCND3',
 'CCNF',
 'PFKL',
 'USP7',
 'IFRD2',
 'MAPKAPK3',
 'PGAM1',
 'PGM1',
 'PHKA1',
 'PHKB',
 'PHKG2',
 'SMARCA4',
 'SMARCC1',
 'ZNF586',
 'PIK3C2B',
 'PIK3C3',
 'PIK3CA',
 'FBXL12',
 'TNFRSF21',
 'SESN1',
 'RBM15B',
 'PIK3R4',
 'CCNH',
 'DNTTIP2',
 'SCCPDH',
 'SCARB1',
 'REEP5',
 'CD40',
 'CD44',
 'CD58',
 'SENP6',
 'ADGRE5',
 'SMARCD2',
 'RAI14',
 'CDK1',
 'SNAP25',
 'PIN1',
 'CDC20',
 'CDC25A',
 'CDC25B',
 'MTERF3',
 'CDC42',
 'AMDHD2',
 'SNCA',
 'ISOC1',
 'PLA2G4A',
 'ST7',
 'MRPS16',
 'FIS1',
 'GOLT1B',
 'COG7',
 'PLCB3',
 'KAT6A',
 'GLOD4',
 'SOX2',
 'SOX4',
 'SPAG4',
 'PLP2',
 'GMNN',
 'LAP3',
 'LOXL1',
 'PLK1',
 'SPP1',
 'PMAIP1',
 'SPR',
 'PLS1',
 'PLSCR1',
 'PMM2',
 'LRPAP1',
 'NOSIP',
 'DERA',
 'YTHDF1',
 'LYN',
 'TIMM22',
 'SMAD3',
 'NENF',
 'TXNL4B',
 'HOOK2',
 'SNX11',
 'ZNF451',
 'TMEM97',
 'LRP10',
 'HTATSF1',
 'RNF167',
 'UBQLN2',
 'SPTAN1',
 'SRC',
 'POLB',
 'POLE2',
 'POLR2K',
 'STAT1',
 'STAT3',
 'POLR2I',
 'STAT5B',
 'AURKA',
 'STK10',
 'VPS28',
 'MAN2B1',
 'MAT2A',
 'HSD17B11',
 'PPARD',
 'PPARG',
 'MBNL1',
 'PPIC',
 'PPOX',
 'MCM3',
 'ATG3',
 'ZDHHC6',
 'NARFL',
 'MRPS2',
 'TES',
 'KIF1BP',
 'STX1A',
 'STX4',
 'STXBP1',
 'STXBP2',
 'SUV39H1',
 'SUPV3L1',
 'SYK',
 'MYCBP',
 'ME2',
 'SYPL1',
 'PPP2R5A',
 'PPP2R5E',
 'MEF2C',
 'MAP3K4',
 'PRCP',
 'TARBP1',
 'MEST',
 'HN1L',
 'PRKACA',
 'PRKCD',
 'PRKCH',
 'SCAND1',
 'CD320',
 'PRKCQ',
 'MIF',
 'NUSAP1',
 'PHGDH',
 'TBP',
 'TBX2',
 'TCEA2',
 'TBXA2R',
 'MAP2K5',
 'MAPK9',
 'MAPK13',
 'VPS72',
 'PRKX',
 'PROS1',
 'LGMN',
 'FOXO4',
 'MMP1',
 'MMP2',
 'DYNLT3',
 'MNAT1',
 'HTRA1',
 'TCTA',
 'SNX7',
 'ATP6V1D',
 'ZNF589',
 'PSMB8',
 'HADH',
 'HSD17B10',
 'PSMB10',
 'HDAC2',
 'HIF1A',
 'HK1',
 'UBE3B',
 'BZW2',
 'NGRN',
 'PSMD2',
 'PSMD4',
 'PSMD9',
 'PSMD10',
 'PSME1',
 'PSME2',
 'PTGS2',
 'PTK2',
 'PTPN1',
 'HLA-DMA',
 'PTPN12',
 'HLA-DRA',
 'PTPN6',
 'PTPRF',
 'PTPRK',
 'HACD3',
 'PTPRC',
 'MSRA',
 'HMGCR',
 'HMOX1',
 'HMGCS1',
 'PRKAG2',
 'ACBD3',
 'UBE2J1',
 'EVL',
 'CERK',
 'PXMP2',
 'PXN',
 'PYCR1',
 'PYGL',
 'RAB27A',
 'HOXA10',
 'HOXA5',
 'RAB4A',
 'RAC2',
 'RAD9A',
 'MOK',
 'RAD51C',
 'RALA',
 'RALB',
 'MUC1',
 'HPRT1',
 'HES1',
 'CHIC2',
 'UFM1',
 'TIMM9',
 'LSR',
 'RAP1GAP',
 'RALGDS',
 'KDM5A',
 'RASA1',
 'RB1',
 'MYC',
 'MYBL2',
 'GADD45B',
 'RELB',
 'HSPA1A',
 'DNAJB2',
 'HSPA4',
 'MYLK',
 'MYO10',
 'RFC2',
 'HSPB1',
 'HSPA8',
 'RFX5',
 'HSPD1',
 'RFC5',
 'RFNG',
 'DNAJB1',
 'RGS2',
 'CTTN',
 'NCK1',
 'EPHA3',
 'EPB41L2',
 'ICAM3',
 'ICAM1',
 'EPHB2',
 'ID2',
 'ERBB3',
 'ERBB2',
 'NR2F6',
 'EPRS',
 'NT5DC2',
 'DHRS7',
 'IDE',
 'ETFB',
 'NFE2L2',
 'NFIL3',
 'ETV1',
 'ETS1',
 'NFATC3',
 'NFATC4',
 'NFKB2',
 'NFKBIA',
 'NFKBIB',
 'NFKBIE',
 'EXT1',
 'IFNAR1',
 'IGFBP3',
 'IGF2R',
 'IGF1R',
 'EZH2',
 'PTK2B',
 'FAH',
 'FAT1',
 'ZNF318',
 'CAB39',
 'NIT1',
 'ARID4B',
 'IGHMBP2',
 'NMT1',
 'CNOT4',
 'NOS3',
 'PNP',
 'NOTCH1',
 'NPC1',
 'IKBKB',
 'SLC11A2',
 'NRAS',
 'FDFT1',
 'IL1B',
 'IL4R',
 'FGFR4',
 'FGFR2',
 'FHL2',
 'IL13RA1',
 'FKBP4',
 'ABHD4',
 'HIST1H2BK',
 'NUCB2',
 'NUP88',
 'NVL',
 'ILK',
 'INPP1']

In [28]:
landmark_set = set(landmark_names)

ppi_filtered = ppi_df[
    ppi_df["protein_id_a"].isin(landmark_set) &
    ppi_df["protein_id_b"].isin(landmark_set)
]

ppi_filtered

       protein_id_a protein_id_b  score  source
38            FKBP4        HSPA8  0.942  STRING
43            FKBP4         AKT1  0.914  STRING
45            FKBP4       DNAJB1  0.957  STRING
48            FKBP4        HSPA4  0.998  STRING
51            FKBP4        NR3C1  0.996  STRING
...             ...          ...    ...     ...
473489       TFAP2A        MYBL2  0.843  STRING
473491       TFAP2A         APOE  0.782  STRING
473492       TFAP2A          JUN  0.758  STRING
473494       TFAP2A         TP53  0.913  STRING
473507       TFAP2A          KIT  0.802  STRING

[7824 rows x 4 columns]

In [29]:
ppi_filtered.groupby('protein_id_a').count()

              protein_id_b  score  source
protein_id_a
ABCB6                    1      1       1
ABCF1                    2      2       2
ABCF3                    2      2       2
ABHD4                    1      1       1
ABHD6                    1      1       1
...                    ...    ...     ...
ZFP36                    5      5       5
ZMIZ1                    1      1       1
ZMYM2                    2      2       2
ZNF451                   1      1       1
ZW10                     5      5       5

[757 rows x 3 columns]

In [30]:
ppi_filtered.groupby('protein_id_b').count()

              protein_id_a  score  source
protein_id_b
ABCB6                    1      1       1
ABCF1                    2      2       2
ABCF3                    2      2       2
ABHD4                    1      1       1
ABHD6                    1      1       1
...                    ...    ...     ...
ZFP36                    5      5       5
ZMIZ1                    1      1       1
ZMYM2                    2      2       2
ZNF451                   1      1       1
ZW10                     5      5       5

[757 rows x 3 columns]

In [31]:
[name.split()[-1][1:-1] for name in df_landmark.columns.to_list()]

['3638',
 '2309',
 '1001',
 '4998',
 '3682',
 '1022',
 '2353',
 '1021',
 '1019',
 '1017',
 '3693',
 '1029',
 '1027',
 '1026',
 '2356',
 '1052',
 '1050',
 '1062',
 '85377',
 '1070',
 '11065',
 '11072',
 '11073',
 '11041',
 '23029',
 '11044',
 '23038',
 '23039',
 '26993',
 '11031',
 '23013',
 '23014',
 '23011',
 '11000',
 '11004',
 '11007',
 '11011',
 '11014',
 '63933',
 '23097',
 '3725',
 '23061',
 '11098',
 '23076',
 '23077',
 '1111',
 '3775',
 '1123',
 '1153',
 '50810',
 '50813',
 '50814',
 '23200',
 '11230',
 '23210',
 '23212',
 '25874',
 '84159',
 '11232',
 '11200',
 '25825',
 '25839',
 '25803',
 '25805',
 '200734',
 '11182',
 '23161',
 '11188',
 '16',
 '23',
 '25',
 '23149',
 '23142',
 '11168',
 '30',
 '39',
 '47',
 '11142',
 '11151',
 '23139',
 '23131',
 '25793',
 '11157',
 '11137',
 '3800',
 '3815',
 '2523',
 '2534',
 '2548',
 '1213',
 '1212',
 '2542',
 '2553',
 '3895',
 '2582',
 '2597',
 '1282',
 '1277',
 '23321',
 '25987',
 '23325',
 '23326',
 '10013',
 '11344',
 '23335',
 '23338',
 '23300',
 '25966',
 '11325',
 '25976',
 '10007',
 '11319',
 '25932',
 '11284',
 '23271',
 '11261',
 '23244',
 '23223',
 '23224',
 '3909',
 '3925',
 '3930',
 '50865',
 '2625',
 '2624',
 '3964',
 '3978',
 '3988',
 '2673',
 '2690',
 '1385',
 '116832',
 '1399',
 '1398',
 '23443',
 '10131',
 '10146',
 '10112',
 '10123',
 '23410',
 '10099',
 '23386',
 '10051',
 '23365',
 '23368',
 '10057',
 '10059',
 '10058',
 '23378',
 '10038',
 '10046',
 '10049',
 '2736',
 '2745',
 '1429',
 '2771',
 '2770',
 '2767',
 '2769',
 '2778',
 '1445',
 '1459',
 '1454',
 '1452',
 '1465',
 '10237',
 '10245',
 '23522',
 '23530',
 '23536',
 '10227',
 '10221',
 '23512',
 '10206',
 '10190',
 '60493',
 '10174',
 '10180',
 '23499',
 '10150',
 '23463',
 '10153',
 '2810',
 '10165',
 '2817',
 '1500',
 '1509',
 '1514',
 '2852',
 '1534',
 '2887',
 '2886',
 '2896',
 '23670',
 '10362',
 '23647',
 '23658',
 '23659',
 '10318',
 '23636',
 '23635',
 '10329',
 '10320',
 '2908',
 '10298',
 '10270',
 '10273',
 '23585',
 '23588',
 '2920',
 '10276',
 '23597',
 '10285',
 '1605',
 '1616',
 '2946',
 '2954',
 '2958',
 '2956',
 '60528',
 '1635',
 '1633',
 '2961',
 '1643',
 '1647',
 '1666',
 '1662',
 '1677',
 '1676',
 '10491',
 '10493',
 '10494',
 '10489',
 '10451',
 '10450',
 '10434',
 '10398',
 '1738',
 '84617',
 '1759',
 '57019',
 '1788',
 '1786',
 '57048',
 '200081',
 '10513',
 '10525',
 '10523',
 '58533',
 '57215',
 '10589',
 '10557',
 '10559',
 '57192',
 '1802',
 '1829',
 '1831',
 '1848',
 '1846',
 '1845',
 '84722',
 '1861',
 '1870',
 '1891',
 '58472',
 '57149',
 '57147',
 '58478',
 '58497',
 '57178',
 '10652',
 '10668',
 '10641',
 '10644',
 '10617',
 '10610',
 '10606',
 '10695',
 '10670',
 '10682',
 '10681',
 '94239',
 '1906',
 '1950',
 '1958',
 '1956',
 '1978',
 '1983',
 '1981',
 '1994',
 '9019',
 '9016',
 '9053',
 '84890',
 '10776',
 '10775',
 '10782',
 '57406',
 '9093',
 '9097',
 '10765',
 '10730',
 '10732',
 '22794',
 '22796',
 '10797',
 '256364',
 '9112',
 '9124',
 '9128',
 '9126',
 '9133',
 '9134',
 '9143',
 '9170',
 '9183',
 '9181',
 '10898',
 '10892',
 '22889',
 '22883',
 '22887',
 '10857',
 '124583',
 '22841',
 '22809',
 '22823',
 '22827',
 '10845',
 '9212',
 '9217',
 '9221',
 '10810',
 '10813',
 '10818',
 '83743',
 '9246',
 '9267',
 '9261',
 '9276',
 '9270',
 '9275',
 '9289',
 '55008',
 '10972',
 '10973',
 '55012',
 '55011',
 '22934',
 '10954',
 '10953',
 '55033',
 '10969',
 '55038',
 '10962',
 '147179',
 '22908',
 '22926',
 '10915',
 '9375',
 '22905',
 '10921',
 '8050',
 '8061',
 '10904',
 '8091',
 '57761',
 '55111',
 '55127',
 '55129',
 '55148',
 '79090',
 '79094',
 '79080',
 '9448',
 '9455',
 '9467',
 '79006',
 '9488',
 '9491',
 '79071',
 '79073',
 '81533',
 '80204',
 '55256',
 '80212',
 '81544',
 '57804',
 '9517',
 '9519',
 '9531',
 '8204',
 '8202',
 '9533',
 '9552',
 '8243',
 '55179',
 '8270',
 '79143',
 '79170',
 '79174',
 '93487',
 '79187',
 '56654',
 '55324',
 '30001',
 '66008',
 '80347',
 '29082',
 '29083',
 '9641',
 '8312',
 '9637',
 '8321',
 '9653',
 '9650',
 '8324',
 '8318',
 '7015',
 '7016',
 '9670',
 '9686',
 '7027',
 '9688',
 '7020',
 '8349',
 '9697',
 '9695',
 '9690',
 '7043',
 '7048',
 '8396',
 '7077',
 '7074',
 '7088',
 '7082',
 '93594',
 '7099',
 '29103',
 '148022',
 '9712',
 '9710',
 '9702',
 '9703',
 '9709',
 '102',
 '9738',
 '128',
 '9761',
 '7105',
 '8440',
 '8446',
 '8444',
 '142',
 '7106',
 '154',
 '9797',
 '178',
 '7153',
 '7158',
 '7157',
 '7159',
 '8480',
 '7165',
 '7168',
 '80349',
 '9801',
 '9805',
 '9813',
 '9817',
 '9833',
 '207',
 '54205',
 '9842',
 '211',
 '8503',
 '8508',
 '8520',
 '9851',
 '9854',
 '55556',
 '226',
 '9847',
 '56889',
 '8518',
 '230',
 '9868',
 '8553',
 '8550',
 '9897',
 '8574',
 '8573',
 '8569',
 '7264',
 '291',
 '91137',
 '7296',
 '79643',
 '55699',
 '54386',
 '65057',
 '55604',
 '55608',
 '56940',
 '9903',
 '55620',
 '9917',
 '9918',
 '9915',
 '9924',
 '9928',
 '9926',
 '9943',
 '310',
 '8607',
 '323',
 '79600',
 '329',
 '9961',
 '332',
 '56997',
 '8624',
 '348',
 '351',
 '355',
 '7319',
 '9988',
 '8678',
 '6009',
 '7358',
 '387',
 '392',
 '7376',
 '6050',
 '7398',
 '56924',
 '65123',
 '80758',
 '375346',
 '80746',
 '54499',
 '55748',
 '55746',
 '79716',
 '8720',
 '427',
 '8731',
 '8726',
 '54438',
 '8727',
 '54442',
 '7416',
 '55793',
 '466',
 '481',
 '6117',
 '6119',
 '6118',
 '7466',
 '7485',
 '7494',
 '6182',
 '6184',
 '6193',
 '6195',
 '6194',
 '388650',
 '501',
 '54512',
 '55847',
 '8800',
 '8804',
 '8821',
 '533',
 '8826',
 '7511',
 '54541',
 '8835',
 '8837',
 '8851',
 '79850',
 '55893',
 '8870',
 '572',
 '8869',
 '7538',
 '8884',
 '581',
 '8878',
 '8895',
 '595',
 '596',
 '6251',
 '6253',
 '6275',
 '6284',
 '55818',
 '55825',
 '54505',
 '55837',
 '27095',
 '64080',
 '8900',
 '27032',
 '622',
 '8914',
 '637',
 '642',
 '644',
 '79921',
 '652',
 '664',
 '665',
 '79947',
 '8974',
 '670',
 '672',
 '53343',
 '6304',
 '8985',
 '54681',
 '79961',
 '8996',
 '695',
 '6342',
 '6347',
 '5018',
 '5019',
 '7690',
 '5048',
 '5054',
 '5058',
 '5050',
 '6390',
 '5096',
 '5092',
 '79902',
 '54623',
 '55958',
 '701',
 '727',
 '7750',
 '780',
 '5110',
 '5111',
 '6443',
 '5106',
 '5108',
 '6461',
 '6464',
 '5154',
 '6499',
 '54733',
 '27109',
 '29763',
 '808',
 '813',
 '823',
 '831',
 '835',
 '836',
 '840',
 '843',
 '847',
 '6500',
 '868',
 '6509',
 '873',
 '874',
 '7852',
 '54881',
 '7849',
 '890',
 '891',
 '896',
 '899',
 '5211',
 '7874',
 '7866',
 '7867',
 '5223',
 '5236',
 '5255',
 '5257',
 '5261',
 '6597',
 '6599',
 '54807',
 '5287',
 '5289',
 '5290',
 '54850',
 '27242',
 '27244',
 '29890',
 '30849',
 '902',
 '30836',
 '51097',
 '949',
 '7905',
 '958',
 '960',
 '965',
 '26054',
 '976',
 '6603',
 '26064',
 '983',
 '6616',
 '5300',
 '991',
 '993',
 '994',
 '51001',
 '998',
 '51005',
 '6622',
 '51015',
 '5321',
 '7982',
 '51021',
 '51024',
 '51026',
 '91949',
 '5331',
 '7994',
 '51031',
 '6657',
 '6659',
 '6676',
 '5355',
 '51053',
 '51056',
 '4016',
 '5347',
 '6696',
 '5366',
 '6697',
 '5357',
 '5359',
 '5373',
 '4043',
 '51070',
 '51071',
 '54915',
 '4067',
 '29928',
 '4088',
 '29937',
 '54957',
 '29911',
 '29916',
 '26036',
 '27346',
 '26020',
 '27336',
 '26001',
 '29978',
 '6709',
 '6714',
 '5423',
 '5427',
 '5440',
 '6772',
 '6774',
 '5438',
 '6777',
 '6790',
 '6793',
 '51160',
 '4125',
 '4144',
 '51170',
 '5467',
 '5468',
 '4154',
 '5480',
 '5498',
 '4172',
 '64422',
 '64429',
 '64428',
 '51116',
 '26136',
 '26128',
 '6804',
 '6810',
 '6812',
 '6813',
 '6839',
 '6832',
 '6850',
 '26292',
 '4200',
 '6856',
 '5525',
 '5529',
 '4208',
 '4216',
 '5547',
 '6894',
 '4232',
 '90861',
 '5566',
 '5580',
 '5583',
 '51282',
 '51293',
 '5588',
 '4282',
 '51203',
 '26227',
 '6908',
 '6909',
 '6919',
 '6915',
 '5607',
 '5601',
 '5603',
 '6944',
 '5613',
 '5627',
 '5641',
 '4303',
 '4312',
 '4313',
 '6990',
 '4331',
 '5654',
 '6988',
 '51375',
 '51382',
 '51385',
 '5696',
 '3033',
 '3028',
 '5699',
 '3066',
 '3091',
 '3098',
 '89910',
 '28969',
 '51335',
 '5708',
 '5710',
 '5715',
 '5716',
 '5720',
 '5721',
 '5743',
 '5747',
 '5770',
 '3108',
 '5782',
 '3122',
 '5777',
 '5792',
 '5796',
 '51495',
 '5788',
 '4482',
 '3156',
 '3162',
 '3157',
 '51422',
 '64746',
 '51465',
 '51466',
 '64781',
 '5827',
 '5829',
 '5831',
 '5836',
 '5873',
 '3206',
 '3202',
 '5867',
 '5880',
 '5883',
 '5891',
 '5889',
 '5898',
 '5899',
 '4582',
 '3251',
 '3280',
 '26511',
 '51569',
 '26520',
 '51599',
 '5909',
 '5900',
 '5927',
 '5921',
 '5925',
 '4609',
 '4605',
 '4616',
 '5971',
 '3303',
 '3300',
 '3308',
 '4638',
 '4651',
 '5982',
 '3315',
 '3312',
 '5993',
 '3329',
 '5985',
 '5986',
 '3337',
 '5997',
 '2017',
 '4690',
 '2042',
 '2037',
 '3385',
 '3383',
 '2048',
 '3398',
 '2065',
 '2064',
 '2063',
 '2058',
 '64943',
 '51635',
 '3416',
 '2109',
 '4780',
 '4783',
 '2115',
 '2113',
 '4775',
 '4776',
 '4791',
 '4792',
 '4793',
 '4794',
 '2131',
 '3454',
 '3486',
 '3482',
 '3480',
 '2146',
 '2185',
 '2184',
 '2195',
 '24149',
 '51719',
 '4817',
 '51742',
 '3508',
 '4836',
 '4850',
 '4846',
 '4860',
 '4851',
 '4864',
 '3551',
 '4891',
 '4893',
 '2222',
 '3553',
 '3566',
 '2264',
 '2263',
 '2274',
 '3597',
 '2288',
 '63874',
 '85236',
 '4925',
 '4927',
 '4931',
 '3611',
 '3628']

In [32]:
gene_id = {}

for name in df_landmark.columns.to_list():
    gene, id = name.split()
    id = id[1:-1]
    
    gene_id[gene] = id

gene_id

{'INSIG1': '3638',
 'FOXO3': '2309',
 'CDH3': '1001',
 'ORC1': '4998',
 'ITGAE': '3682',
 'CDK7': '1022',
 'FOS': '2353',
 'CDK6': '1021',
 'CDK4': '1019',
 'CDK2': '1017',
 'ITGB5': '3693',
 'CDKN2A': '1029',
 'CDKN1B': '1027',
 'CDKN1A': '1026',
 'FPGS': '2356',
 'CEBPD': '1052',
 'CEBPA': '1050',
 'CENPE': '1062',
 'MICALL1': '85377',
 'CETN3': '1070',
 'UBE2C': '11065',
 'DUSP14': '11072',
 'TOPBP1': '11073',
 'B4GAT1': '11041',
 'RBM34': '23029',
 'TENT4A': '11044',
 'WDTC1': '23038',
 'XPO7': '23039',
 'AKAP8L': '26993',
 'RAB31': '11031',
 'SPEN': '23013',
 'FBXO21': '23014',
 'RAB21': '23011',
 'SLC27A3': '11000',
 'KIF2C': '11004',
 'CCDC85B': '11007',
 'TLK2': '11011',
 'KDELR2': '11014',
 'MCUR1': '63933',
 'CDK19': '23097',
 'JUN': '3725',
 'TBC1D9B': '23061',
 'PRSS23': '11098',
 'RRP1B': '23076',
 'MYCBP2': '23077',
 'CHEK1': '1111',
 'KCNK1': '3775',
 'CHN1': '1123',
 'CIRBP': '1153',
 'HDGFL3': '50810',
 'COPS7A': '50813',
 'NSDHL': '50814',
 'ATP11B': '23200',
 'PRAF2': '11230',
 'JMJD6': '23210',
 'RRS1': '23212',
 'MPC2': '25874',
 'ARID5B': '84159',
 'POLG2': '11232',
 'CHEK2': '11200',
 'BACE2': '25825',
 'COG4': '25839',
 'SPDEF': '25803',
 'BAMBI': '25805',
 'SPRED2': '200734',
 'SLC2A6': '11182',
 'SNX13': '23161',
 'NISCH': '11188',
 'AARS1': '16',
 'ABCF1': '23',
 'ABL1': '25',
 'FCHO1': '23149',
 'DCUN1D4': '23142',
 'PSIP1': '11168',
 'ACAA1': '30',
 'ACAT2': '39',
 'ACLY': '47',
 'PKIG': '11142',
 'CORO1A': '11151',
 'MAST2': '23139',
 'GPATCH8': '23131',
 'FBXO7': '25793',
 'LSM6': '11157',
 'PWP1': '11137',
 'KIF5C': '3800',
 'KIT': '3815',
 'FUT1': '2523',
 'FYN': '2534',
 'GAA': '2548',
 'CLTC': '1213',
 'CLTB': '1212',
 'SLC37A4': '2542',
 'GABPB1': '2553',
 'KTN1': '3895',
 'GALE': '2582',
 'GAPDH': '2597',
 'COL4A1': '1282',
 'COL1A1': '1277',
 'TRIM2': '23321',
 'TSKU': '25987',
 'WASHC4': '23325',
 'USP22': '23326',
 'HDAC6': '10013',
 'TWF2': '11344',
 'WDR7': '23335',
 'JADE2': '23338',
 'ATMIN': '23300',
 'C2CD2': '25966',
 'DDX42': '11325',
 'TIPARP': '25976',
 'GNPDA1': '10007',
 'ECD': '11319',
 'CLIC4': '25932',
 'PNKP': '11284',
 'CAMSAP2': '23271',
 'CHP1': '11261',
 'PDS5A': '23244',
 'RRP12': '23223',
 'SYNE2': '23224',
 'LAMA3': '3909',
 'STMN1': '3925',
 'LBR': '3930',
 'HEBP1': '50865',
 'GATA3': '2625',
 'GATA2': '2624',
 'LGALS8': '3964',
 'LIG1': '3978',
 'LIPA': '3988',
 'GFPT1': '2673',
 'GHR': '2690',
 'CREB1': '1385',
 'RPL39L': '116832',
 'CRKL': '1399',
 'CRK': '1398',
 'SLC35A3': '23443',
 'TRAP1': '10131',
 'G3BP1': '10146',
 'KIF20A': '10112',
 'ARL4C': '10123',
 'SIRT3': '23410',
 'TSPAN3': '10099',
 'NUDCD3': '23386',
 'SMC4': '10051',
 'ARHGEF12': '23365',
 'PPP1R13B': '23368',
 'ABCC5': '10057',
 'DNM1L': '10059',
 'ABCB6': '10058',
 'RRP8': '23378',
 'PARP2': '10038',
 'MAMLD1': '10046',
 'DNAJB6': '10049',
 'GLI2': '2736',
 'GLRX': '2745',
 'CRYZ': '1429',
 'GNAI2': '2771',
 'GNAI1': '2770',
 'GNA11': '2767',
 'GNA15': '2769',
 'GNAS': '2778',
 'CSK': '1445',
 'CSNK2A2': '1459',
 'CSNK1E': '1454',
 'CSNK1A1': '1452',
 'CSRP1': '1465',
 'SLC35B1': '10237',
 'TIMM17B': '10245',
 'KAT6B': '23522',
 'NNT': '23530',
 'ADAT1': '23536',
 'MFSD10': '10227',
 'TRIB1': '10221',
 'SUZ12': '23512',
 'TRIM13': '10206',
 'TXNDC9': '10190',
 'FASTKD5': '60493',
 'SORBS3': '10174',
 'RBM6': '10180',
 'MACF1': '23499',
 'MBNL2': '10150',
 'ICMT': '23463',
 'CEBPZ': '10153',
 'SFN': '2810',
 'SLC25A13': '10165',
 'GPC1': '2817',
 'CTNND1': '1500',
 'CTSD': '1509',
 'CTSL': '1514',
 'GPER1': '2852',
 'CYB561': '1534',
 'GRB10': '2887',
 'GRB7': '2886',
 'GRN': '2896',
 'CEMIP2': '23670',
 'HMG20B': '10362',
 'ARFIP2': '23647',
 'LSM5': '23658',
 'PLA2G15': '23659',
 'TNIP1': '10318',
 'NUP62': '23636',
 'SSBP2': '23635',
 'RXYLT1': '10329',
 'IKZF1': '10320',
 'NR3C1': '2908',
 'PAK4': '10298',
 'AKAP8': '10270',
 'STUB1': '10273',
 'TMEM50A': '23585',
 'KLHDC2': '23588',
 'CXCL2': '2920',
 'NET1': '10276',
 'ACOT9': '23597',
 'SMNDC1': '10285',
 'DAG1': '1605',
 'DAXX': '1616',
 'GSTM2': '2946',
 'GSTZ1': '2954',
 'GTF2A2': '2958',
 'MSH6': '2956',
 'ELAC2': '60528',
 'DCTD': '1635',
 'DCK': '1633',
 'GTF2E2': '2961',
 'DDB2': '1643',
 'GADD45A': '1647',
 'DECR1': '1666',
 'DDX10': '1662',
 'DFFB': '1677',
 'DFFA': '1676',
 'CRTAP': '10491',
 'VAT1': '10493',
 'STK25': '10494',
 'LRRC41': '10489',
 'VAV3': '10451',
 'PPIE': '10450',
 'LYPLA1': '10434',
 'MYL9': '10398',
 'DLD': '1738',
 'TUBB6': '84617',
 'DNM1': '1759',
 'CIAPIN1': '57019',
 'DNMT3A': '1788',
 'DNMT1': '1786',
 'PLSCR3': '57048',
 'TXLNA': '200081',
 'APPBP2': '10513',
 'HYOU1': '10525',
 'CHERP': '10523',
 'SNX6': '58533',
 'THAP11': '57215',
 'DRAP1': '10589',
 'RPP38': '10557',
 'SLC35A1': '10559',
 'MCOLN1': '57192',
 'DPH2': '1802',
 'DSG2': '1829',
 'TSC22D3': '1831',
 'DUSP6': '1848',
 'DUSP4': '1846',
 'DUSP3': '1845',
 'PSRC1': '84722',
 'TOR1A': '1861',
 'E2F2': '1870',
 'ECH1': '1891',
 'SQOR': '58472',
 'LYRM1': '57149',
 'SCYL3': '57147',
 'ENOPH1': '58478',
 'PRUNE1': '58497',
 'ZMIZ1': '57178',
 'YKT6': '10652',
 'CGRRF1': '10668',
 'NPRL2': '10641',
 'IGF2BP2': '10644',
 'STAMBP': '10617',
 'ST6GALNAC2': '10610',
 'PAICS': '10606',
 'CNPY3': '10695',
 'RRAGA': '10670',
 'EBP': '10682',
 'GNB5': '10681',
 'H2AZ2': '94239',
 'EDN1': '1906',
 'EGF': '1950',
 'EGR1': '1958',
 'EGFR': '1956',
 'EIF4EBP1': '1978',
 'EIF5': '1983',
 'EIF4G1': '1981',
 'ELAVL1': '1994',
 'MPZL1': '9019',
 'SLC25A14': '9016',
 'MAP7': '9053',
 'ADO': '84890',
 'ARPP19': '10776',
 'POP4': '10775',
 'ZNF274': '10782',
 'ABHD6': '57406',
 'DNAJA3': '9093',
 'USP14': '9097',
 'KDM5B': '10765',
 'YME1L1': '10730',
 'TCFL5': '10732',
 'CASC3': '22794',
 'COG2': '22796',
 'MTHFD2': '10797',
 'EML3': '256364',
 'MTA1': '9112',
 'PDLIM1': '9124',
 'PRPF4': '9128',
 'SMC3': '9126',
 'CCNB2': '9133',
 'CCNE2': '9134',
 'SYNGR3': '9143',
 'LPAR2': '9170',
 'ZW10': '9183',
 'ARHGEF2': '9181',
 'CPSF4': '10898',
 'MALT1': '10892',
 'KHDC4': '22889',
 'CLSTN1': '22883',
 'FOXJ3': '22887',
 'PGRMC1': '10857',
 'CANT1': '124583',
 'RAB11FIP2': '22841',
 'ATF5': '22809',
 'MTF2': '22823',
 'PUF60': '22827',
 'CLPX': '10845',
 'AURKB': '9212',
 'VAPB': '9217',
 'NOLC1': '9221',
 'WASF3': '10810',
 'UTP14A': '10813',
 'FRS2': '10818',
 'GRWD1': '83743',
 'UBE2L6': '9246',
 'CYTH1': '9267',
 'MAPKAPK2': '9261',
 'COPB2': '9276',
 'ITGB1BP1': '9270',
 'BCL7B': '9275',
 'ADGRG1': '9289',
 'HERC6': '55008',
 'TMED10': '10972',
 'ASCC3': '10973',
 'PPP2R3C': '55012',
 'PIH1D1': '55011',
 'RPIA': '22934',
 'PDIA5': '10954',
 'TOMM34': '10953',
 'FKBP14': '55033',
 'EBNA1BP2': '10969',
 'CDCA4': '55038',
 'MLLT11': '10962',
 'WIPF2': '147179',
 'SACM1L': '22908',
 'ATF6': '22926',
 'TCERG1': '10915',
 'TM9SF2': '9375',
 'EPN2': '22905',
 'RNPS1': '10921',
 'PDHX': '8050',
 'FOSL1': '8061',
 'BLCAP': '10904',
 'HMGA2': '8091',
 'TRIB3': '57761',
 'PLEKHJ1': '55111',
 'HEATR1': '55127',
 'ANO10': '55129',
 'UBR7': '55148',
 'TRAPPC6A': '79090',
 'CHAC1': '79094',
 'CCDC86': '79080',
 'MAP4K4': '9448',
 'HOMER2': '9455',
 'SH3BP5': '9467',
 'METRN': '79006',
 'PIGB': '9488',
 'PSMF1': '9491',
 'ELOVL6': '79071',
 'TMEM109': '79073',
 'ITFG1': '81533',
 'FBXO11': '80204',
 'ADI1': '55256',
 'CCDC92': '80212',
 'GDPD5': '81544',
 'POLD4': '57804',
 'SPTLC2': '9517',
 'TBPL1': '9519',
 'BAG3': '9531',
 'NRIP1': '8204',
 'NCOA3': '8202',
 'POLR1C': '9533',
 'SPAG7': '9552',
 'SMC1A': '8243',
 'FAIM': '55179',
 'LAGE3': '8270',
 'MBOAT7': '79143',
 'PRR15L': '79170',
 'CRELD2': '79174',
 'MAPK1IP1L': '93487',
 'FSD1': '79187',
 'NPDC1': '56654',
 'ABCF3': '55324',
 'ERO1A': '30001',
 'TRAK2': '66008',
 'COASY': '80347',
 'CHMP4A': '29082',
 'GTPBP8': '29083',
 'IKBKE': '9641',
 'AXIN1': '8312',
 'FEZ2': '9637',
 'FZD1': '8321',
 'HS2ST1': '9653',
 'MTFR1': '9650',
 'FZD7': '8324',
 'CDC45': '8318',
 'TERT': '7015',
 'TESK1': '7016',
 'IPO13': '9670',
 'VGLL4': '9686',
 'TFDP1': '7027',
 'NUP93': '9688',
 'TFAP2A': '7020',
 'H2BC21': '8349',
 'TRAM2': '9697',
 'EDEM1': '9695',
 'UBE3C': '9690',
 'TGFB3': '7043',
 'TGFBR2': '7048',
 'PIP4K2B': '8396',
 'TIMP2': '7077',
 'TIAM1': '7074',
 'TLE1': '7088',
 'TJP1': '7082',
 'TBC1D31': '93594',
 'TLR4': '7099',
 'DNAJC15': '29103',
 'TICAM1': '148022',
 'USP6NL': '9712',
 'GARRE1': '9710',
 'CEP57': '9702',
 'KIAA0100': '9703',
 'HERPUD1': '9709',
 'ADAM10': '102',
 'CCP110': '9738',
 'ADH5': '128',
 'MLEC': '9761',
 'TSPAN6': '7105',
 'NCK2': '8440',
 'DUSP11': '8446',
 'DYRK3': '8444',
 'PARP1': '142',
 'TSPAN4': '7106',
 'ADRB2': '154',
 'TATDN2': '9797',
 'AGL': '178',
 'TOP2A': '7153',
 'TP53BP1': '7158',
 'TP53': '7157',
 'TP53BP2': '7159',
 'RAE1': '8480',
 'TPD52L2': '7165',
 'TPM1': '7168',
 'WDR61': '80349',
 'MRPL19': '9801',
 'SCRN1': '9805',
 'EFCAB14': '9813',
 'KEAP1': '9817',
 'MELK': '9833',
 'AKT1': '207',
 'CYCS': '54205',
 'PLEKHM1': '9842',
 'ALAS1': '211',
 'PIK3R3': '8503',
 'NIPSNAP1': '8508',
 'HAT1': '8520',
 'KIAA0753': '9851',
 'C2CD2L': '9854',
 'ENOSF1': '55556',
 'ALDOA': '226',
 'C2CD5': '9847',
 'TM9SF3': '56889',
 'ELP1': '8518',
 'ALDOC': '230',
 'TOMM70': '9868',
 'BHLHE40': '8553',
 'MAPKAPK5': '8550',
 'WASHC5': '9897',
 'AKR7A2': '8574',
 'CASK': '8573',
 'MKNK1': '8569',
 'GFUS': '7264',
 'SLC25A4': '291',
 'SLC25A46': '91137',
 'TXNRD1': '7296',
 'CHMP6': '79643',
 'IARS2': '55699',
 'TERF2IP': '54386',
 'ACD': '65057',
 'CARMIL1': '55604',
 'ANKRD10': '55608',
 'DUSP22': '56940',
 'KLHL21': '9903',
 'STAP2': '55620',
 'FAM20B': '9917',
 'NCAPD2': '9918',
 'ARNT2': '9915',
 'PAN2': '9924',
 'KIF14': '9928',
 'LPGAT1': '9926',
 'OXSR1': '9943',
 'ANXA7': '310',
 'RUVBL1': '8607',
 'APBB2': '323',
 'TCTN1': '79600',
 'BIRC2': '329',
 'MVP': '9961',
 'BIRC5': '332',
 'COQ8A': '56997',
 'PSMG1': '8624',
 'APOE': '348',
 'APP': '351',
 'FAS': '355',
 'UBE2A': '7319',
 'DMTF1': '9988',
 'BECN1': '8678',
 'RHEB': '6009',
 'UGDH': '7358',
 'RHOA': '387',
 'ARHGAP1': '392',
 'NR1H2': '7376',
 'RNH1': '6050',
 'USP1': '7398',
 'PAK6': '56924',
 'INTS3': '65123',
 'PRR7': '80758',
 'STIMATE': '375346',
 'TSEN2': '80746',
 'TMCO1': '54499',
 'CNDP2': '55748',
 'NUP133': '55746',
 'NPEPL1': '79716',
 'MBTPS1': '8720',
 'ASAH1': '427',
 'RNMT': '8731',
 'EED': '8726',
 'GFOD1': '54438',
 'CTNNAL1': '8727',
 'KCTD5': '54442',
 'VDAC1': '7416',
 'MINDY1': '55793',
 'ATF1': '466',
 'ATP1B1': '481',
 'RPA1': '6117',
 'RPA3': '6119',
 'RPA2': '6118',
 'WFS1': '7466',
 'GET1': '7485',
 'XBP1': '7494',
 'MRPL12': '6182',
 'RPN1': '6184',
 'RPS5': '6193',
 'RPS6KA1': '6195',
 'RPS6': '6194',
 'DIPK1A': '388650',
 'ALDH7A1': '501',
 'EXOSC4': '54512',
 'CISD1': '55847',
 'PEX11A': '8800',
 'CREG1': '8804',
 'INPP4B': '8821',
 'ATP6V0B': '533',
 'IQGAP1': '8826',
 'XPNPEP1': '7511',
 'DDIT4': '54541',
 'SOCS2': '8835',
 'CFLAR': '8837',
 'CDK5R1': '8851',
 'TLCD3A': '79850',
 'ZNF395': '55893',
 'IER3': '8870',
 'BAD': '572',
 'ST3GAL5': '8869',
 'ZFP36': '7538',
 'SLC5A6': '8884',
 'BAX': '581',
 'SQSTM1': '8878',
 'CPNE3': '8895',
 'CCND1': '595',
 'BCL2': '596',
 'RSU1': '6251',
 'RTN2': '6253',
 'S100A4': '6275',
 'S100A13': '6284',
 'KDM3A': '55818',
 'PECR': '55825',
 'DHX29': '54505',
 'EAPP': '55837',
 'TRAPPC3': '27095',
 'RBKS': '64080',
 'CCNA1': '8900',
 'ATP2C1': '27032',
 'BDH1': '622',
 'TIMELESS': '8914',
 'BID': '637',
 'BLMH': '642',
 'BLVRA': '644',
 'TCEAL4': '79921',
 'BMP4': '652',
 'BNIP3': '664',
 'BNIP3L': '665',
 'DHDDS': '79947',
 'P4HA2': '8974',
 'BPHL': '670',
 'BRCA1': '672',
 'NUDT9': '53343',
 'SATB1': '6304',
 'PLOD3': '8985',
 'P4HTM': '54681',
 'DENND2D': '79961',
 'NOL3': '8996',
 'BTK': '695',
 'SCP2': '6342',
 'CCL2': '6347',
 'OXA1L': '5018',
 'OXCT1': '5019',
 'ZNF131': '7690',
 'PAFAH1B1': '5048',
 'SERPINE1': '5054',
 'PAK1': '5058',
 'PAFAH1B3': '5050',
 'SDHB': '6390',
 'PCCB': '5096',
 'PCBD1': '5092',
 'NUP85': '79902',
 'PAF1': '54623',
 'KLHL9': '55958',
 'BUB1B': '701',
 'C5': '727',
 'ZMYM2': '7750',
 'DDR1': '780',
 'PCMT1': '5110',
 'PCNA': '5111',
 'SGCB': '6443',
 'PCK2': '5106',
 'PCM1': '5108',
 'SHB': '6461',
 'SHC1': '6464',
 'PDGFA': '5154',
 'SKIV2L': '6499',
 'SLC35F2': '54733',
 'DMAC2L': '27109',
 'PACSIN3': '29763',
 'CALM3': '808',
 'CALU': '813',
 'CAPN1': '823',
 'CAST': '831',
 'CASP2': '835',
 'CASP3': '836',
 'CASP7': '840',
 'CASP10': '843',
 'CAT': '847',
 'SKP1': '6500',
 'CBLB': '868',
 'SLC1A4': '6509',
 'CBR1': '873',
 'CBR3': '874',
 'CXCR4': '7852',
 'TEX10': '54881',
 'PAX8': '7849',
 'CCNA2': '890',
 'CCNB1': '891',
 'CCND3': '896',
 'CCNF': '899',
 'PFKL': '5211',
 'USP7': '7874',
 'IFRD2': '7866',
 'MAPKAPK3': '7867',
 'PGAM1': '5223',
 'PGM1': '5236',
 'PHKA1': '5255',
 'PHKB': '5257',
 'PHKG2': '5261',
 'SMARCA4': '6597',
 'SMARCC1': '6599',
 'ZNF586': '54807',
 'PIK3C2B': '5287',
 'PIK3C3': '5289',
 'PIK3CA': '5290',
 'FBXL12': '54850',
 'TNFRSF21': '27242',
 'SESN1': '27244',
 'RBM15B': '29890',
 'PIK3R4': '30849',
 'CCNH': '902',
 'DNTTIP2': '30836',
 'SCCPDH': '51097',
 'SCARB1': '949',
 'REEP5': '7905',
 'CD40': '958',
 'CD44': '960',
 'CD58': '965',
 'SENP6': '26054',
 'ADGRE5': '976',
 'SMARCD2': '6603',
 'RAI14': '26064',
 'CDK1': '983',
 'SNAP25': '6616',
 'PIN1': '5300',
 'CDC20': '991',
 'CDC25A': '993',
 'CDC25B': '994',
 'MTERF3': '51001',
 'CDC42': '998',
 'AMDHD2': '51005',
 'SNCA': '6622',
 'ISOC1': '51015',
 'PLA2G4A': '5321',
 'ST7': '7982',
 'MRPS16': '51021',
 'FIS1': '51024',
 'GOLT1B': '51026',
 'COG7': '91949',
 'PLCB3': '5331',
 'KAT6A': '7994',
 'GLOD4': '51031',
 'SOX2': '6657',
 'SOX4': '6659',
 'SPAG4': '6676',
 'PLP2': '5355',
 'GMNN': '51053',
 'LAP3': '51056',
 'LOXL1': '4016',
 'PLK1': '5347',
 'SPP1': '6696',
 'PMAIP1': '5366',
 'SPR': '6697',
 'PLS1': '5357',
 'PLSCR1': '5359',
 'PMM2': '5373',
 'LRPAP1': '4043',
 'NOSIP': '51070',
 'DERA': '51071',
 'YTHDF1': '54915',
 'LYN': '4067',
 'TIMM22': '29928',
 'SMAD3': '4088',
 'NENF': '29937',
 'TXNL4B': '54957',
 'HOOK2': '29911',
 'SNX11': '29916',
 'ZNF451': '26036',
 'TMEM97': '27346',
 'LRP10': '26020',
 'HTATSF1': '27336',
 'RNF167': '26001',
 'UBQLN2': '29978',
 'SPTAN1': '6709',
 'SRC': '6714',
 'POLB': '5423',
 'POLE2': '5427',
 'POLR2K': '5440',
 'STAT1': '6772',
 'STAT3': '6774',
 'POLR2I': '5438',
 'STAT5B': '6777',
 'AURKA': '6790',
 'STK10': '6793',
 'VPS28': '51160',
 'MAN2B1': '4125',
 'MAT2A': '4144',
 'HSD17B11': '51170',
 'PPARD': '5467',
 'PPARG': '5468',
 'MBNL1': '4154',
 'PPIC': '5480',
 'PPOX': '5498',
 'MCM3': '4172',
 'ATG3': '64422',
 'ZDHHC6': '64429',
 'CIAO3': '64428',
 'MRPS2': '51116',
 'TES': '26136',
 'KIFBP': '26128',
 'STX1A': '6804',
 'STX4': '6810',
 'STXBP1': '6812',
 'STXBP2': '6813',
 'SUV39H1': '6839',
 'SUPV3L1': '6832',
 'SYK': '6850',
 'MYCBP': '26292',
 'ME2': '4200',
 'SYPL1': '6856',
 'PPP2R5A': '5525',
 'PPP2R5E': '5529',
 'MEF2C': '4208',
 'MAP3K4': '4216',
 'PRCP': '5547',
 'TARBP1': '6894',
 'MEST': '4232',
 'JPT2': '90861',
 'PRKACA': '5566',
 'PRKCD': '5580',
 'PRKCH': '5583',
 'SCAND1': '51282',
 'CD320': '51293',
 'PRKCQ': '5588',
 'MIF': '4282',
 'NUSAP1': '51203',
 'PHGDH': '26227',
 'TBP': '6908',
 'TBX2': '6909',
 'TCEA2': '6919',
 'TBXA2R': '6915',
 'MAP2K5': '5607',
 'MAPK9': '5601',
 'MAPK13': '5603',
 'VPS72': '6944',
 'PRKX': '5613',
 'PROS1': '5627',
 'LGMN': '5641',
 'FOXO4': '4303',
 'MMP1': '4312',
 'MMP2': '4313',
 'DYNLT3': '6990',
 'MNAT1': '4331',
 'HTRA1': '5654',
 'TCTA': '6988',
 'SNX7': '51375',
 'ATP6V1D': '51382',
 'ZNF589': '51385',
 'PSMB8': '5696',
 'HADH': '3033',
 'HSD17B10': '3028',
 'PSMB10': '5699',
 'HDAC2': '3066',
 'HIF1A': '3091',
 'HK1': '3098',
 'UBE3B': '89910',
 'BZW2': '28969',
 'NGRN': '51335',
 'PSMD2': '5708',
 'PSMD4': '5710',
 'PSMD9': '5715',
 'PSMD10': '5716',
 'PSME1': '5720',
 'PSME2': '5721',
 'PTGS2': '5743',
 'PTK2': '5747',
 'PTPN1': '5770',
 'HLA-DMA': '3108',
 'PTPN12': '5782',
 'HLA-DRA': '3122',
 'PTPN6': '5777',
 'PTPRF': '5792',
 'PTPRK': '5796',
 'HACD3': '51495',
 'PTPRC': '5788',
 'MSRA': '4482',
 'HMGCR': '3156',
 'HMOX1': '3162',
 'HMGCS1': '3157',
 'PRKAG2': '51422',
 'ACBD3': '64746',
 'UBE2J1': '51465',
 'EVL': '51466',
 'CERK': '64781',
 'PXMP2': '5827',
 'PXN': '5829',
 'PYCR1': '5831',
 'PYGL': '5836',
 'RAB27A': '5873',
 'HOXA10': '3206',
 'HOXA5': '3202',
 'RAB4A': '5867',
 'RAC2': '5880',
 'RAD9A': '5883',
 'MOK': '5891',
 'RAD51C': '5889',
 'RALA': '5898',
 'RALB': '5899',
 'MUC1': '4582',
 'HPRT1': '3251',
 'HES1': '3280',
 'CHIC2': '26511',
 'UFM1': '51569',
 'TIMM9': '26520',
 'LSR': '51599',
 'RAP1GAP': '5909',
 'RALGDS': '5900',
 'KDM5A': '5927',
 'RASA1': '5921',
 'RB1': '5925',
 'MYC': '4609',
 'MYBL2': '4605',
 'GADD45B': '4616',
 'RELB': '5971',
 'HSPA1A': '3303',
 'DNAJB2': '3300',
 'HSPA4': '3308',
 'MYLK': '4638',
 'MYO10': '4651',
 'RFC2': '5982',
 'HSPB1': '3315',
 'HSPA8': '3312',
 'RFX5': '5993',
 'HSPD1': '3329',
 'RFC5': '5985',
 'RFNG': '5986',
 'DNAJB1': '3337',
 'RGS2': '5997',
 'CTTN': '2017',
 'NCK1': '4690',
 'EPHA3': '2042',
 'EPB41L2': '2037',
 'ICAM3': '3385',
 'ICAM1': '3383',
 'EPHB2': '2048',
 'ID2': '3398',
 'ERBB3': '2065',
 'ERBB2': '2064',
 'NR2F6': '2063',
 'EPRS1': '2058',
 'NT5DC2': '64943',
 'DHRS7': '51635',
 'IDE': '3416',
 'ETFB': '2109',
 'NFE2L2': '4780',
 'NFIL3': '4783',
 'ETV1': '2115',
 'ETS1': '2113',
 'NFATC3': '4775',
 'NFATC4': '4776',
 'NFKB2': '4791',
 'NFKBIA': '4792',
 'NFKBIB': '4793',
 'NFKBIE': '4794',
 'EXT1': '2131',
 'IFNAR1': '3454',
 'IGFBP3': '3486',
 'IGF2R': '3482',
 'IGF1R': '3480',
 'EZH2': '2146',
 'PTK2B': '2185',
 'FAH': '2184',
 'FAT1': '2195',
 'ZNF318': '24149',
 'CAB39': '51719',
 'NIT1': '4817',
 'ARID4B': '51742',
 'IGHMBP2': '3508',
 'NMT1': '4836',
 'CNOT4': '4850',
 'NOS3': '4846',
 'PNP': '4860',
 'NOTCH1': '4851',
 'NPC1': '4864',
 'IKBKB': '3551',
 'SLC11A2': '4891',
 'NRAS': '4893',
 'FDFT1': '2222',
 'IL1B': '3553',
 'IL4R': '3566',
 'FGFR4': '2264',
 'FGFR2': '2263',
 'FHL2': '2274',
 'IL13RA1': '3597',
 'FKBP4': '2288',
 'ABHD4': '63874',
 'H2BC12': '85236',
 'NUCB2': '4925',
 'NUP88': '4927',
 'NVL': '4931',
 'ILK': '3611',
 'INPP1': '3628'}

In [38]:
len(gene_id)

978

In [33]:
ppi_df

       protein_id_a protein_id_b  score  source
0              ARF5        ACAP1  0.825  STRING
1              ARF5         COPA  0.718  STRING
2              ARF5    RAB11FIP3  0.952  STRING
3              ARF5        COPB2  0.752  STRING
4              ARF5         COPE  0.795  STRING
...             ...          ...    ...     ...
473855         LDB1        ZFPM1  0.942  STRING
473856         LDB1         LHX4  0.944  STRING
473857         RFX7         RFX5  0.780  STRING
473858         RFX7       RFXANK  0.978  STRING
473859         RFX7       ANKRA2  0.973  STRING

[473860 rows x 4 columns]

In [42]:
gene_id_list = [gene_id[gene] for gene in ppi_df['protein_id_a'].unique().tolist() if gene in gene_id.keys()]
len(gene_id_list)

939

In [54]:
landmark_gene_to_id = landmarks[['Entrez ID', 'Symbol']].set_index('Symbol').to_dict()

gene_to_id = gene_id | landmark_gene_to_id
len(gene_to_id)

979

In [56]:
gene_id_list = [gene_to_id[gene] for gene in ppi_df['protein_id_a'].unique().tolist() if gene in gene_to_id.keys()]
len(gene_id_list)

939

In [58]:
ppi_df = pd.read_csv('/Users/zijiexu/GEMS-LAB/jumpstart_bundle 2/data/protein_features/string_ppi_entrez.csv')
ppi_df

        entrez_id_a  entrez_id_b symbol_a   symbol_b  score  source
0               381         9744     ARF5      ACAP1  0.825  STRING
1               381         1314     ARF5       COPA  0.718  STRING
2               381         9727     ARF5  RAB11FIP3  0.952  STRING
3               381         9276     ARF5      COPB2  0.752  STRING
4               381        11316     ARF5       COPE  0.795  STRING
...             ...          ...      ...        ...    ...     ...
437987         8861       161882     LDB1      ZFPM1  0.942  STRING
437988         8861        89884     LDB1       LHX4  0.944  STRING
437989        64864         5993     RFX7       RFX5  0.780  STRING
437990        64864         8625     RFX7     RFXANK  0.978  STRING
437991        64864        57763     RFX7     ANKRA2  0.973  STRING

[437992 rows x 6 columns]

In [72]:
common_int = {int(x) for x in common}
len(common_int)

978

In [95]:
ppi_filtered = ppi_df[
    ppi_df["entrez_id_a"].isin(common_int) |
    ppi_df["entrez_id_b"].isin(common_int)
]

ppi_filtered

        entrez_id_a  entrez_id_b symbol_a symbol_b  score  source
3               381         9276     ARF5    COPB2  0.752  STRING
8               381         9267     ARF5    CYTH1  0.765  STRING
21              381         1029     ARF5   CDKN2A  0.760  STRING
23              381        23647     ARF5   ARFIP2  0.842  STRING
32             4074         3482     M6PR    IGF2R  0.991  STRING
...             ...          ...      ...      ...    ...     ...
437940         8861        23635     LDB1    SSBP2  0.997  STRING
437954         8861         2624     LDB1    GATA2  0.994  STRING
437957         8861         2625     LDB1    GATA3  0.932  STRING
437986         8861         7088     LDB1     TLE1  0.914  STRING
437989        64864         5993     RFX7     RFX5  0.780  STRING

[87088 rows x 6 columns]

In [96]:
print(len(ppi_filtered['entrez_id_a'].unique()))
print(len(common_int))

print(common_int)
print(set(ppi_filtered['entrez_id_a'].unique().tolist()))

len(common_int - set(ppi_filtered['entrez_id_a'].unique().tolist()))

9396
978
{2048, 51203, 10245, 8202, 2058, 8204, 2063, 2064, 2065, 16, 23, 25, 55324, 4125, 10270, 30, 94239, 10273, 200734, 79902, 10276, 6182, 39, 6184, 10285, 47, 4144, 6193, 79921, 6195, 6194, 8243, 10298, 4154, 2109, 57406, 2113, 2115, 79947, 4172, 10318, 8270, 10320, 51282, 2131, 10329, 79961, 51293, 53343, 116832, 2146, 102, 4200, 6251, 6253, 4208, 30836, 4216, 8312, 10362, 8318, 128, 30849, 8321, 6275, 8324, 51335, 2184, 2185, 4232, 6284, 142, 2195, 154, 8349, 10398, 6304, 2222, 51375, 178, 51382, 51385, 4282, 84159, 10434, 6342, 6347, 8396, 207, 4303, 10450, 10451, 211, 2263, 4312, 4313, 2264, 51422, 2274, 226, 230, 4331, 2288, 6390, 8440, 10489, 10491, 8444, 10493, 10494, 8446, 55556, 2309, 51465, 51466, 22794, 22796, 10513, 22809, 10523, 10525, 8480, 291, 22823, 51495, 28969, 6443, 22827, 2353, 55604, 2356, 310, 8503, 55608, 22841, 8508, 10557, 6461, 10559, 6464, 323, 55620, 8518, 8520, 329, 332, 80204, 80212, 348, 10589, 351, 6499, 6500, 22883, 8550, 355, 22887, 22889, 8553, 256364, 6509, 10606, 26993, 10610, 51569, 10617, 22905, 8569, 22908, 8573, 8574, 4482, 387, 63874, 392, 22926, 51599, 10641, 55699, 10644, 22934, 27032, 29082, 29083, 10652, 8607, 57761, 427, 10668, 10670, 29103, 8624, 9448, 51635, 10681, 10682, 63933, 55746, 55748, 6597, 10695, 6599, 6603, 57804, 466, 27095, 6616, 66008, 80347, 2523, 80349, 6622, 481, 23011, 23013, 2534, 23014, 4582, 8678, 10730, 27109, 10732, 2542, 55793, 2548, 23029, 501, 2553, 4605, 23038, 23039, 4609, 6657, 6659, 51719, 4616, 55818, 10765, 8720, 55825, 6676, 533, 23061, 10775, 10776, 2582, 8726, 8731, 8727, 55837, 4638, 51742, 10782, 23076, 2597, 23077, 55847, 6696, 6697, 4651, 10797, 375346, 6709, 148022, 23097, 10810, 6714, 572, 10813, 2624, 2625, 10818, 581, 64080, 4690, 595, 596, 55893, 23131, 10845, 8800, 23139, 8804, 23142, 10857, 27242, 27244, 23149, 622, 2673, 6772, 8821, 6774, 23161, 6777, 8826, 637, 642, 2690, 644, 8837, 6790, 8835, 6793, 84617, 10892, 652, 10898, 8851, 6804, 55958, 664, 665, 6810, 10904, 6812, 6813, 670, 672, 23200, 10915, 8869, 8870, 4775, 4776, 10921, 23210, 23212, 4780, 8878, 4783, 2736, 6832, 8884, 6839, 23223, 2745, 4793, 4791, 4794, 695, 23224, 8895, 701, 4792, 6850, 8900, 27336, 10953, 10954, 6856, 23244, 2767, 4817, 2770, 27346, 10962, 2771, 2769, 727, 8914, 10969, 2778, 10972, 10973, 4836, 23271, 90861, 4846, 6894, 84722, 4851, 4850, 11000, 2810, 6908, 4860, 11004, 11007, 4864, 2817, 6909, 6915, 23300, 11011, 11014, 6919, 780, 8974, 11031, 8985, 23321, 4891, 23325, 4893, 23326, 6944, 11041, 8996, 11044, 2852, 23335, 808, 23338, 813, 823, 9016, 11065, 9019, 4925, 4927, 11072, 831, 11073, 835, 836, 4931, 2886, 2887, 23368, 23365, 840, 843, 6988, 6990, 847, 2896, 23378, 23386, 11098, 2908, 9053, 868, 7015, 2920, 7016, 874, 80746, 7020, 873, 23410, 7027, 80758, 890, 891, 896, 11137, 2946, 7043, 899, 9093, 11142, 4998, 902, 9097, 2954, 7048, 2956, 2958, 11151, 2961, 23443, 11157, 9112, 5018, 5019, 84890, 11168, 7074, 9124, 7077, 9126, 23463, 64422, 9128, 7082, 64428, 9133, 11182, 64429, 7088, 9134, 11188, 949, 9143, 5048, 5050, 7099, 54205, 5054, 958, 960, 7105, 7106, 5058, 11200, 965, 23499, 976, 9170, 3028, 983, 23512, 3033, 9181, 11230, 9183, 11232, 993, 994, 23522, 991, 5092, 998, 5096, 1001, 23530, 23536, 7153, 5106, 5108, 7157, 5110, 7159, 5111, 1017, 3066, 1019, 9212, 7165, 1022, 11261, 7168, 1021, 1026, 1027, 91137, 9221, 1029, 9217, 3091, 11284, 1050, 3098, 1052, 9246, 23585, 5154, 23588, 3108, 1062, 9261, 23597, 1070, 3122, 9267, 9270, 11319, 9275, 9276, 11325, 29763, 9289, 60493, 11344, 23635, 3156, 3157, 23636, 1111, 3162, 5211, 23647, 7264, 1123, 5223, 58472, 23658, 23659, 58478, 60528, 54386, 5236, 23670, 7296, 58497, 3202, 1153, 3206, 5255, 5257, 5261, 7319, 79006, 9375, 58533, 54438, 5287, 5289, 5290, 54442, 7158, 3251, 5300, 1212, 1213, 7358, 25793, 29890, 5321, 25803, 25805, 7376, 3280, 5331, 29911, 29916, 79071, 25825, 79073, 54499, 3300, 5347, 7398, 3303, 29928, 79080, 64746, 5355, 3308, 5357, 54505, 5359, 3312, 25839, 79090, 3315, 85236, 54512, 79094, 9455, 7416, 5366, 29937, 9467, 5373, 1277, 3329, 1282, 3337, 64781, 54541, 9488, 25874, 9491, 29978, 79143, 7466, 9517, 9519, 5423, 30001, 93487, 5427, 3383, 3385, 9531, 7485, 5438, 9533, 5440, 79170, 7494, 79174, 3398, 25932, 56654, 9552, 79187, 7511, 3416, 5467, 5468, 54623, 5480, 1385, 25966, 7538, 1398, 1399, 25976, 5498, 3454, 85377, 25987, 26001, 200081, 5525, 1429, 3480, 54681, 3482, 93594, 5529, 3486, 26020, 1445, 9637, 9641, 5547, 1452, 1454, 64943, 9650, 1459, 26036, 9653, 3508, 1465, 5566, 26054, 9670, 5580, 54733, 5583, 26064, 5588, 9686, 9688, 9690, 1500, 3551, 9695, 5601, 3553, 9697, 5603, 1509, 9702, 9703, 5607, 1514, 9709, 3566, 5613, 9712, 9710, 5627, 1534, 5641, 9738, 7690, 3597, 26128, 5654, 54807, 26136, 3611, 9761, 65057, 388650, 3628, 3638, 56889, 5696, 54850, 5699, 9797, 7750, 1605, 9801, 5708, 9805, 5710, 1616, 5715, 5716, 24149, 9813, 5720, 5721, 9817, 56924, 1633, 54881, 65123, 1635, 3682, 9833, 1643, 56940, 3693, 1647, 5743, 9842, 5747, 26227, 9847, 50810, 9851, 81533, 50814, 1662, 9854, 50813, 1666, 54915, 81544, 5770, 1676, 1677, 3725, 9868, 5777, 5782, 5788, 5792, 5796, 56997, 124583, 7849, 9897, 7852, 54957, 9903, 50865, 26292, 7866, 7867, 9915, 9917, 9918, 3775, 57019, 7874, 5827, 9924, 5829, 9926, 5831, 9928, 1738, 5836, 9943, 57048, 3800, 1759, 55008, 7905, 55011, 55012, 3815, 9961, 5867, 147179, 79600, 5873, 5880, 55033, 1786, 5883, 1788, 55038, 5889, 5891, 9988, 1802, 5899, 5900, 5898, 5909, 10007, 79643, 10013, 83743, 5921, 5925, 1829, 5927, 1831, 91949, 7982, 1845, 89910, 3895, 1848, 1846, 7994, 10038, 51001, 57149, 10046, 51005, 57147, 10049, 10051, 1861, 3909, 51015, 55111, 10057, 10058, 10059, 51021, 1870, 51024, 51026, 5971, 3925, 51031, 55127, 55129, 57178, 3930, 5982, 5985, 5986, 1891, 79716, 57192, 5993, 55148, 51053, 5997, 51056, 8050, 10099, 1906, 6009, 3964, 8061, 51070, 57215, 10112, 51071, 3978, 10123, 55179, 26511, 10131, 3988, 26520, 51097, 8091, 1950, 6050, 10146, 1956, 10150, 1958, 10153, 51116, 4016, 10165, 1978, 1981, 10174, 1983, 10180, 1994, 4043, 10190, 55256, 51160, 10206, 2017, 51170, 4067, 6117, 6118, 6119, 79850, 10221, 10227, 2037, 4088, 2042, 10237}

64

In [71]:
ppi_filtered.groupby('entrez_id_b').count()

             entrez_id_a  symbol_a  symbol_b  score  source
entrez_id_b
16                     5         5         5      5       5
23                     2         2         2      2       2
25                    33        33        33     33      33
30                     9         9         9      9       9
39                     8         8         8      8       8
...                  ...       ...       ...    ...     ...
116832                 3         3         3      3       3
124583                 1         1         1      1       1
147179                 3         3         3      3       3
148022                 4         4         4      4       4
200081                 2         2         2      2       2

[748 rows x 5 columns]

In [109]:
cell_line_embeddings = pd.read_csv("/Users/zijiexu/GEMS-LAB/MD-syn-GEMS/CCLE_expression.csv")
landmarks = pd.read_csv('/Users/zijiexu/GEMS-LAB/MD-syn-GEMS/landmark_genes.txt', sep="\t")
landmark_ids = list(landmarks["Entrez ID"])
landmark_ids = [str(id) for id in landmark_ids]

id_to_col = {}

for col in cell_line_embeddings.columns:
    id = col.split()[-1][1:-1]
    id_to_col[id] = col

col_names = []
for id in landmark_ids:
    col_names.append(id_to_col[id])
col_names.append('Unnamed: 0')


cell_line_embeddings = cell_line_embeddings[col_names]
cell_line_embeddings.columns = [col.split()[-1][1:-1] for col in cell_line_embeddings.columns]
cell_line_embeddings = cell_line_embeddings.rename(columns={"": "cell_line"})
cell_line_embeddings = cell_line_embeddings.set_index('cell_line')
cell_line_embeddings

,3638,2309,1001,4998,3682,1022,2353,1021,1019,1017,...,2274,3597,2288,63874,85236,4925,4927,4931,3611,3628
cell_line,,,,,,,,,,,,,,,,,,,,,
ACH-001113,5.791814,3.078951,0.097611,3.981853,6.582857,5.844737,9.608920,3.785551,8.143077,6.265849,...,4.707083,4.755422,6.632559,6.484460,7.925406,5.989366,6.017031,5.069960,4.966246,2.462052
ACH-001289,6.553821,3.068671,0.250962,3.244887,5.585263,5.726286,5.842225,5.782933,8.820626,5.837943,...,4.001802,4.496335,6.336462,0.014355,8.471269,7.032321,6.405652,4.730096,6.434128,6.553975
ACH-001339,5.533875,3.220330,0.344828,3.490570,6.887769,4.951401,4.500802,3.339137,8.528220,7.006410,...,5.384741,5.216843,5.364222,3.463361,5.226123,6.840337,6.225352,4.168321,6.897603,4.364572
ACH-001538,5.000901,4.510962,7.678776,3.117695,4.590362,5.954196,3.135863,3.867896,8.013518,4.858976,...,6.668176,5.697941,6.442446,3.503349,6.378338,5.937109,5.694602,4.187451,6.231317,3.833902
ACH-000242,6.293518,2.877744,6.437794,4.193772,5.982537,4.977280,9.730215,0.310340,8.425971,6.651339,...,6.371210,4.367371,6.162291,3.747387,4.048759,4.135042,4.890933,4.450221,6.272023,5.590662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-000285,6.052459,3.007196,0.150560,4.504620,5.712596,4.813012,1.584963,3.168321,8.763909,7.108211,...,0.389567,0.464668,7.425090,1.207893,5.656782,7.428109,5.706531,5.743084,5.893362,0.485427
ACH-002669,4.660495,2.671293,5.514122,4.004501,4.950002,6.057234,2.963474,3.510962,7.680817,5.669027,...,7.278264,5.038261,6.324091,3.493135,6.857981,5.267910,4.926474,3.870858,5.602884,4.789208
ACH-001858,6.895060,4.458119,3.594549,2.805292,6.879583,5.966707,2.625270,3.577731,7.523170,5.596637,...,5.258519,5.892877,4.890933,5.885086,6.522464,6.789599,5.454505,3.462052,6.692790,3.374344
ACH-001997,6.649472,3.815575,4.865424,3.250962,5.525129,5.563463,5.226509,4.319762,8.485829,6.152386,...,7.744094,4.942515,5.928844,5.464342,8.029011,5.282069,5.989593,3.544733,6.101398,3.734439
ACH-000052,5.943687,2.615887,0.641546,4.679199,5.985728,4.613532,8.271556,1.851999,7.813204,6.303598,...,2.422233,2.367371,6.286512,4.525443,6.094236,5.668743,5.646451,4.671859,6.584061,1.899176

In [110]:
targets_df = pd.read_csv('/Users/zijiexu/GEMS-LAB/jumpstart_bundle 2/data/protein_features/drug_target.csv')
targets_df

      DrugID (DrugBank ID)  Drug_Target (Gene Eentrez IDs)
0                  DB00114                            3067
1                  DB00117                            3067
2                  DB00142                           27165
3                  DB01839                            2162
4                  DB02340                            2162
...                    ...                             ...
15046              DB01398                             771
15047              DB01398                             759
15048              DB01398                             760
15049              DB04149                            5141
15050              DB04149                            5143

[15051 rows x 2 columns]

In [113]:
drug_to_targets = (
    targets_df
    .groupby("DrugID (DrugBank ID)")["Drug_Target (Gene Eentrez IDs)"]
    .apply(list)
    .to_dict()
)
drug_to_targets

{'DB00001': [2147],
 'DB00002': [2209,
  1956,
  2215,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00004': [3560, 3559, 3561],
 'DB00005': [7124,
  2209,
  2215,
  7133,
  4049,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00006': [2147],
 'DB00007': [2798],
 'DB00008': [3455, 3454],
 'DB00009': [5340, 5054, 2243, 5329],
 'DB00011': [3455, 3454],
 'DB00013': [5340, 5054, 5329, 5328, 4036, 5055, 5327, 6768, 5104, 4811],
 'DB00014': [3973, 2798],
 'DB00015': [5340, 5054, 2243, 5329],
 'DB00017': [799],
 'DB00018': [3455, 3454],
 'DB00019': [1991, 1441],
 'DB00020': [1438, 3563, 5553, 1439, 6383],
 'DB00022': [3455, 3454],
 'DB00025': [2159, 2158, 821, 7450, 3309, 811, 4035, 5264, 433, 3998, 90411],
 'DB00028': [2209, 2215, 2214, 2212, 2213, 9103],
 'DB00029': [5340, 5054, 2243, 5329],
 'DB00030': [3643,
  3480,
  1509,
  4036,
  1363,
  4856,
  3416,
  5925,
  5126,
  5122,
  3490,
  94121],
 'DB00031': [5340, 5054, 2243, 5329, 5055, 821, 302, 7123, 3856, 811, 4035],
 'DB00032': [3973, 2492],
 'DB00033': [3460, 3459],
 'DB00034': [3455, 3454],
 'DB00035': [552, 554, 553],
 'DB00036': [2159, 2155, 2677, 7035, 2152, 3249],
 'DB00039': [2263, 3339, 2264, 8829, 2260, 2261],
 'DB00040': [2642, 2740, 9340],
 'DB00041': [3560, 3559, 3561],
 'DB00042': [6843, 6844, 127833],
 'DB00043': [2205, 2206],
 'DB00044': [3973],
 'DB00045': [7097],
 'DB00046': [3643, 3480],
 'DB00047': [3643, 3480],
 'DB00048': [1277, 1281, 1280, 1278],
 'DB00050': [3973, 2798],
 'DB00051': [7124,
  2209,
  2215,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00052': [2690, 5618],
 'DB00054': [3674,
  2209,
  2215,
  7448,
  3690,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00055': [2157,
  2153,
  2147,
  5054,
  2677,
  5627,
  5196,
  1356,
  7056,
  10544,
  5104,
  5269],
 'DB00056': [945, 2209, 2215, 716, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00058': [1991],
 'DB00060': [3455, 3454],
 'DB00062': [259, 348, 6288],
 'DB00063': [3690],
 'DB00064': [259, 348, 6288],
 'DB00065': [7124],
 'DB00066': [2492],
 'DB00067': [552, 554, 553],
 'DB00068': [3455, 3454],
 'DB00069': [3455, 3454],
 'DB00071': [3643,
  3480,
  1509,
  4036,
  1363,
  4856,
  3416,
  3118,
  5925,
  5126,
  5122,
  3490,
  94121],
 'DB00072': [2064,
  2209,
  1956,
  2215,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00073': [931, 2209, 2215, 716, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00074': [3560,
  3559,
  2209,
  2215,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00075': [916,
  2209,
  2215,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103,
  915,
  917,
  919],
 'DB00078': [931, 2209, 2215, 716, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00081': [931, 2209, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00082': [2690],
 'DB00083': [6616, 388],
 'DB00086': [5340, 2149],
 'DB00087': [1043, 2209, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00089': [2346],
 'DB00091': [819, 5478, 5535],
 'DB00092': [2209, 914, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00093': [552],
 'DB00094': [2492],
 'DB00095': [3683, 2209, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00097': [3973, 2492],
 'DB00098': [3683, 909, 942, 3690, 2213, 920, 3140, 3688, 3685],
 'DB00099': [1991, 1441],
 'DB00100': [2157, 2147, 2159, 2155, 2677, 2160, 4035],
 'DB00102': [5159, 5156, 2],
 'DB00104': [6751, 6755, 6752],
 'DB00105': [3455, 3454],
 'DB00106': [2798],
 'DB00107': [5020, 5021],
 'DB00108': [3676,
  2209,
  2215,
  3383,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00110': [2209, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00111': [3560,
  3559,
  2209,
  2215,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00112': [7422, 2209, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00113': [634],
 'DB00114': [3067,
  5836,
  51380,
  64902,
  9054,
  10993,
  55163,
  18,
  883,
  57026,
  6472,
  189,
  875,
  6470,
  2571,
  2806,
  63826,
  8942,
  4953,
  211,
  4942,
  10558,
  113451,
  79896,
  586,
  23464,
  2805,
  29968,
  2731,
  9517,
  2875,
  6898,
  587,
  51166,
  8879,
  1491,
  10841,
  5837,
  11212,
  5834,
  1644,
  2572,
  23042,
  56267,
  339896,
  85007,
  212,
  84706,
  55034,
  113675,
  51091,
  55304,
  5023],
 'DB00115': [166785, 4548, 4552, 4594, 25974, 4524],
 'DB00116': [275,
  10797,
  6472,
  6470,
  4522,
  4548,
  10841,
  10840,
  471,
  4524,
  123263],
 'DB00117': [3067, 3034, 3035],
 'DB00118': [262, 4144, 875, 27232, 4143, 1312, 5409],
 'DB00119': [5313, 5315, 5162, 64902, 18, 5091],
 'DB00120': [10667, 2193, 10056, 7054, 6898, 5053],
 'DB00121': [64087, 3141, 56922, 5095, 5096, 31, 5091, 32],
 'DB00122': [43, 9468, 5130, 5338, 590, 5337, 162466],
 'DB00123': [3735],
 'DB00125': [4843, 4846, 113451, 435, 445, 384],
 'DB00126': [5033,
  5351,
  1621,
  5264,
  5352,
  8985,
  8424,
  5066,
  64175,
  79676,
  121642,
  55214,
  10536,
  55239,
  112398,
  221120,
  8284,
  54583,
  112399,
  55217,
  54681,
  3938,
  151],
 'DB00127': [4953, 54498, 6611, 762, 765, 763, 835, 766, 23632, 11238],
 'DB00128': [443,
  440,
  2806,
  95,
  444,
  2805,
  445,
  1615,
  10606,
  790,
  159,
  55157,
  80150,
  122622,
  91703,
  6035],
 'DB00129': [383, 5009, 2628, 4946, 4942, 384, 4947, 51686],
 'DB00130': [5471, 1503, 2752],
 'DB00131': [5836,
  5564,
  107,
  55902,
  5142,
  2180,
  5562,
  84532,
  5565,
  1385,
  5292,
  5144,
  3094,
  2203,
  132,
  3939,
  6714,
  134,
  5029,
  5028],
 'DB00132': [3992, 7442, 9415, 6785, 2864, 2170, 5468, 338557],
 'DB00133': [6301, 10993, 189, 875, 63826, 10558, 9517],
 'DB00134': [4548, 4552, 635, 10988, 23743],
 'DB00135': [8565, 51067, 7054, 6898],
 'DB00136': [7421],
 'DB00138': [1497],
 'DB00139': [5033,
  5351,
  7915,
  6389,
  8801,
  444,
  8630,
  8985,
  8424,
  64175,
  55214,
  10536,
  55217,
  6392,
  8974,
  6390,
  8802,
  5019,
  6391,
  56670,
  64064,
  8803,
  54583],
 'DB00140': [55312, 645],
 'DB00141': [5973, 2683, 4669, 8703, 8702, 8704, 55577, 51172],
 'DB00142': [27165,
  10157,
  2729,
  2746,
  2058,
  440,
  18,
  8833,
  2897,
  2902,
  2571,
  2806,
  2906,
  2677,
  2904,
  2905,
  586,
  2805,
  116444,
  2346,
  2572,
  29968,
  2730,
  2890,
  116443,
  2875,
  6898,
  2356,
  587,
  51166,
  2747,
  2903,
  10841,
  5832,
  2911,
  2744,
  2898,
  2900,
  2901,
  2891,
  2893,
  2892,
  2899,
  2914,
  2917,
  2918,
  56267,
  84706,
  5198,
  5188,
  2752,
  55191,
  26873,
  2895,
  2028,
  124454,
  51557,
  162417,
  23549,
  2894],
 'DB00143': [2937,
  2936,
  2944,
  373156,
  2940,
  2947,
  2941,
  2948,
  221357,
  2950,
  9446,
  2876,
  2877,
  2952,
  2954,
  2880,
  2878,
  2678,
  2739,
  4056,
  2879,
  27306,
  2946,
  3029,
  2939,
  4259,
  51060,
  2938,
  4257,
  2098,
  2745,
  2949,
  257202,
  493869,
  2882,
  4258,
  119391,
  51022],
 'DB00144': [949, 23761, 10396, 9791, 5578, 1608, 8527, 81490, 55627, 55512],
 'DB00145': [2743,
  64902,
  2937,
  6472,
  189,
  6470,
  2628,
  27232,
  211,
  8001,
  2741,
  2905,
  23464,
  116444,
  2731,
  2742,
  2903,
  212,
  2617,
  2653,
  570,
  2841,
  10249,
  219970,
  92292,
  51268],
 'DB00146': [7421],
 'DB00147': [8566],
 'DB00148': [1152, 548596, 1160, 2593, 1158],
 'DB00149': [23395, 51451, 586, 9836, 587, 51520],
 'DB00150': [7453, 10352],
 'DB00151': [51380,
  9054,
  2729,
  2937,
  875,
  2805,
  1036,
  2730,
  833,
  1491,
  4255,
  79587],
 'DB00152': [27010],
 'DB00153': [7421],
 'DB00154': [5742, 5743, 165140],
 'DB00155': [4843,
  4842,
  4846,
  5009,
  23564,
  445,
  23576,
  23569,
  353238,
  29943,
  51702,
  11240],
 'DB00156': [6897, 79896, 80222],
 'DB00157': [3294,
  23530,
  128,
  275,
  3419,
  4731,
  1717,
  4728,
  50814,
  3283,
  3284,
  1737,
  3945,
  10157,
  4705,
  4725,
  4726,
  6307,
  5162,
  92483,
  1645,
  11112,
  3291,
  217,
  501,
  4729,
  4200,
  3948,
  7915,
  1727,
  26227,
  4967,
  4697,
  4718,
  622,
  2746,
  51478,
  4722,
  222,
  3292,
  2819,
  4700,
  4835,
  4694,
  5831,
  124,
  4329,
  4711,
  8659,
  4716,
  7299,
  3030,
  10797,
  4709,
  223,
  4710,
  160287,
  6652,
  4704,
  374291,
  4717,
  3028,
  56901,
  10873,
  3290,
  1719,
  3293,
  4707,
  9563,
  127,
  4702,
  4712,
  3033,
  125,
  4701,
  3295,
  3939,
  4708,
  1109,
  221,
  126,
  4698,
  219,
  4723,
  4719,
  4724,
  4713,
  8854,
  131,
  51079,
  5860,
  126328,
  2597,
  4706,
  4695,
  3248,
  216,
  3420,
  1036,
  5959,
  5160,
  3156,
  7923,
  220,
  1962,
  3163,
  4190,
  8644,
  645,
  4715,
  224,
  4199,
  5161,
  4522,
  1646,
  7358,
  2936,
  7264,
  4714,
  4696,
  218,
  26330,
  3615,
  29920,
  4720,
  3162,
  1738,
  644,
  231,
  55967,
  2747,
  3614,
  35,
  3421,
  4191],
 'DB00159': [5742, 5468, 5743, 2864, 3992, 2182, 5467, 7442, 2181, 165140],
 'DB00160': [64902, 9054, 18, 16, 189, 8942, 2875, 85007, 84706, 57505],
 'DB00161': [7407, 586, 5096],
 'DB00162': [10901,
  5949,
  5947,
  8854,
  216,
  5959,
  220,
  112724,
  145226,
  6017,
  9227,
  9249,
  54884,
  51109,
  57665,
  50700,
  5950],
 'DB00163': [284904, 240, 23541, 266629, 5579, 8856, 5578, 1606, 5516, 5515],
 'DB00165': [8566, 501, 57026, 875],
 'DB00167': [3376, 586, 36, 587, 55699],
 'DB00169': [7421],
 'DB00170': [2147,
  2159,
  4835,
  2155,
  2158,
  5624,
  2677,
  8858,
  79001,
  632,
  5627,
  1728,
  154807,
  3620,
  7052,
  4129,
  994,
  316],
 'DB00171': [25,
  157,
  19,
  10939,
  8883,
  6833,
  440,
  22978,
  90,
  107,
  317,
  156,
  55902,
  207,
  369,
  27,
  65061,
  94,
  10060,
  2180,
  91,
  445,
  269,
  5562,
  8647,
  84532,
  439,
  10188,
  5243,
  1244,
  9619,
  5029,
  5028,
  9261,
  5023,
  5030,
  5024,
  2840,
  5032,
  5025],
 'DB00172': [5033,
  2058,
  5831,
  29920,
  5478,
  10105,
  11212,
  64175,
  55214,
  10536,
  8974,
  5625,
  10465,
  5479,
  5480,
  9360,
  25973,
  112849],
 'DB00173': [353, 32, 4507, 55825, 52, 6733],
 'DB00174': [440, 4677, 80150, 79731],
 'DB00176': [6532, 6531],
 'DB00177': [185],
 'DB00178': [1636],
 'DB00179': [240, 3480, 1588, 239],
 'DB00180': [2908],
 'DB00181': [2550, 9568],
 'DB00182': [9607, 134864, 3350, 1548, 6530, 6532, 6531],
 'DB00184': [57053,
  1135,
  1137,
  1141,
  1139,
  55584,
  1143,
  1136,
  1138,
  8973,
  1142],
 'DB00185': [1131, 1128],
 'DB00186': [2569,
  2555,
  2558,
  2557,
  2556,
  706,
  2559,
  2554,
  2560,
  2562,
  2561,
  2566,
  2565,
  2567,
  2564,
  2568,
  55879,
  2570,
  2563,
  200959],
 'DB00187': [153],
 'DB00188': [5707, 5708, 5689, 5693, 5690],
 'DB00189': [2555, 2558, 2557, 2556, 2559, 2554, 2560, 2562, 2561],
 'DB00191': [4129, 4128, 134864],
 'DB00192': [6331],
 'DB00193': [1131, 4985, 3358, 4986, 116443, 4988, 89832, 6530, 6532],
 'DB00194': [1803],
 'DB00195': [153, 154],
 'DB00196': [1576],
 'DB00197': [5468, 5054, 2182, 2104, 2101, 4129],
 'DB00198': [4663, 4758, 1066, 4759],
 'DB00200': [6947, 166785, 81693, 326625, 4548, 4552, 4594, 8029, 25974],
 'DB00201': [134, 5142, 6261, 135, 43, 3757],
 'DB00202': [1131, 1128, 57053, 1129, 89832],
 'DB00203': [8654, 5148, 5149, 10057, 5146, 28234],
 'DB00204': [3757, 3776, 3768],
 'DB00205': [1719, 55244],
 'DB00208': [64805, 1555, 1557],
 'DB00209': [1128],
 'DB00210': [6257, 5916, 5915, 6256, 5914, 6258],
 'DB00211': [148, 147],
 'DB00212': [5972],
 'DB00213': [6582, 55244, 9429],
 'DB00215': [1128, 6530, 3358, 6532, 148, 3269, 3757],
 'DB00216': [3350, 3357, 3355, 3354, 3363, 3352, 3351],
 'DB00217': [150, 152, 151, 3758],
 'DB00218': [23113, 7153],
 'DB00219': [1128],
 'DB00221': [153, 154],
 'DB00222': [6833, 3758, 3767],
 'DB00223': [2908],
 'DB00227': [3683, 3156, 3066, 8856, 5243],
 'DB00228': [27032, 2741, 513, 3778, 2890, 3736, 2554],
 'DB00230': [773],
 'DB00231': [2569,
  2555,
  2558,
  2557,
  2556,
  706,
  2559,
  2554,
  2560,
  2562,
  2561,
  2566,
  2565,
  2567,
  2564,
  2568,
  55879,
  2570,
  2563,
  200959],
 'DB00232': [759, 760, 762],
 'DB00233': [240, 5743, 30814, 5770],
 'DB00234': [1565, 6530, 3358, 6532],
 'DB00235': [5139, 8654, 5742, 5140],
 'DB00237': [2555, 2558, 2557, 2556, 2559, 2554, 2898, 2891, 1137, 1139],
 'DB00240': [2908],
 'DB00241': [2555, 2558, 2557, 2556, 2559, 2554, 2898, 2891, 1137, 1139],
 'DB00242': [4860, 6240, 5422, 6241, 50484, 5426, 5427, 56655, 54107],
 'DB00244': [5742, 5468, 240, 5743, 4353, 3551],
 'DB00245': [1128, 3269],
 'DB00246': [1812,
  1131,
  1128,
  1816,
  1133,
  150,
  3350,
  3359,
  152,
  1815,
  1132,
  3269,
  3356,
  3354,
  148,
  3358,
  1129,
  151,
  147,
  1814,
  3363,
  3352,
  1813,
  3351,
  3362,
  154,
  153,
  6915,
  6532,
  3757],
 'DB00247': [3350, 3357, 3356, 3358, 3363],
 'DB00248': [1812,
  1816,
  150,
  3350,
  152,
  1815,
  3357,
  3356,
  3358,
  151,
  1814,
  3363,
  3352,
  1813,
  3351],
 'DB00249': [7083],
 'DB00250': [3362],
 'DB00251': [1595],
 'DB00252': [6323, 6331, 1559],
 'DB00253': [2908],
 'DB00255': [2099, 2100, 2104],
 'DB00257': [3783,
  7226,
  1586,
  5243,
  1576,
  1588,
  3738,
  3577,
  554,
  1233,
  3757,
  1595,
  9971],
 'DB00259': [759, 760, 761, 762, 768, 377677],
 'DB00260': [2671],
 'DB00261': [5139, 64805],
 'DB00262': [2936],
 'DB00264': [153, 154, 155],
 'DB00266': [79001, 1728, 1429, 1559, 9159, 2859],
 'DB00268': [1812,
  1816,
  150,
  3350,
  152,
  1815,
  3357,
  3356,
  3358,
  151,
  1814,
  3352,
  1813,
  3351,
  3363],
 'DB00269': [2099],
 'DB00270': [775, 781, 8912, 783, 779, 776, 9254],
 'DB00272': [3274],
 'DB00273': [6323, 760, 2897, 762, 2554, 771, 759, 763, 766, 768, 377677],
 'DB00275': [185],
 'DB00276': [3757, 7153, 6580, 1565, 316],
 'DB00277': [134, 8654, 136, 5139, 5142, 135, 5141],
 'DB00278': [2147],
 'DB00279': [7068, 7067],
 'DB00280': [1131, 1128, 6331, 1129, 3751, 3752, 6582],
 'DB00281': [6336, 6331, 1956, 6335],
 'DB00282': [2224],
 'DB00283': [3269, 6580],
 'DB00284': [8972, 2548, 6476, 279],
 'DB00285': [1129, 150, 1128, 6530, 4886, 3356, 3358, 6532, 3362, 6531],
 'DB00286': [2099],
 'DB00287': [5737],
 'DB00288': [301, 2908],
 'DB00289': [6530, 6532, 6531, 3757],
 'DB00290': [3980, 3978],
 'DB00292': [151, 2554, 1584, 1585],
 'DB00293': [7298, 2356],
 'DB00294': [2099, 5241, 6462],
 'DB00295': [4985, 4986, 4988, 4987],
 'DB00296': [6336],
 'DB00297': [5731, 6336],
 'DB00298': [148, 147, 146],
 'DB00302': [5340],
 'DB00304': [2099, 5241, 6462],
 'DB00306': [2555, 2558, 2557, 2556, 2559, 2554, 2898, 2891, 1137, 1139],
 'DB00307': [6257, 6256, 6258, 5914, 5915, 5916],
 'DB00308': [3757, 3775, 782, 775, 81033, 786, 9424, 781, 90134, 3767],
 'DB00309': [81027],
 'DB00311': [759, 760, 762, 766, 771, 761, 765, 768, 23632],
 'DB00312': [2555, 2558, 2557, 2556, 2559, 2554, 2898, 2891, 1137, 1139],
 'DB00313': [18, 36, 9734, 3065],
 'DB00315': [3350, 3355, 3352, 3351],
 'DB00316': [5742, 5743, 771, 761, 766],
 'DB00317': [1956,
  2580,
  2051,
  8767,
  8986,
  9262,
  6793,
  11200,
  25,
  2064,
  3932,
  5979,
  4233,
  3055,
  2268,
  3815,
  6714,
  5261,
  2065,
  2042,
  4058,
  558,
  3791,
  2322,
  27,
  5601,
  1453,
  1454,
  1022,
  3654,
  5602,
  2044,
  2050,
  2047,
  5607,
  5587,
  2066,
  388228,
  80122,
  50488,
  147746,
  79837,
  4215,
  85443,
  81788,
  9748,
  2872,
  27148,
  51135,
  51701,
  9263,
  285220,
  23043,
  9429,
  10746],
 'DB00318': [4985, 4986, 4988],
 'DB00320': [150, 3357, 3352, 3351, 1576, 55244],
 'DB00321': [1131,
  1128,
  1133,
  150,
  3350,
  1132,
  4985,
  3269,
  3356,
  148,
  1129,
  4986,
  146,
  3736,
  3785,
  4914,
  3751,
  3752,
  1813,
  1812,
  1816,
  6530,
  3274,
  3358,
  6532,
  1814,
  3362,
  6531,
  6331,
  6335,
  6326,
  59340,
  11255],
 'DB00322': [7298],
 'DB00323': [1312],
 'DB00324': [2908],
 'DB00325': [43],
 'DB00327': [4985, 4986, 4988],
 'DB00328': [5742,
  5468,
  5743,
  2739,
  5320,
  145482,
  11251,
  240,
  3576,
  367,
  231,
  6916,
  8644,
  5732,
  9356,
  9376,
  10599],
 'DB00331': [5564],
 'DB00332': [1131, 1128, 1129],
 'DB00333': [57053, 4985, 116443, 4988, 5243, 4986, 3757],
 'DB00334': [1812,
  1131,
  1128,
  1816,
  1133,
  150,
  3350,
  3359,
  152,
  1815,
  1132,
  3269,
  3356,
  3354,
  148,
  3358,
  1129,
  151,
  147,
  1814,
  3363,
  3352,
  1813,
  3351,
  3362,
  3757],
 'DB00335': [153, 154],
 'DB00336': [254958],
 'DB00337': [2280, 2475],
 'DB00338': [1576],
 'DB00340': [1131, 1128, 1133, 1132, 1129],
 'DB00341': [3269],
 'DB00342': [1131, 3757, 3269, 5243, 1576, 1128, 1573],
 'DB00343': [786, 1576],
 'DB00344': [6530, 6532, 6531],
 'DB00345': [9356],
 'DB00346': [148, 147, 146],
 'DB00347': [8913],
 'DB00349': [2569,
  2555,
  2558,
  2557,
  2556,
  2559,
  2554,
  2560,
  2562,
  2561,
  2566,
  2565,
  2567,
  2564,
  2568,
  55879,
  2570,
  2563,
  200959],
 'DB00350': [5742, 3758],
 'DB00351': [5241, 2908],
 'DB00353': [1812, 3354, 3355, 3357],
 'DB00354': [1128, 3269],
 'DB00356': [3778],
 'DB00357': [1588],
 'DB00358': [3039, 135, 3757],
 'DB00360': [7166, 4846, 7054, 5053],
 'DB00361': [203068],
 'DB00363': [1812,
  1131,
  1128,
  59340,
  1133,
  150,
  3350,
  3359,
  152,
  1815,
  1132,
  3269,
  3356,
  3354,
  148,
  3358,
  1129,
  151,
  147,
  1814,
  3363,
  3352,
  50632,
  1813,
  3351,
  3362,
  1816,
  6532,
  3361,
  3757,
  11255],
 'DB00364': [2243, 1950, 2247, 2244, 2266, 643834],
 'DB00365': [23113],
 'DB00366': [1128, 3269],
 'DB00367': [2099, 367, 6715, 5241, 6462],
 'DB00368': [153, 150, 152, 148, 151, 147, 154, 146, 5053, 155, 1813],
 'DB00370': [150,
  3359,
  3269,
  3356,
  3358,
  4986,
  3350,
  1813,
  151,
  152,
  1812,
  6530,
  3363,
  148,
  1814],
 'DB00371': [2555, 2558, 2557, 2556, 2559, 2554],
 'DB00372': [1812, 1815, 1813],
 'DB00373': [153, 154, 155],
 'DB00374': [64805, 5739, 5467, 5734, 5733],
 'DB00376': [1131, 1128, 1133, 1132, 1129],
 'DB00377': [3359],
 'DB00378': [5241],
 'DB00379': [6331, 196, 3757, 6326],
 'DB00380': [7153, 7155],
 'DB00381': [759,
  775,
  781,
  774,
  783,
  779,
  776,
  55799,
  782,
  3776,
  146,
  148,
  147],
 'DB00382': [43, 590, 6582, 1544, 1129, 1268, 1269, 1145, 55244],
 'DB00383': [1131, 1128, 1129],
 'DB00384': [6338, 6337, 6339, 6340],
 'DB00385': [7153],
 'DB00387': [1131, 1128, 1132, 1129, 1133],
 'DB00388': [148, 147, 146],
 'DB00389': [7173],
 'DB00390': [476],
 'DB00391': [1814, 1813, 759, 760, 1815, 763, 766, 768, 11238],
 'DB00392': [1128, 1129, 116443, 590, 43],
 'DB00393': [782, 775, 4306, 783, 779, 785, 778, 784, 776, 196, 8856, 9971],
 'DB00396': [2099,
  5241,
  4306,
  6580,
  6581,
  2908,
  6462,
  367,
  1559,
  151306,
  10280],
 'DB00397': [1812, 153, 150, 148],
 'DB00398': [2324,
  5894,
  2322,
  5159,
  3791,
  3815,
  673,
  10733,
  8767,
  6793,
  25,
  4914,
  3643,
  3932,
  2534,
  1436,
  5979,
  3055,
  3350,
  2268,
  2260,
  6714,
  2321,
  2261,
  1017,
  3356,
  3358,
  1969,
  2042,
  2046,
  2053,
  3363,
  7048,
  1445,
  3357,
  27,
  2444,
  5601,
  3361,
  1452,
  1195,
  2932,
  3362,
  3718,
  3984,
  3985,
  6300,
  2044,
  2050,
  2047,
  2043,
  1018,
  1020,
  7010,
  5607,
  2045,
  5600,
  1432,
  4921,
  91807,
  57551,
  204851,
  147746,
  140469,
  11184,
  9212,
  85366,
  9748,
  10114,
  2872,
  27148,
  285220,
  23043,
  9344,
  11183],
 'DB00399': [2224, 9453],
 'DB00400': [203068],
 'DB00401': [775, 781, 783, 779, 776],
 'DB00402': [2555, 2558, 2556, 706, 2554, 2557],
 'DB00404': [2569,
  2555,
  2558,
  2557,
  2556,
  706,
  2559,
  2554,
  2560,
  2562,
  2561,
  2566,
  2565,
  2567,
  2564,
  2568,
  55879,
  2570,
  2563,
  200959,
  23476,
  5724],
 'DB00405': [3269],
 'DB00407': [462, 3053],
 'DB00408': [1812,
  3356,
  3358,
  1813,
  1129,
  1132,
  3350,
  1133,
  150,
  1128,
  151,
  152,
  1131,
  1815,
  3363,
  148,
  3269,
  1814,
  3362,
  57582,
  59340],
 'DB00409': [10280, 1815, 3356, 1814, 1813, 3350],
 'DB00411': [1128, 1129, 1135, 1132, 1133, 1131],

In [121]:
mapping_df = pd.read_csv('/Users/zijiexu/GEMS-LAB/jumpstart_bundle 2/data/synergy_labels/drugcomb_name_to_dbid_mapping.csv')
mapping_df = mapping_df.set_index('name_norm')['drugbank_id']
mapping_df

name_norm
5-fu           DB00544
abt-888            NaN
azd1775            NaN
bez-235            NaN
bortezomib     DB00188
                ...
smdc914896         NaN
tro 19622          NaN
ru360              NaN
smdc873969         NaN
smdc-530602        NaN
Name: drugbank_id, Length: 6245, dtype: object

In [122]:
mapping_df.loc['5-fu']

'DB00544'

In [2]:
import pandas as pd

In [34]:
combdb_df = pd.read_csv('/Users/zijiexu/GEMS-LAB/canonical_data/drugcombs_scored.csv')
combdb_df

,ID,Drug1,Drug2,Cell line,ZIP,Bliss,Loewe,HSA
0,1,5-FU,ABT-888,A2058,1.720,6.260,-2.750,5.540
1,2,5-FU,ABT-888,A2058,5.880,12.330,3.330,11.610
2,3,5-FU,ABT-888,A2058,3.590,11.660,2.650,10.940
3,4,5-FU,ABT-888,A2058,-0.850,5.150,-3.860,4.430
4,5,5-FU,AZD1775,A2058,12.290,15.770,10.400,18.660
...,...,...,...,...,...,...,...,...
498860,498861,Mitomycin C,Valproic acid sodium salt,DIPG25,-3.076,-11.124,-6.078,-6.367
498861,498862,Cyanein,Valproic acid sodium salt,DIPG25,1.320,-1.091,-16.157,1.139
498862,498863,Erlotinib,Valproic acid sodium salt,DIPG25,-15.768,-15.776,-25.465,-6.212
498863,498864,Bafilomycin A1,Valproic acid sodium salt,DIPG25,2.208,10.567,-9.455,1.525
498864,498865,Mebendazole,Valproic acid sodium salt,DIPG25,6.807,11.948,-18.311,1.149

In [35]:
pair_means = (
    combdb_df
    .groupby(['Drug1', 'Drug2'])['ZIP']
    .mean()
    .reset_index(name='mean_ZIP')
)

pair_means

,Drug1,Drug2,mean_ZIP
0,(+)-BICUCULLINE,TEMOZOLOMIDE,21.850000
1,(+)-Blebbistatin,(+)-JQ1,8.410000
2,(+)-Blebbistatin,IBRUTINIB (PCI-32765),12.420000
3,(+)-JQ1,(+)-JQ1,4.512857
4,(+)-JQ1,(-)-Ethyl apovincaminate,12.700000
...,...,...,...
84341,xylometazoline,RUXOLITINIB,60.940000
84342,"{(3r,4r)-4-Methyl-3-[methyl(7h-Pyrrolo[2,3-D]p...",MARIZOMIB,4.860000
84343,"{(3r,4r)-4-Methyl-3-[methyl(7h-Pyrrolo[2,3-D]p...",PANOBINOSTAT,-5.980000
84344,"{2-[(2,6-dichlorophenyl)amino]phenyl}acetate",717906-29-1,-4.570000
84345,"{2-[(2,6-dichlorophenyl)amino]phenyl}acetate",RUXOLITINIB,1.100000

In [36]:
filtered = pair_means[
    (pair_means['mean_ZIP'] > 10) |
    (pair_means['mean_ZIP'] < -10)
].copy()

filtered

                   Drug1                     Drug2  mean_ZIP
0        (+)-BICUCULLINE              TEMOZOLOMIDE    21.850
2       (+)-Blebbistatin     IBRUTINIB (PCI-32765)    12.420
4                (+)-JQ1  (-)-Ethyl apovincaminate    12.700
8                (+)-JQ1               200484-11-3    23.675
9                (+)-JQ1               451492-95-8    12.620
...                  ...                       ...       ...
84305       thapsigargin                mefloquine    22.280
84314         tizanidine               RUXOLITINIB    43.270
84331       valacyclovir               RUXOLITINIB    26.900
84335  vindesine sulfate               RUXOLITINIB    11.150
84341     xylometazoline               RUXOLITINIB    60.940

[36817 rows x 3 columns]

In [37]:
filtered['label'] = (filtered['mean_ZIP'] > 10).astype(int)

filtered.groupby('label').count()

       Drug1  Drug2  mean_ZIP
label
0      24450  24450     24450
1      12367  12367     12367

In [18]:
import pandas as pd
df = pd.read_csv("/Users/zijiexu/GEMS-LAB/canonical_data/canonical_folds.csv")
print(len(df), df['label'].value_counts().to_dict(), df['fold'].value_counts().to_dict())
# 40831 {0: 27984, 1: 12847} {1: 13611, 0: 13610, 2: 13610}

40831 {0: 27984, 1: 12847} {0: 13611, 1: 13610, 2: 13610}

In [21]:
df['fold'].unique()

array([1, 0, 2])

In [24]:
ppi_path = "/Users/zijiexu/GEMS-LAB/jumpstart_bundle 2/data/protein_features/string_ppi_entrez.csv"
landmarks_path = "/Users/zijiexu/GEMS-LAB/jumpstart_bundle 2/data/landmark_genes.txt"

print(f'=== PPI FILE: {ppi_path} ===')
print(f'=== LANDMARKS FILE: {landmarks_path} ===')

ppi_df = pd.read_csv(ppi_path)
landmarks_df = pd.read_csv(landmarks_path, sep="\t")

landmark_ids = set(list(landmarks_df["Entrez ID"]))

ppi_filtered = ppi_df[
    ppi_df["entrez_id_a"].isin(landmark_ids) &
    ppi_df["entrez_id_b"].isin(landmark_ids)
]

ppi_filtered.groupby('entrez_id_a').count()

=== PPI FILE: /Users/zijiexu/GEMS-LAB/jumpstart_bundle 2/data/protein_features/string_ppi_entrez.csv ===
=== LANDMARKS FILE: /Users/zijiexu/GEMS-LAB/jumpstart_bundle 2/data/landmark_genes.txt ===

             entrez_id_b  symbol_a  symbol_b  score  source
entrez_id_a
16                     5         5         5      5       5
23                     2         2         2      2       2
25                    33        33        33     33      33
30                     9         9         9      9       9
39                     8         8         8      8       8
...                  ...       ...       ...    ...     ...
116832                 3         3         3      3       3
124583                 1         1         1      1       1
147179                 3         3         3      3       3
148022                 4         4         4      4       4
200081                 2         2         2      2       2

[748 rows x 5 columns]

In [28]:
group_means = combdb_df.groupby(['Drug1', 'Drug2'])['ZIP'].transform('mean')

filtered_df = combdb_df[(group_means > 10) | (group_means < 0)]
filtered_df

,ID,Drug1,Drug2,Cell line,ZIP,Bliss,Loewe,HSA
0,1,5-FU,ABT-888,A2058,1.720,6.260,-2.750,5.540
1,2,5-FU,ABT-888,A2058,5.880,12.330,3.330,11.610
2,3,5-FU,ABT-888,A2058,3.590,11.660,2.650,10.940
3,4,5-FU,ABT-888,A2058,-0.850,5.150,-3.860,4.430
8,9,5-FU,BEZ-235,A2058,4.010,3.380,3.210,7.140
...,...,...,...,...,...,...,...,...
498849,498850,BMS-754807,Valproic acid sodium salt,DIPG25,-2.363,-1.900,-32.929,1.915
498850,498851,Lenalidomide,Valproic acid sodium salt,DIPG25,-13.080,-17.051,-2.520,-6.883
498857,498858,Doxorubicin,Valproic acid sodium salt,DIPG25,3.215,10.998,-21.448,2.021
498859,498860,Rotenone,Valproic acid sodium salt,DIPG25,-6.545,-5.280,-6.811,2.909
498862,498863,Erlotinib,Valproic acid sodium salt,DIPG25,-15.768,-15.776,-25.465,-6.212

In [32]:
group_means = combdb_df.groupby(['Drug1', 'Drug2'])['ZIP'].mean()

filtered = group_means[(group_means > 10) | (group_means < 0)]
filtered.shape

(55717,)

# DrugComb testing

In [3]:
import pandas as pd

In [48]:
CANONICAL_DATA_DIR = '/Users/zijiexu/GEMS-LAB/canonical_data/'
CANONICAL_DATA_DIR_2 = "/Users/zijiexu/Downloads/canonical_data/"

In [5]:
combdb_df = pd.read_csv(CANONICAL_DATA_DIR + 'drugcombs_scored.csv')

combdb_df

,ID,Drug1,Drug2,Cell line,ZIP,Bliss,Loewe,HSA
0,1,5-FU,ABT-888,A2058,1.720,6.260,-2.750,5.540
1,2,5-FU,ABT-888,A2058,5.880,12.330,3.330,11.610
2,3,5-FU,ABT-888,A2058,3.590,11.660,2.650,10.940
3,4,5-FU,ABT-888,A2058,-0.850,5.150,-3.860,4.430
4,5,5-FU,AZD1775,A2058,12.290,15.770,10.400,18.660
...,...,...,...,...,...,...,...,...
498860,498861,Mitomycin C,Valproic acid sodium salt,DIPG25,-3.076,-11.124,-6.078,-6.367
498861,498862,Cyanein,Valproic acid sodium salt,DIPG25,1.320,-1.091,-16.157,1.139
498862,498863,Erlotinib,Valproic acid sodium salt,DIPG25,-15.768,-15.776,-25.465,-6.212
498863,498864,Bafilomycin A1,Valproic acid sodium salt,DIPG25,2.208,10.567,-9.455,1.525
498864,498865,Mebendazole,Valproic acid sodium salt,DIPG25,6.807,11.948,-18.311,1.149

In [6]:
pair_means = (
    combdb_df
    .groupby(['Drug1', 'Drug2'])['ZIP']
    .mean()
    .reset_index(name='mean_ZIP')
)

pair_means

,Drug1,Drug2,mean_ZIP
0,(+)-BICUCULLINE,TEMOZOLOMIDE,21.850000
1,(+)-Blebbistatin,(+)-JQ1,8.410000
2,(+)-Blebbistatin,IBRUTINIB (PCI-32765),12.420000
3,(+)-JQ1,(+)-JQ1,4.512857
4,(+)-JQ1,(-)-Ethyl apovincaminate,12.700000
...,...,...,...
84341,xylometazoline,RUXOLITINIB,60.940000
84342,"{(3r,4r)-4-Methyl-3-[methyl(7h-Pyrrolo[2,3-D]p...",MARIZOMIB,4.860000
84343,"{(3r,4r)-4-Methyl-3-[methyl(7h-Pyrrolo[2,3-D]p...",PANOBINOSTAT,-5.980000
84344,"{2-[(2,6-dichlorophenyl)amino]phenyl}acetate",717906-29-1,-4.570000
84345,"{2-[(2,6-dichlorophenyl)amino]phenyl}acetate",RUXOLITINIB,1.100000

In [7]:
filtered = pair_means[
    (pair_means['mean_ZIP'] > 10) |
    (pair_means['mean_ZIP'] < -10)
].copy()

filtered

                   Drug1                     Drug2  mean_ZIP
0        (+)-BICUCULLINE              TEMOZOLOMIDE    21.850
2       (+)-Blebbistatin     IBRUTINIB (PCI-32765)    12.420
4                (+)-JQ1  (-)-Ethyl apovincaminate    12.700
8                (+)-JQ1               200484-11-3    23.675
9                (+)-JQ1               451492-95-8    12.620
...                  ...                       ...       ...
84305       thapsigargin                mefloquine    22.280
84314         tizanidine               RUXOLITINIB    43.270
84331       valacyclovir               RUXOLITINIB    26.900
84335  vindesine sulfate               RUXOLITINIB    11.150
84341     xylometazoline               RUXOLITINIB    60.940

[36817 rows x 3 columns]

In [8]:
filtered['label'] = (filtered['mean_ZIP'] > 10).astype(int)

filtered

                   Drug1                     Drug2  mean_ZIP  label
0        (+)-BICUCULLINE              TEMOZOLOMIDE    21.850      1
2       (+)-Blebbistatin     IBRUTINIB (PCI-32765)    12.420      1
4                (+)-JQ1  (-)-Ethyl apovincaminate    12.700      1
8                (+)-JQ1               200484-11-3    23.675      1
9                (+)-JQ1               451492-95-8    12.620      1
...                  ...                       ...       ...    ...
84305       thapsigargin                mefloquine    22.280      1
84314         tizanidine               RUXOLITINIB    43.270      1
84331       valacyclovir               RUXOLITINIB    26.900      1
84335  vindesine sulfate               RUXOLITINIB    11.150      1
84341     xylometazoline               RUXOLITINIB    60.940      1

[36817 rows x 4 columns]

In [9]:
print(len(filtered['Drug1'].unique()))
print(len(filtered['Drug2'].unique()))

3128
744

In [10]:
name_to_dbid_mapping = pd.read_csv(CANONICAL_DATA_DIR + "drugcomb_name_to_dbid_mapping_improved.csv")
name_to_dbid_mapping

            name   name_norm drugbank_id     strategy
0           5-FU        5-fu     DB00544    norm_name
1        ABT-888     abt-888     DB07232  pubchem_cid
2        AZD1775     azd1775     DB11740  pubchem_cid
3        BEZ-235     bez-235     DB11651  pubchem_cid
4     BORTEZOMIB  bortezomib     DB00188    norm_name
...          ...         ...         ...          ...
6240        EMPM        empm         NaN          NaN
6241     SHP-099     shp-099         NaN          NaN
6242      ML-119      ml-119         NaN          NaN
6243     RRx-001     rrx-001     DB12060    norm_name
6244  PluriSln 1  plurisln 1         NaN          NaN

[6245 rows x 4 columns]

In [11]:
drug1_merge = filtered.merge(
    name_to_dbid_mapping,
    left_on='Drug1',
    right_on='name',
    how='left'
)

In [12]:
drug1_merge_renamed = drug1_merge.rename(columns={'name': 'name_1', 'name_norm': 'name_norm_1', 'drugbank_id': 'drugbank_id_1'}).drop(columns=['strategy'])
drug1_merge_renamed

,Drug1,Drug2,mean_ZIP,label,name_1,name_norm_1,drugbank_id_1
0,(+)-BICUCULLINE,TEMOZOLOMIDE,21.850,1,(+)-BICUCULLINE,(+)-bicuculline,NaN
1,(+)-Blebbistatin,IBRUTINIB (PCI-32765),12.420,1,(+)-Blebbistatin,(+)-blebbistatin,NaN
2,(+)-JQ1,(-)-Ethyl apovincaminate,12.700,1,(+)-JQ1,(+)-jq1,NaN
3,(+)-JQ1,200484-11-3,23.675,1,(+)-JQ1,(+)-jq1,NaN
4,(+)-JQ1,451492-95-8,12.620,1,(+)-JQ1,(+)-jq1,NaN
...,...,...,...,...,...,...,...
36812,thapsigargin,mefloquine,22.280,1,thapsigargin,thapsigargin,NaN
36813,tizanidine,RUXOLITINIB,43.270,1,tizanidine,tizanidine,DB00697
36814,valacyclovir,RUXOLITINIB,26.900,1,valacyclovir,valacyclovir,DB00577
36815,vindesine sulfate,RUXOLITINIB,11.150,1,vindesine sulfate,vindesine sulfate,DB00309
36816,xylometazoline,RUXOLITINIB,60.940,1,xylometazoline,xylometazoline,DB06694

In [13]:
drug2_merge = drug1_merge_renamed.merge(
    name_to_dbid_mapping,
    left_on='Drug2',
    right_on='name',
    how='left'
)

In [14]:
df_with_ids = drug2_merge.rename(columns={'name': 'name_2', 'name_norm': 'name_norm_2', 'drugbank_id': 'drugbank_id_2'}).drop(columns=['strategy'])
df_with_ids

,Drug1,Drug2,mean_ZIP,label,name_1,name_norm_1,drugbank_id_1,name_2,name_norm_2,drugbank_id_2
0,(+)-BICUCULLINE,TEMOZOLOMIDE,21.850,1,(+)-BICUCULLINE,(+)-bicuculline,NaN,TEMOZOLOMIDE,temozolomide,DB00853
1,(+)-Blebbistatin,IBRUTINIB (PCI-32765),12.420,1,(+)-Blebbistatin,(+)-blebbistatin,NaN,IBRUTINIB (PCI-32765),ibrutinib (pci-32765),DB09053
2,(+)-JQ1,(-)-Ethyl apovincaminate,12.700,1,(+)-JQ1,(+)-jq1,NaN,(-)-Ethyl apovincaminate,(-)-ethyl apovincaminate,NaN
3,(+)-JQ1,200484-11-3,23.675,1,(+)-JQ1,(+)-jq1,NaN,200484-11-3,200484-11-3,NaN
4,(+)-JQ1,451492-95-8,12.620,1,(+)-JQ1,(+)-jq1,NaN,451492-95-8,451492-95-8,NaN
...,...,...,...,...,...,...,...,...,...,...
36812,thapsigargin,mefloquine,22.280,1,thapsigargin,thapsigargin,NaN,mefloquine,mefloquine,DB00358
36813,tizanidine,RUXOLITINIB,43.270,1,tizanidine,tizanidine,DB00697,RUXOLITINIB,ruxolitinib,DB08877
36814,valacyclovir,RUXOLITINIB,26.900,1,valacyclovir,valacyclovir,DB00577,RUXOLITINIB,ruxolitinib,DB08877
36815,vindesine sulfate,RUXOLITINIB,11.150,1,vindesine sulfate,vindesine sulfate,DB00309,RUXOLITINIB,ruxolitinib,DB08877
36816,xylometazoline,RUXOLITINIB,60.940,1,xylometazoline,xylometazoline,DB06694,RUXOLITINIB,ruxolitinib,DB08877

In [15]:
df_with_ids.groupby('label').count()

,Drug1,Drug2,mean_ZIP,name_1,name_norm_1,drugbank_id_1,name_2,name_norm_2,drugbank_id_2
label,,,,,,,,,
0,24450,24450,24450,24450,24450,22828,24450,24450,22929
1,12367,12367,12367,12366,12366,8646,12367,12367,9938

In [16]:
fold_splits = pd.read_csv(CANONICAL_DATA_DIR + "canonical_folds.csv")
fold_splits

       triplet_id drug1_dbid drug2_dbid cell_name  label  fold
0               0    DB00063    DB00176     KBM-7      0     1
1               1    DB00063    DB00181     KBM-7      0     0
2               2    DB00063    DB00185     KBM-7      0     2
3               3    DB00063    DB00198     KBM-7      0     1
4               4    DB00063    DB00203     KBM-7      0     0
...           ...        ...        ...       ...    ...   ...
40826       40826    DB16828    DB17428     U-HO1      1     1
40827       40827    DB16830    DB17062     TC-32      1     2
40828       40828    DB17015    DB17016   SKMEL30      1     2
40829       40829    DB17015    DB17016     ZR751      0     0
40830       40830    DB17021    DB17062     TC-71      1     1

[40831 rows x 6 columns]

In [17]:
fold_splits.groupby('label').count()

       triplet_id  drug1_dbid  drug2_dbid  cell_name   fold
label
0           27984       27984       27984      27984  27984
1           12847       12847       12847      12847  12847

In [18]:
fold_splits['cell_name'].unique()

array(['KBM-7', 'T98G', 'L-1236', 'MALME-3M', 'MCF7', 'PC-3', 'HCT-15',
       'HCT116', 'HOP-92', 'LOX IMVI', 'NCI-H460', 'NCIH23', 'RPMI-8226',
       'SN12C', 'COLO320DM', 'MOLT-4', 'HL-60(TB)', 'MDA-MB-468',
       'NCI-H522', 'NCI\\\\/ADR-RES', 'UO-31', 'MSTO', 'CAKI-1', 'SW-620',
       'U251', 'A2058', 'A549', 'ZR751', 'IGROV1', 'MDA-MB-231', 'SR',
       'CCRF-CEM', 'A498', 'BT-549', 'DU-145', 'HT29', 'K-562', 'RXF 393',
       'SF-268', 'SK-MEL-2', 'SK-MEL-28', 'SNB-19', 'TK-10', 'UACC-257',
       'ES2', 'NCIH2122', 'SK-MEL-5', 'HS 578T', 'SKMEL30', 'COLO 205',
       'NCI-H226', 'HCC-2998', 'LNCAP', 'ACHN', 'SF-539', 'SW837',
       'NCI-H322M', 'M14', 'OVCAR3', 'SK-OV-3', 'MDA-MB-435', 'HOP-62',
       'OVCAR-5', 'T-47D', 'UACC62', 'OVCAR-4', 'HDLM-2', 'L-428',
       'HT144', 'A2780', '786-0', 'KM12', 'OVCAR-8', 'SNB-75', 'SF-295',
       'JHH-136', 'JHH-520', 'EKVX', 'CAOV3', 'EFM192B', 'LOVO',
       'MDAMB436', 'NCIH520', 'OV90', 'RKO', 'RPMI7951', 'SKMES1',
       'TC-71', 'PA1', 'A375', 'A427', 'U-HO1', 'KPL1', 'OCUBM', 'TC-32',
       'DLD1', 'UWB1289', 'NCIH1650', 'VCAP', 'UWB1289+BRCA1', 'RD',
       'Rh36', 'Huh-7', 'CTR', 'SMS-CTR', 'EW-8'], dtype=object)

In [19]:
ccle = pd.read_csv('/Users/zijiexu/GEMS-LAB/jumpstart_bundle 2/data/CCLE_expression.csv').set_index('Unnamed: 0')
ccle

,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),C1orf112 (55732),FGR (2268),CFH (3075),FUCA2 (2519),GCLC (2729),NFYA (4800),...,H3C2 (8358),H3C3 (8352),AC098582.1 (8916),DUS4L-BCAP29 (115253422),C8orf44-SGK3 (100533105),ELOA3B (728929),NPBWR1 (2831),ELOA3D (100506888),ELOA3 (162699),CDR1 (1038)
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
ACH-001113,4.331992,0.000000,7.364397,2.792855,4.470537,0.028569,1.226509,3.042644,6.499686,4.739848,...,2.689299,0.189034,0.201634,2.130931,0.555816,0.000000,0.275007,0.0,0.000000,0.000000
ACH-001289,4.566815,0.584963,7.106537,2.543496,3.504620,0.000000,0.189034,3.813525,4.221104,3.481557,...,1.286881,1.049631,0.321928,1.464668,0.632268,0.000000,0.014355,0.0,0.000000,0.000000
ACH-001339,3.150560,0.000000,7.379032,2.333424,4.227279,0.056584,1.310340,6.687061,3.682573,3.273516,...,0.594549,1.097611,0.831877,2.946731,0.475085,0.000000,0.084064,0.0,0.000000,0.042644
ACH-001538,5.085340,0.000000,7.154109,2.545968,3.084064,0.000000,5.868143,6.165309,4.489928,3.956986,...,0.214125,0.632268,0.298658,1.641546,0.443607,0.000000,0.028569,0.0,0.000000,0.000000
ACH-000242,6.729145,0.000000,6.537607,2.456806,3.867896,0.799087,7.208381,5.569856,7.127014,4.568032,...,1.117695,2.358959,0.084064,1.910733,0.000000,0.000000,0.464668,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-000285,0.056584,0.000000,6.604071,3.264536,4.972693,0.411426,0.097611,0.704872,4.829850,5.178715,...,2.229588,0.084064,1.310340,3.039138,0.344828,0.000000,0.000000,0.0,0.475085,0.042644
ACH-002669,3.109361,0.000000,7.031219,1.541019,3.664483,0.014355,3.624101,6.805292,4.472488,4.397118,...,0.189034,0.400538,0.356144,1.327687,0.000000,0.000000,0.014355,0.0,0.000000,0.000000
ACH-001858,4.390943,0.000000,7.013127,1.887525,3.252476,0.028569,3.286881,6.902074,5.410748,3.401903,...,1.097611,0.400538,0.613532,1.992768,0.704872,0.000000,1.464668,0.0,0.000000,0.526069
ACH-001997,5.057017,0.000000,7.814935,2.538538,3.893362,0.028569,4.078951,6.971429,4.469886,3.463361,...,0.831877,0.847997,1.292782,2.153805,0.687061,0.000000,0.000000,0.0,0.000000,0.000000
ACH-000052,4.247928,0.000000,6.174127,2.316146,3.823749,0.189034,1.321928,3.536053,3.943921,4.468583,...,1.244887,1.201634,0.000000,1.956057,0.575312,0.042644,0.000000,0.0,0.176323,0.056584

In [20]:
cell_line_ccle_map = pd.read_csv(CANONICAL_DATA_DIR + "cell_line_ccle_map.csv").set_index('drugcomb_name')
cell_line_ccle_map

              ccle_modelid     match_type
drugcomb_name
3D7                    NaN      unmatched
786-0           ACH-000649     alias:786O
A-375           ACH-000219       stripped
A2058           ACH-000788       stripped
A2780           ACH-000657       stripped
...                    ...            ...
UWB1289         ACH-001418       stripped
UWB1289+BRCA1   ACH-001418  alias:UWB1289
VCAP            ACH-000115       stripped
WM-115          ACH-000304       stripped
ZR751           ACH-000097       stripped

[122 rows x 2 columns]

In [21]:
drug_comb_cell_lines = list(fold_splits['cell_name'].unique())
match_count = 0
missing_count = 0
for name in drug_comb_cell_lines:
    id = cell_line_ccle_map['ccle_modelid'].get(name)
    if id is None:
        missing_count += 1
        print(f'{name} not in mapping')
    else:
        match_count += 1

print(f'match count: {match_count}')
print(f'missing count: {missing_count}')

match count: 106
missing count: 0

In [22]:
for name in drug_comb_cell_lines:
    id = cell_line_ccle_map.loc[name]['ccle_modelid']
    cell_line = ccle['TSPAN6 (7105)'].get(id)
    if cell_line is None:
        print(f'Missing: {id}')

Missing: ACH-002199
Missing: ACH-001127
Missing: ACH-001738
Missing: ACH-000979
Missing: ACH-002195
Missing: ACH-001198
Missing: ACH-001208
Missing: ACH-001039
Missing: ACH-001081
Missing: ACH-002172
Missing: ACH-002159
Missing: ACH-002179
Missing: ACH-001205

In [23]:
filtered

                   Drug1                     Drug2  mean_ZIP  label
0        (+)-BICUCULLINE              TEMOZOLOMIDE    21.850      1
2       (+)-Blebbistatin     IBRUTINIB (PCI-32765)    12.420      1
4                (+)-JQ1  (-)-Ethyl apovincaminate    12.700      1
8                (+)-JQ1               200484-11-3    23.675      1
9                (+)-JQ1               451492-95-8    12.620      1
...                  ...                       ...       ...    ...
84305       thapsigargin                mefloquine    22.280      1
84314         tizanidine               RUXOLITINIB    43.270      1
84331       valacyclovir               RUXOLITINIB    26.900      1
84335  vindesine sulfate               RUXOLITINIB    11.150      1
84341     xylometazoline               RUXOLITINIB    60.940      1

[36817 rows x 4 columns]

In [24]:
smiles = pd.read_csv('/Users/zijiexu/GEMS-LAB/jumpstart_bundle 2/data/synergy_labels/drug_chemical_info_with_smiles.csv')
smiles

,Unnamed: 0,drugName,cIds,drugNameOfficial,molecularWeight,smilesString
0,0,Bendamustine,CIDs00065628,bendamustine,358.26284,CN1C2=C(C=C(C=C2)N(CCCl)CCCl)N=C1CCCC(=O)O
1,1,Lonidamine,CIDs00039562,lonidamine,321.15810,C1=CC=C2C(=C1)C(=NN2CC3=C(C=C(C=C3)Cl)Cl)C(=O)O
2,2,Lenalidomide,CIDs00216326,lenalidomide,259.26062,C1CC(=O)NC(=O)C1N2CC3=C(C2=O)C=CC=C3N
3,3,Cladribine,CIDs00020279,cladribine,285.68698,C1C(C(OC1N2C=NC3=C2N=C(N=C3N)Cl)CO)O
4,4,Pentostatin,CIDs00439693,pentostatin,268.26914,C1C(C(OC1N2C=NC3=C2NC=NCC3O)CO)O
...,...,...,...,...,...,...
3024,3049,CO-V,CIDs00040926,Niapent,268.26914,C1C(C(OC1N2C=NC3=C2NC=NCC3O)CO)O
3025,3050,ADM HYDROCHLORIDE,CIDs00032874,doxorubicin hydrochloride,579.98020,CC1C(C(CC(O1)OC2CC(CC3=C(C4=C(C(=C23)O)C(=O)C5...
3026,3051,NSC 85998,CIDs23615975,streptozotocine,265.22060,CN(C(=O)NC(C=O)C(C(C(CO)O)O)O)N=O
3027,3052,NSC-127716,CIDs00016886,5-aza-2'-deoxycytidine,228.20528,C1C(C(OC1N2C=NC(=NC2=O)N)CO)O
3028,3058,NSC256439,CIDs00003685,4-DMDR,497.49388,CC1C(C(CC(O1)OC2CC(CC3=C(C4=C(C(=C23)O)C(=O)C5...

In [25]:
smiles['normalized_drugName'] = smiles['drugName']
smiles['normalized_drugName'] = (
    smiles['normalized_drugName']
    .str.lower()
    .str.strip()
)

smiles['normalized_drugNameOfficial'] = smiles['drugNameOfficial']
smiles['normalized_drugNameOfficial'] = (
    smiles['normalized_drugNameOfficial']
    .str.lower()
    .str.strip()
)

smiles

,Unnamed: 0,drugName,cIds,drugNameOfficial,molecularWeight,smilesString,normalized_drugName,normalized_drugNameOfficial
0,0,Bendamustine,CIDs00065628,bendamustine,358.26284,CN1C2=C(C=C(C=C2)N(CCCl)CCCl)N=C1CCCC(=O)O,bendamustine,bendamustine
1,1,Lonidamine,CIDs00039562,lonidamine,321.15810,C1=CC=C2C(=C1)C(=NN2CC3=C(C=C(C=C3)Cl)Cl)C(=O)O,lonidamine,lonidamine
2,2,Lenalidomide,CIDs00216326,lenalidomide,259.26062,C1CC(=O)NC(=O)C1N2CC3=C(C2=O)C=CC=C3N,lenalidomide,lenalidomide
3,3,Cladribine,CIDs00020279,cladribine,285.68698,C1C(C(OC1N2C=NC3=C2N=C(N=C3N)Cl)CO)O,cladribine,cladribine
4,4,Pentostatin,CIDs00439693,pentostatin,268.26914,C1C(C(OC1N2C=NC3=C2NC=NCC3O)CO)O,pentostatin,pentostatin
...,...,...,...,...,...,...,...,...
3024,3049,CO-V,CIDs00040926,Niapent,268.26914,C1C(C(OC1N2C=NC3=C2NC=NCC3O)CO)O,co-v,niapent
3025,3050,ADM HYDROCHLORIDE,CIDs00032874,doxorubicin hydrochloride,579.98020,CC1C(C(CC(O1)OC2CC(CC3=C(C4=C(C(=C23)O)C(=O)C5...,adm hydrochloride,doxorubicin hydrochloride
3026,3051,NSC 85998,CIDs23615975,streptozotocine,265.22060,CN(C(=O)NC(C=O)C(C(C(CO)O)O)O)N=O,nsc 85998,streptozotocine
3027,3052,NSC-127716,CIDs00016886,5-aza-2'-deoxycytidine,228.20528,C1C(C(OC1N2C=NC(=NC2=O)N)CO)O,nsc-127716,5-aza-2'-deoxycytidine
3028,3058,NSC256439,CIDs00003685,4-DMDR,497.49388,CC1C(C(CC(O1)OC2CC(CC3=C(C4=C(C(=C23)O)C(=O)C5...,nsc256439,4-dmdr

In [26]:
smiles_drugName = smiles.copy().set_index('normalized_drugName')
smiles_drugNameOfficial = smiles.copy().set_index('normalized_drugNameOfficial')

In [27]:
dbid_to_drug = pd.read_csv(CANONICAL_DATA_DIR + 'drugcomb_name_to_dbid_mapping_improved.csv').set_index('drugbank_id')
dbid_to_drug

                   name   name_norm     strategy
drugbank_id
DB00544            5-FU        5-fu    norm_name
DB07232         ABT-888     abt-888  pubchem_cid
DB11740         AZD1775     azd1775  pubchem_cid
DB11651         BEZ-235     bez-235  pubchem_cid
DB00188      BORTEZOMIB  bortezomib    norm_name
...                 ...         ...          ...
NaN                EMPM        empm          NaN
NaN             SHP-099     shp-099          NaN
NaN              ML-119      ml-119          NaN
DB12060         RRx-001     rrx-001    norm_name
NaN          PluriSln 1  plurisln 1          NaN

[6245 rows x 3 columns]

In [28]:
test_id = 'DB00544'

In [29]:
def get_names(id):
    return dbid_to_drug['name_norm'].get(id)

In [35]:
def get_smiles(names):
    for name in names:
        if name in smiles_drugName.index:
            print(f'{name} found in smiles_drugName')

            smiles = smiles_drugName.loc[name, 'smilesString']

            # handle duplicate indices
            if isinstance(smiles, pd.Series):
                smiles = smiles.iloc[0]

            return smiles

        elif name in smiles_drugNameOfficial.index:
            print(f'{name} found in smiles_drugNameOfficial')

            smiles = smiles_drugNameOfficial.loc[name, 'smilesString']

            # handle duplicate indices
            if isinstance(smiles, pd.Series):
                smiles = smiles.iloc[0]

            return smiles

    return None

In [36]:
test_names = get_names(test_id)

In [37]:
get_smiles(test_names)

5-fu found in smiles_drugName

'C1=C(C(=O)NC(=O)N1)F'

In [38]:
dbids = (
    set(fold_splits['drug1_dbid'].dropna().unique()) |
    set(fold_splits['drug2_dbid'].dropna().unique())
)
len(dbids)

1092

In [42]:
smiles_list = []
no_ids = 0
no_smiles = 0
no_smiles_dbids = []
for id in dbids:
    names = get_names(id)
    if names is None:
        no_ids += 1
        print(f'[NO NAME] id: {id}')
        continue
    
    smiles = get_smiles(names)
    if smiles is None or pd.isna(smiles):
        no_smiles += 1
        no_smiles_dbids.append(id)
        print(f'[NO SMILES] id: {id}, names: {names}')
        continue
    smiles_list.append(smiles)

[NO SMILES] id: DB00863, names: ranitidine
[NO SMILES] id: DB01626, names: pargyline
[NO SMILES] id: DB00962, names: zaleplon
valdecoxib found in smiles_drugName
cilengitide found in smiles_drugName
salicin found in smiles_drugName
estradiol found in smiles_drugName
[NO SMILES] id: DB00961, names: mepivacaine hcl
thiabendazole found in smiles_drugName
cytidine found in smiles_drugName
epalrestat found in smiles_drugName
[NO SMILES] id: DB15293, names: drugbank_id
DB15293    epalrestat
DB15293    epalrestat
Name: name_norm, dtype: object
argatroban found in smiles_drugName
[NO SMILES] id: DB00691, names: moexipril hcl
tioxolone found in smiles_drugName
[NO SMILES] id: DB01239, names: chlorprothixene
colchicine found in smiles_drugName
[NO SMILES] id: DB00607, names: nafcillin sodium
proparacaine found in smiles_drugName
ixabepilone found in smiles_drugName
tropisetron found in smiles_drugName
[NO SMILES] id: DB11699, names: drugbank_id
DB11699    tropisetron
DB11699    tropisetron
Name: name_norm, dtype: object
[NO SMILES] id: DB00946, names: phenprocoumon
albendazole oxide found in smiles_drugName
indirubin found in smiles_drugName
[NO SMILES] id: DB12379, names: drugbank_id
DB12379    indirubin
DB12379    indirubin
Name: name_norm, dtype: object
ritonavir found in smiles_drugName
levosulpiride found in smiles_drugName
bicalutamide found in smiles_drugName
prednisolone found in smiles_drugName
[NO SMILES] id: DB00911, names: tinidazole
[NO SMILES] id: DB00894, names: testolactone
[NO SMILES] id: DB00719, names: azatadine
ranolazine found in smiles_drugName
[NO SMILES] id: DB00763, names: methimazole
macitentan found in smiles_drugName
vardenafil found in smiles_drugName
[NO SMILES] id: DB00862, names: drugbank_id
DB00862    vardenafil hcl trihydrate
DB00862                   vardenafil
Name: name_norm, dtype: object
[NO SMILES] id: DB13262, names: aceclidine hcl
[NO SMILES] id: DB00792, names: tripelennamine hcl
formestane found in smiles_drugName
[NO SMILES] id: DB06314, names: sgx-523
indomethacin found in smiles_drugName
nimesulide found in smiles_drugName
pralatrexate found in smiles_drugName
cediranib found in smiles_drugName
quinine found in smiles_drugName
[NO SMILES] id: DB00468, names: drugbank_id
DB00468                  quinine
DB00468    quinine hcl dihydrate
DB00468                  quinine
Name: name_norm, dtype: object
[NO SMILES] id: DB06264, names: tolperisone hcl
[NO SMILES] id: DB00387, names: procyclidine hcl
nitrofurazone found in smiles_drugName
methotrexate found in smiles_drugName
podophyllotoxin found in smiles_drugNameOfficial
atovaquone found in smiles_drugName
ramipril found in smiles_drugName
[NO SMILES] id: DB00232, names: methyclothiazide
moxifloxacin hydrochloride found in smiles_drugName
[NO SMILES] id: DB14507, names: lithium citrate
[NO SMILES] id: DB01264, names: darunavir
[NO SMILES] id: DB00179, names: masoprocol
cortisone acetate found in smiles_drugName
acitretin found in smiles_drugName
[NO SMILES] id: DB13791, names: penfluridol
methacycline hydrochloride found in smiles_drugName
[NO SMILES] id: DB00931, names: drugbank_id
DB00931              methacycline hcl
DB00931    methacycline hydrochloride
Name: name_norm, dtype: object
nisoldipine found in smiles_drugName
paroxetine found in smiles_drugName
[NO SMILES] id: DB11743, names: ipatasertib
pregnenolone found in smiles_drugName
[NO SMILES] id: DB16702, names: famprofazone
ginkgolide a found in smiles_drugName
[NO SMILES] id: DB11556, names: detomidine hcl
[NO SMILES] id: DB01150, names: cefprozil monohydrate
orphenadrine hydrochloride found in smiles_drugName
[NO SMILES] id: DB01173, names: drugbank_id
DB01173          orphenadrine citrate
DB01173                  orphenadrine
DB01173    orphenadrine hydrochloride
Name: name_norm, dtype: object
[NO SMILES] id: DB00939, names: meclofenamic acid
[NO SMILES] id: DB06412, names: oxymetholone
ticlopidine hydrochloride found in smiles_drugName
[NO SMILES] id: DB00208, names: drugbank_id
DB00208              ticlopidine hcl
DB00208                  ticlopidine
DB00208    ticlopidine hydrochloride
Name: name_norm, dtype: object
[NO SMILES] id: DB09144, names: uridine triacetate
bazedoxifene found in smiles_drugName
[NO SMILES] id: DB06401, names: drugbank_id
DB06401        bazedoxifene hcl
DB06401            bazedoxifene
DB06401    bazedoxifene acetate
DB06401            bazedoxifene
Name: name_norm, dtype: object
floxuridine found in smiles_drugName
trazodone found in smiles_drugName
5-fu found in smiles_drugName
[NO SMILES] id: DB13036, names: ramatroban
topotecan found in smiles_drugName
[NO SMILES] id: DB01030, names: drugbank_id
DB01030                  topotecan
DB01030    topotecan hydrochloride
DB01030    topotecan hydrochloride
Name: name_norm, dtype: object
[NO SMILES] id: DB00393, names: nimodipine
verapamil found in smiles_drugName
[NO SMILES] id: DB13478, names: meptazinol hcl
stanozolol found in smiles_drugName
desonide found in smiles_drugName
isotretinoin found in smiles_drugName
pioglitazone hydrochloride found in smiles_drugName
[NO SMILES] id: DB01132, names: drugbank_id
DB01132                  pioglitazone
DB01132              pioglitazone hcl
DB01132    pioglitazone hydrochloride
Name: name_norm, dtype: object
[NO SMILES] id: DB08806, names: roxatidine acetate hcl
clinofibrate found in smiles_drugName
[NO SMILES] id: DB04838, names: cyclandelate
dihydromyricetin found in smiles_drugName
[NO SMILES] id: DB06422, names: norcisapride
bortezomib found in smiles_drugName
sibutramine found in smiles_drugNameOfficial
[NO SMILES] id: DB00421, names: spironolactone
geldanamycin found in smiles_drugName
[NO SMILES] id: DB06797, names: mebutamate
chenodeoxycholic acid found in smiles_drugName
[NO SMILES] id: DB06654, names: drugbank_id
DB06654    safinamide mesylate
DB06654             safinamide
Name: name_norm, dtype: object
glipizide found in smiles_drugName
doxercalciferol found in smiles_drugName
[NO SMILES] id: DB01399, names: sasapyrine
enzalutamide found in smiles_drugName
mycophenolic acid found in smiles_drugName
[NO SMILES] id: DB11364, names: pidotimod
tioconazole found in smiles_drugName
[NO SMILES] id: DB11541, names: ractopamine hcl
[NO SMILES] id: DB11663, names: pictilisib
[NO SMILES] id: DB08864, names: rilpivirine
sertraline found in smiles_drugNameOfficial
[NO SMILES] id: DB00299, names: penciclovir
menadione found in smiles_drugName
lomustine found in smiles_drugName
fluocinolone acetonide found in smiles_drugName
[NO SMILES] id: DB00672, names: chlorpropamide
marbofloxacin found in smiles_drugName
[NO SMILES] id: DB16108, names: tak-715
dovitinib found in smiles_drugName
[NO SMILES] id: DB05928, names: drugbank_id
DB05928    dovitinib
DB05928    dovitinib
Name: name_norm, dtype: object
[NO SMILES] id: DB02266, names: flufenamic acid
[NO SMILES] id: DB09020, names: bisacodyl
[NO SMILES] id: DB01250, names: olsalazine sodium
daunorubicin hydrochloride found in smiles_drugName
amuvatinib found in smiles_drugName
fluconazole found in smiles_drugName
icotinib hydrochloride found in smiles_drugName
[NO SMILES] id: DB11737, names: drugbank_id
DB11737                  icotinib
DB11737    icotinib hydrochloride
DB11737    icotinib hydrochloride
Name: name_norm, dtype: object
mometasone furoate found in smiles_drugName
pazopanib found in smiles_drugName
[NO SMILES] id: DB09256, names: tegafur
[NO SMILES] id: DB04879, names: vatalanib
nutlin-3 found in smiles_drugName
tizanidine hydrochloride found in smiles_drugName
[NO SMILES] id: DB00697, names: drugbank_id
DB00697              tizanidine hcl
DB00697                  tizanidine
DB00697    tizanidine hydrochloride
Name: name_norm, dtype: object
miglitol found in smiles_drugName
[NO SMILES] id: DB06061, names: azd-8330
[NO SMILES] id: DB00657, names: mecamylamine
mevastatin found in smiles_drugName
prazosin hydrochloride found in smiles_drugName
[NO SMILES] id: DB00457, names: drugbank_id
DB00457              prazosin hcl
DB00457                  prazosin
DB00457    prazosin hydrochloride
Name: name_norm, dtype: object
[NO SMILES] id: DB00950, names: fexofenadine hcl
[NO SMILES] id: DB00153, names: vitamin d2
rifabutin found in smiles_drugName
[NO SMILES] id: DB00615, names: drugbank_id
DB00615    rifabutin
DB00615    rifabutin
Name: name_norm, dtype: object
rebamipide found in smiles_drugName
protionamide found in smiles_drugName
itraconazole found in smiles_drugName
obatoclax found in smiles_drugName
[NO SMILES] id: DB12191, names: drugbank_id
DB12191    obatoclax mesylate (gx15-070)
DB12191                        obatoclax
Name: name_norm, dtype: object
cinacalcet found in smiles_drugNameOfficial
maprotiline found in smiles_drugName
[NO SMILES] id: DB12424, names: mk-3207
sodium cloxacillin found in smiles_drugName
[NO SMILES] id: DB01147, names: drugbank_id
DB01147    cloxacillin sodium
DB01147    cloxacillin sodium
DB01147    sodium cloxacillin
Name: name_norm, dtype: object
[NO SMILES] id: DB00827, names: cinoxacin
[NO SMILES] id: DB12550, names: taladegib
oxytetracycline found in smiles_drugName
[NO SMILES] id: DB00165, names: pyridoxine hcl
[NO SMILES] id: DB01048, names: abacavir
doramapimod found in smiles_drugName
levonorgestrel found in smiles_drugName
[NO SMILES] id: DB08568, names: a-674563
[NO SMILES] id: DB00954, names: dirithromycin
estriol found in smiles_drugName
[NO SMILES] id: DB01421, names: paromomycin
bosutinib found in smiles_drugName
[NO SMILES] id: DB00529, names: drugbank_id
DB00529           foscarnet
DB00529    foscarnet sodium
Name: name_norm, dtype: object
dinaciclib found in smiles_drugName
[NO SMILES] id: DB00181, names: baclofen
[NO SMILES] id: DB16776, names: tyrphostin ag 879
d-cycloserine found in smiles_drugName
tolnaftate found in smiles_drugName
ulipristal acetate found in smiles_drugName
dichlorphenamide found in smiles_drugName
[NO SMILES] id: DB00948, names: mezlocillin sodium
[NO SMILES] id: DB00662, names: trimethobenzamide
rifaximin found in smiles_drugName
vemurafenib found in smiles_drugName
[NO SMILES] id: DB13407, names: nifenazone
pefloxacin found in smiles_drugName
edaravone found in smiles_drugName
[NO SMILES] id: DB09210, names: piracetam
acipimox found in smiles_drugName
pelitinib found in smiles_drugName
maraviroc found in smiles_drugName
mechlorethamine hydrochloride found in smiles_drugName
[NO SMILES] id: DB00888, names: drugbank_id
DB00888    mechlorethamine hydrochloride
DB00888                  mechlorethamine
DB00888                     chlormethine
Name: name_norm, dtype: object
fluocinonide found in smiles_drugName
cyproterone acetate found in smiles_drugName
lenalidomide found in smiles_drugName
uridine found in smiles_drugName
refametinib found in smiles_drugName
valproic acid found in smiles_drugName
vinorelbine found in smiles_drugName
[NO SMILES] id: DB04703, names: hesperidin
zidovudine found in smiles_drugName
[NO SMILES] id: DB00732, names: atracurium besylate
a77 1726 found in smiles_drugName
azithromycin found in smiles_drugName
[NO SMILES] id: DB12879, names: omigapil
quercetin found in smiles_drugName
dydrogesterone found in smiles_drugName
lansoprazole found in smiles_drugName
teniposide found in smiles_drugName
estramustine found in smiles_drugName
doxycycline found in smiles_drugName
ponatinib found in smiles_drugName
cefoperazone sodium found in smiles_drugName
[NO SMILES] id: DB01329, names: drugbank_id
DB01329                  cefoperazone
DB01329           cefoperazone sodium
DB01329           cefoperazone sodium
DB01329    cefoperazone (sodium salt)
Name: name_norm, dtype: object
trioxsalen found in smiles_drugName
pemetrexed found in smiles_drugName
[NO SMILES] id: DB00642, names: drugbank_id
DB00642             pemetrexed
DB00642             pemetrexed
DB00642    pemetrexed disodium
Name: name_norm, dtype: object
[NO SMILES] id: DB05546, names: sb-743921
[NO SMILES] id: DB05913, names: osi-930
[NO SMILES] id: DB17058, names: tpca-1
irsogladine maleate found in smiles_drugName
[NO SMILES] id: DB13056, names: drugbank_id
DB13056            irsogladine
DB13056    irsogladine maleate
DB13056    irsogladine maleate
Name: name_norm, dtype: object
ethosuximide found in smiles_drugName
[NO SMILES] id: DB06775, names: carglumic acid
chlormezanone found in smiles_drugName
melphalan found in smiles_drugName
enoxacin found in smiles_drugName
[NO SMILES] id: DB13174, names: rhein
bexarotene found in smiles_drugName
chloramphenicol palmitate found in smiles_drugName
[NO SMILES] id: DB00368, names: norepinephrine
pyrazinamide found in smiles_drugName
flunisolide found in smiles_drugName
[NO SMILES] id: DB00518, names: albendazole
[NO SMILES] id: DB17197, names: amg-900
ofloxacin found in smiles_drugName
[NO SMILES] id: DB15581, names: chrysin
cyclophosphamide found in smiles_drugName
[NO SMILES] id: DB01016, names: glyburide
[NO SMILES] id: DB04871, names: lorcaserin hcl
[NO SMILES] id: DB01124, names: tolbutamide
[NO SMILES] id: DB08874, names: fidaxomicin
hydroxychloroquine found in smiles_drugName
ketoconazole found in smiles_drugName
pimobendan found in smiles_drugName
[NO SMILES] id: DB00908, names: quinidine
[NO SMILES] id: DB00738, names: pentamidine
chlorambucil found in smiles_drugName
methoxsalen found in smiles_drugName
isoproterenol found in smiles_drugName
clorsulon found in smiles_drugName
lactulose found in smiles_drugName
[NO SMILES] id: DB00226, names: guanadrel
[NO SMILES] id: DB00063, names: eptifibatide
[NO SMILES] id: DB00855, names: aminolevulinic acid hydrochloride
istradefylline found in smiles_drugName
silmitasertib found in smiles_drugName
fludarabine base found in smiles_drugName
synephrine found in smiles_drugName
sparfloxacin found in smiles_drugName
[NO SMILES] id: DB00252, names: drugbank_id
DB00252           phenytoin
DB00252    phenytoin sodium
Name: name_norm, dtype: object
sotrastaurin found in smiles_drugName
idebenone found in smiles_drugName
resminostat found in smiles_drugName
homoharringtonine found in smiles_drugNameOfficial
biperiden found in smiles_drugName
hydrochlorothiazide found in smiles_drugName
ly2157299 found in smiles_drugName
[NO SMILES] id: DB00419, names: miglustat
arecoline found in smiles_drugName
salbutamol sulfate found in smiles_drugName
terbinafine hydrochloride found in smiles_drugName
[NO SMILES] id: DB00857, names: drugbank_id
DB00857                  terbinafine
DB00857              terbinafine hcl
DB00857    terbinafine hydrochloride
Name: name_norm, dtype: object
masitinib found in smiles_drugName
[NO SMILES] id: DB11725, names: latrepirdine hydrochloride
iniparib found in smiles_drugName
oxfendazole found in smiles_drugName
dabrafenib found in smiles_drugName
[NO SMILES] id: DB12686, names: pha-793887
[NO SMILES] id: DB09009, names: articaine hcl
tolvaptan found in smiles_drugName
4-aminosalicylic acid found in smiles_drugName
laquinimod found in smiles_drugName
[NO SMILES] id: DB06685, names: drugbank_id
DB06685    laquinimod
DB06685    laquinimod
Name: name_norm, dtype: object
bimatoprost found in smiles_drugName
mercaptopurine found in smiles_drugName
anacetrapib found in smiles_drugName
gimeracil found in smiles_drugName
[NO SMILES] id: DB09257, names: drugbank_id
DB09257    gimeracil
DB09257    gimeracil
Name: name_norm, dtype: object
tofacitinib found in smiles_drugName
quizartinib found in smiles_drugName
[NO SMILES] id: DB00604, names: cisapride
chloroxine found in smiles_drugName
[NO SMILES] id: DB05198, names: cyc116
[NO SMILES] id: DB00532, names: mephenytoin
pomalidomide found in smiles_drugName
zonisamide found in smiles_drugName
raloxifene found in smiles_drugName
crotamiton found in smiles_drugName
testosterone found in smiles_drugName
artemether found in smiles_drugName
alisertib found in smiles_drugName
aminophylline found in smiles_drugNameOfficial
amoxapine found in smiles_drugName
licofelone found in smiles_drugName
dihydroartemisinin found in smiles_drugName
[NO SMILES] id: DB12774, names: azd-8055
[NO SMILES] id: DB17021, names: jq1
hydralazine found in smiles_drugName
[NO SMILES] id: DB11259, names: diosmetin
[NO SMILES] id: DB00645, names: dyclonine hcl
estrone found in smiles_drugName
phenylephrine hydrochloride found in smiles_drugName
[NO SMILES] id: DB00388, names: drugbank_id
DB00388              phenylephrine hcl
DB00388                  phenylephrine
DB00388    phenylephrine hydrochloride
Name: name_norm, dtype: object
saxagliptin found in smiles_drugName
deferasirox found in smiles_drugName
[NO SMILES] id: DB01609, names: drugbank_id
DB01609    deferasirox
DB01609    deferasirox
Name: name_norm, dtype: object
fingolimod found in smiles_drugNameOfficial
artesunate found in smiles_drugName
[NO SMILES] id: DB11738, names: rilmenidine
[NO SMILES] id: DB16891, names: enmd-981693
[NO SMILES] id: DB01085, names: pilocarpine hcl
carmofur found in smiles_drugName
clozapine found in smiles_drugName
[NO SMILES] id: DB00363, names: drugbank_id
DB00363    clozapine
DB00363    clozapine
DB00363    clozapine
Name: name_norm, dtype: object
betamethasone found in smiles_drugName
budesonide found in smiles_drugName
rifampin found in smiles_drugName
[NO SMILES] id: DB01045, names: drugbank_id
DB01045      rifampin
DB01045    rifampicin
Name: name_norm, dtype: object
[NO SMILES] id: DB00706, names: tamsulosin hydrochloride
oxaliplatin found in smiles_drugName
[NO SMILES] id: DB00526, names: drugbank_id
DB00526    oxaliplatin
DB00526    oxaliplatin
Name: name_norm, dtype: object
2-iminobiotin found in smiles_drugName
azacitidine found in smiles_drugName
cabozantinib found in smiles_drugName
saracatinib found in smiles_drugName
thiotepa found in smiles_drugName
palbociclib found in smiles_drugName
lovastatin found in smiles_drugName
tacrine found in smiles_drugName
terazosin found in smiles_drugName
ispinesib found in smiles_drugName
[NO SMILES] id: DB06188, names: drugbank_id
DB06188    ispinesib (sb-715992)
DB06188                ispinesib
Name: name_norm, dtype: object
[NO SMILES] id: DB15795, names: adiphenine hcl
nicorandil found in smiles_drugName
perifosine found in smiles_drugName
posaconazole found in smiles_drugName
iloperidone found in smiles_drugName
tacedinaline found in smiles_drugName
stavudine found in smiles_drugName
trilostane found in smiles_drugName
[NO SMILES] id: DB13022, names: ly-2874455
kinetin found in smiles_drugName
carisoprodol found in smiles_drugName
[NO SMILES] id: DB13155, names: esculin
flunarizine found in smiles_drugName
rolipram found in smiles_drugName
vancomycin hydrochloride found in smiles_drugName
mocetinostat found in smiles_drugName
meclinertant found in smiles_drugName
valaciclovir found in smiles_drugName
[NO SMILES] id: DB00577, names: drugbank_id
DB00577    valaciclovir hcl
DB00577        valacyclovir
DB00577        valaciclovir
Name: name_norm, dtype: object
digoxin found in smiles_drugName
icariin found in smiles_drugName
salinomycin found in smiles_drugName
[NO SMILES] id: DB09216, names: tolfenamic acid
wp1066 found in smiles_drugNameOfficial
calcitriol found in smiles_drugName
[NO SMILES] id: DB00345, names: 4-aminohippuric acid
primidone found in smiles_drugName
tranexamic acid found in smiles_drugName
conivaptan hydrochloride found in smiles_drugName
[NO SMILES] id: DB00872, names: drugbank_id
DB00872              conivaptan hcl
DB00872                  conivaptan
DB00872    conivaptan hydrochloride
Name: name_norm, dtype: object
efavirenz found in smiles_drugName
allopurinol found in smiles_drugName
[NO SMILES] id: DB00437, names: drugbank_id
DB00437    allopurinol
DB00437    allopurinol
DB00437    allopurinol
Name: name_norm, dtype: object
[NO SMILES] id: DB13785, names: dropropizine
hydroxyurea found in smiles_drugName
bardoxolone methyl found in smiles_drugName
brivanib found in smiles_drugName
[NO SMILES] id: DB09232, names: cilnidipine
20-hydroxyecdysone found in smiles_drugName
triciribine found in smiles_drugName
meprednisone found in smiles_drugName
ribitol found in smiles_drugName

In [45]:
print(f"No ids: {no_ids}")
print(f"No smiles: {no_smiles}")
no_smiles_dbids

No ids: 0
No smiles: 481

['DB00863',
 'DB01626',
 'DB00962',
 'DB00961',
 'DB15293',
 'DB00691',
 'DB01239',
 'DB00607',
 'DB11699',
 'DB00946',
 'DB12379',
 'DB00911',
 'DB00894',
 'DB00719',
 'DB00763',
 'DB00862',
 'DB13262',
 'DB00792',
 'DB06314',
 'DB00468',
 'DB06264',
 'DB00387',
 'DB00232',
 'DB14507',
 'DB01264',
 'DB00179',
 'DB13791',
 'DB00931',
 'DB11743',
 'DB16702',
 'DB11556',
 'DB01150',
 'DB01173',
 'DB00939',
 'DB06412',
 'DB00208',
 'DB09144',
 'DB06401',
 'DB13036',
 'DB01030',
 'DB00393',
 'DB13478',
 'DB01132',
 'DB08806',
 'DB04838',
 'DB06422',
 'DB00421',
 'DB06797',
 'DB06654',
 'DB01399',
 'DB11364',
 'DB11541',
 'DB11663',
 'DB08864',
 'DB00299',
 'DB00672',
 'DB16108',
 'DB05928',
 'DB02266',
 'DB09020',
 'DB01250',
 'DB11737',
 'DB09256',
 'DB04879',
 'DB00697',
 'DB06061',
 'DB00657',
 'DB00457',
 'DB00950',
 'DB00153',
 'DB00615',
 'DB12191',
 'DB12424',
 'DB01147',
 'DB00827',
 'DB12550',
 'DB00165',
 'DB01048',
 'DB08568',
 'DB00954',
 'DB01421',
 'DB00529',
 'DB00181',
 'DB16776',
 'DB00948',
 'DB00662',
 'DB13407',
 'DB09210',
 'DB00888',
 'DB04703',
 'DB00732',
 'DB12879',
 'DB01329',
 'DB00642',
 'DB05546',
 'DB05913',
 'DB17058',
 'DB13056',
 'DB06775',
 'DB13174',
 'DB00368',
 'DB00518',
 'DB17197',
 'DB15581',
 'DB01016',
 'DB04871',
 'DB01124',
 'DB08874',
 'DB00908',
 'DB00738',
 'DB00226',
 'DB00063',
 'DB00855',
 'DB00252',
 'DB00419',
 'DB00857',
 'DB11725',
 'DB12686',
 'DB09009',
 'DB06685',
 'DB09257',
 'DB00604',
 'DB05198',
 'DB00532',
 'DB12774',
 'DB17021',
 'DB11259',
 'DB00645',
 'DB00388',
 'DB01609',
 'DB11738',
 'DB16891',
 'DB01085',
 'DB00363',
 'DB01045',
 'DB00706',
 'DB00526',
 'DB06188',
 'DB15795',
 'DB13022',
 'DB13155',
 'DB00577',
 'DB09216',
 'DB00345',
 'DB00872',
 'DB00437',
 'DB13785',
 'DB09232',
 'DB06799',
 'DB00760',
 'DB00765',
 'DB11376',
 'DB08052',
 'DB13048',
 'DB06021',
 'DB13247',
 'DB00796',
 'DB12484',
 'DB00717',
 'DB13072',
 'DB01086',
 'DB00784',
 'DB05944',
 'DB12200',
 'DB01050',
 'DB05243',
 'DB01143',
 'DB12137',
 'DB00814',
 'DB09419',
 'DB08356',
 'DB01396',
 'DB01181',
 'DB00412',
 'DB13024',
 'DB11960',
 'DB12645',
 'DB11413',
 'DB15911',
 'DB02959',
 'DB00285',
 'DB13919',
 'DB00804',
 'DB12047',
 'DB00356',
 'DB07118',
 'DB00819',
 'DB11372',
 'DB04335',
 'DB01597',
 'DB00330',
 'DB01581',
 'DB00485',
 'DB00321',
 'DB00633',
 'DB06694',
 'DB12245',
 'DB00261',
 'DB00335',
 'DB00168',
 'DB06145',
 'DB12235',
 'DB13284',
 'DB13835',
 'DB00758',
 'DB15049',
 'DB17428',
 'DB13740',
 'DB12380',
 'DB09026',
 'DB00967',
 'DB01182',
 'DB08877',
 'DB01231',
 'DB00851',
 'DB12558',
 'DB00750',
 'DB03419',
 'DB01698',
 'DB09242',
 'DB12750',
 'DB13726',
 'DB06169',
 'DB12618',
 'DB02520',
 'DB00236',
 'DB12979',
 'DB15582',
 'DB00883',
 'DB00614',
 'DB12831',
 'DB13551',
 'DB00442',
 'DB11886',
 'DB00660',
 'DB00668',
 'DB01638',
 'DB00326',
 'DB00751',
 'DB00126',
 'DB00791',
 'DB12319',
 'DB06155',
 'DB00440',
 'DB00856',
 'DB03793',
 'DB17030',
 'DB00471',
 'DB17053',
 'DB12174',
 'DB00622',
 'DB16567',
 'DB12852',
 'DB00494',
 'DB00952',
 'DB12848',
 'DB00759',
 'DB05482',
 'DB06695',
 'DB12904',
 'DB00187',
 'DB00486',
 'DB00477',
 'DB08963',
 'DB00832',
 'DB04961',
 'DB00889',
 'DB11511',
 'DB00498',
 'DB06700',
 'DB11974',
 'DB11748',
 'DB00673',
 'DB06762',
 'DB01582',
 'DB00787',
 'DB01115',
 'DB04847',
 'DB16824',
 'DB00987',
 'DB03585',
 'DB00836',
 'DB05936',
 'DB00762',
 'DB00711',
 'DB08799',
 'DB00441',
 'DB00972',
 'DB12064',
 'DB12529',
 'DB05050',
 'DB02600',
 'DB01607',
 'DB01219',
 'DB12611',
 'DB03754',
 'DB13536',
 'DB17379',
 'DB09075',
 'DB00679',
 'DB00935',
 'DB01118',
 'DB00185',
 'DB05424',
 'DB16739',
 'DB00353',
 'DB01218',
 'DB01037',
 'DB01156',
 'DB15399',
 'DB00342',
 'DB12802',
 'DB00968',
 'DB01268',
 'DB11851',
 'DB17046',
 'DB18024',
 'DB05552',
 'DB13510',
 'DB00675',
 'DB06413',
 'DB00514',
 'DB14674',
 'DB14065',
 'DB05500',
 'DB00377',
 'DB01088',
 'DB00277',
 'DB08142',
 'DB07941',
 'DB16828',
 'DB01023',
 'DB00391',
 'DB15477',
 'DB06097',
 'DB12661',
 'DB12241',
 'DB15589',
 'DB00585',
 'DB13318',
 'DB01014',
 'DB09341',
 'DB00692',
 'DB00414',
 'DB17062',
 'DB09079',
 'DB00551',
 'DB00461',
 'DB12332',
 'DB00244',
 'DB09063',
 'DB09516',
 'DB17015',
 'DB00703',
 'DB00400',
 'DB00483',
 'DB00460',
 'DB11901',
 'DB17023',
 'DB00402',
 'DB03604',
 'DB16837',
 'DB15446',
 'DB04104',
 'DB01119',
 'DB00389',
 'DB00590',
 'DB00674',
 'DB00376',
 'DB00845',
 'DB00296',
 'DB00978',
 'DB01032',
 'DB00513',
 'DB11485',
 'DB04861',
 'DB05695',
 'DB11513',
 'DB00627',
 'DB09268',
 'DB17029',
 'DB04878',
 'DB02115',
 'DB12387',
 'DB02329',
 'DB07905',
 'DB00634',
 'DB01251',
 'DB12556',
 'DB01134',
 'DB04896',
 'DB01018',
 'DB01004',
 'DB00267',
 'DB12863',
 'DB00439',
 'DB00359',
 'DB00176',
 'DB00501',
 'DB06808',
 'DB00289',
 'DB08943',
 'DB13044',
 'DB03209',
 'DB17043',
 'DB17059',
 'DB01248',
 'DB13855',
 'DB01610',
 'DB13124',
 'DB09083',
 'DB04794',
 'DB01169',
 'DB01667',
 'DB17016',
 'DB12302',
 'DB05408',
 'DB16844',
 'DB09019',
 'DB01053',
 'DB14031',
 'DB01435',
 'DB00215',
 'DB01393',
 'DB00225',
 'DB04441',
 'DB07340',
 'DB12116',
 'DB11697',
 'DB01242',
 'DB00450',
 'DB04665',
 'DB14763',
 'DB12731',
 'DB04920',
 'DB06817',
 'DB00914',
 'DB00230',
 'DB06769',
 'DB00613',
 'DB00900',
 'DB01194',
 'DB00282',
 'DB11742',
 'DB06999',
 'DB08972',
 'DB15578',
 'DB00821',
 'DB14014',
 'DB16877',
 'DB00605',
 'DB12221',
 'DB01397',
 'DB00346',
 'DB00308',
 'DB00508',
 'DB01340',
 'DB12745',
 'DB00436',
 'DB12882',
 'DB08816',
 'DB00925',
 'DB08893',
 'DB00325',
 'DB06201',
 'DB01392',
 'DB05470',
 'DB01098',
 'DB12881',
 'DB00384',
 'DB13744',
 'DB13956',
 'DB00559',
 'DB11925',
 'DB00882',
 'DB00319',
 'DB02587',
 'DB09231',
 'DB00268',
 'DB00554',
 'DB00828']

In [52]:
molecules = pd.read_csv(CANONICAL_DATA_DIR_2 + 'drugbank/molecules.csv').set_index('drugbank_id')['smiles'].dropna()
molecules

drugbank_id
DB00006    CC[C@H](C)[C@H](NC(=O)[C@H](CCC(O)=O)NC(=O)[C@...
DB00014    CC(C)C[C@H](NC(=O)[C@@H](COC(C)(C)C)NC(=O)[C@H...
DB00027    CC(C)C[C@@H](NC(=O)CNC(=O)[C@@H](NC=O)C(C)C)C(...
DB00035    NC(=O)CC[C@@H]1NC(=O)[C@H](CC2=CC=CC=C2)NC(=O)...
DB00050    CC(C)C[C@H](NC(=O)[C@@H](CCCNC(N)=O)NC(=O)[C@H...
                                 ...
DB19446    [H][C@@]1(CC[C@@H](CC1)N1CC(C1)OC)[C@@]1(C)OC2...
DB19451    COC(=O)N[C@H](C(=O)N1C[C@@H](C[C@H]1C(=O)N[C@@...
DB19454           CCCCCCCCCCCCCCCCOC(=O)CCCCCCC\C=C/CCCCCCCC
DB19455               CCCCCCCCCCCCCCCCOC(=O)CCCCCCC\C=C/CCCC
DB19456             CCCCCCCCCCCCCCCCOC(=O)CCCCCCC\C=C/CCCCCC
Name: smiles, Length: 12313, dtype: object

In [58]:
missing = 0
for id in no_smiles_dbids:
    smiles = molecules.get(id)
    if smiles is None:
        missing += 1

print(missing)

10

In [41]:
targets = (
            pd.read_csv('/Users/zijiexu/GEMS-LAB/jumpstart_bundle 2/data/protein_features/drug_target.csv')
            .groupby("DrugID (DrugBank ID)")["Drug_Target (Gene Eentrez IDs)"]
            .apply(list)
            .to_dict()
        )

targets

{'DB00001': [2147],
 'DB00002': [2209,
  1956,
  2215,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00004': [3560, 3559, 3561],
 'DB00005': [7124,
  2209,
  2215,
  7133,
  4049,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00006': [2147],
 'DB00007': [2798],
 'DB00008': [3455, 3454],
 'DB00009': [5340, 5054, 2243, 5329],
 'DB00011': [3455, 3454],
 'DB00013': [5340, 5054, 5329, 5328, 4036, 5055, 5327, 6768, 5104, 4811],
 'DB00014': [3973, 2798],
 'DB00015': [5340, 5054, 2243, 5329],
 'DB00017': [799],
 'DB00018': [3455, 3454],
 'DB00019': [1991, 1441],
 'DB00020': [1438, 3563, 5553, 1439, 6383],
 'DB00022': [3455, 3454],
 'DB00025': [2159, 2158, 821, 7450, 3309, 811, 4035, 5264, 433, 3998, 90411],
 'DB00028': [2209, 2215, 2214, 2212, 2213, 9103],
 'DB00029': [5340, 5054, 2243, 5329],
 'DB00030': [3643,
  3480,
  1509,
  4036,
  1363,
  4856,
  3416,
  5925,
  5126,
  5122,
  3490,
  94121],
 'DB00031': [5340, 5054, 2243, 5329, 5055, 821, 302, 7123, 3856, 811, 4035],
 'DB00032': [3973, 2492],
 'DB00033': [3460, 3459],
 'DB00034': [3455, 3454],
 'DB00035': [552, 554, 553],
 'DB00036': [2159, 2155, 2677, 7035, 2152, 3249],
 'DB00039': [2263, 3339, 2264, 8829, 2260, 2261],
 'DB00040': [2642, 2740, 9340],
 'DB00041': [3560, 3559, 3561],
 'DB00042': [6843, 6844, 127833],
 'DB00043': [2205, 2206],
 'DB00044': [3973],
 'DB00045': [7097],
 'DB00046': [3643, 3480],
 'DB00047': [3643, 3480],
 'DB00048': [1277, 1281, 1280, 1278],
 'DB00050': [3973, 2798],
 'DB00051': [7124,
  2209,
  2215,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00052': [2690, 5618],
 'DB00054': [3674,
  2209,
  2215,
  7448,
  3690,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00055': [2157,
  2153,
  2147,
  5054,
  2677,
  5627,
  5196,
  1356,
  7056,
  10544,
  5104,
  5269],
 'DB00056': [945, 2209, 2215, 716, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00058': [1991],
 'DB00060': [3455, 3454],
 'DB00062': [259, 348, 6288],
 'DB00063': [3690],
 'DB00064': [259, 348, 6288],
 'DB00065': [7124],
 'DB00066': [2492],
 'DB00067': [552, 554, 553],
 'DB00068': [3455, 3454],
 'DB00069': [3455, 3454],
 'DB00071': [3643,
  3480,
  1509,
  4036,
  1363,
  4856,
  3416,
  3118,
  5925,
  5126,
  5122,
  3490,
  94121],
 'DB00072': [2064,
  2209,
  1956,
  2215,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00073': [931, 2209, 2215, 716, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00074': [3560,
  3559,
  2209,
  2215,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00075': [916,
  2209,
  2215,
  716,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103,
  915,
  917,
  919],
 'DB00078': [931, 2209, 2215, 716, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00081': [931, 2209, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00082': [2690],
 'DB00083': [6616, 388],
 'DB00086': [5340, 2149],
 'DB00087': [1043, 2209, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00089': [2346],
 'DB00091': [819, 5478, 5535],
 'DB00092': [2209, 914, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00093': [552],
 'DB00094': [2492],
 'DB00095': [3683, 2209, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00097': [3973, 2492],
 'DB00098': [3683, 909, 942, 3690, 2213, 920, 3140, 3688, 3685],
 'DB00099': [1991, 1441],
 'DB00100': [2157, 2147, 2159, 2155, 2677, 2160, 4035],
 'DB00102': [5159, 5156, 2],
 'DB00104': [6751, 6755, 6752],
 'DB00105': [3455, 3454],
 'DB00106': [2798],
 'DB00107': [5020, 5021],
 'DB00108': [3676,
  2209,
  2215,
  3383,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00110': [2209, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00111': [3560,
  3559,
  2209,
  2215,
  715,
  712,
  713,
  714,
  2214,
  2212,
  2213,
  9103],
 'DB00112': [7422, 2209, 2215, 715, 712, 713, 714, 2214, 2212, 2213, 9103],
 'DB00113': [634],
 'DB00114': [3067,
  5836,
  51380,
  64902,
  9054,
  10993,
  55163,
  18,
  883,
  57026,
  6472,
  189,
  875,
  6470,
  2571,
  2806,
  63826,
  8942,
  4953,
  211,
  4942,
  10558,
  113451,
  79896,
  586,
  23464,
  2805,
  29968,
  2731,
  9517,
  2875,
  6898,
  587,
  51166,
  8879,
  1491,
  10841,
  5837,
  11212,
  5834,
  1644,
  2572,
  23042,
  56267,
  339896,
  85007,
  212,
  84706,
  55034,
  113675,
  51091,
  55304,
  5023],
 'DB00115': [166785, 4548, 4552, 4594, 25974, 4524],
 'DB00116': [275,
  10797,
  6472,
  6470,
  4522,
  4548,
  10841,
  10840,
  471,
  4524,
  123263],
 'DB00117': [3067, 3034, 3035],
 'DB00118': [262, 4144, 875, 27232, 4143, 1312, 5409],
 'DB00119': [5313, 5315, 5162, 64902, 18, 5091],
 'DB00120': [10667, 2193, 10056, 7054, 6898, 5053],
 'DB00121': [64087, 3141, 56922, 5095, 5096, 31, 5091, 32],
 'DB00122': [43, 9468, 5130, 5338, 590, 5337, 162466],
 'DB00123': [3735],
 'DB00125': [4843, 4846, 113451, 435, 445, 384],
 'DB00126': [5033,
  5351,
  1621,
  5264,
  5352,
  8985,
  8424,
  5066,
  64175,
  79676,
  121642,
  55214,
  10536,
  55239,
  112398,
  221120,
  8284,
  54583,
  112399,
  55217,
  54681,
  3938,
  151],
 'DB00127': [4953, 54498, 6611, 762, 765, 763, 835, 766, 23632, 11238],
 'DB00128': [443,
  440,
  2806,
  95,
  444,
  2805,
  445,
  1615,
  10606,
  790,
  159,
  55157,
  80150,
  122622,
  91703,
  6035],
 'DB00129': [383, 5009, 2628, 4946, 4942, 384, 4947, 51686],
 'DB00130': [5471, 1503, 2752],
 'DB00131': [5836,
  5564,
  107,
  55902,
  5142,
  2180,
  5562,
  84532,
  5565,
  1385,
  5292,
  5144,
  3094,
  2203,
  132,
  3939,
  6714,
  134,
  5029,
  5028],
 'DB00132': [3992, 7442, 9415, 6785, 2864, 2170, 5468, 338557],
 'DB00133': [6301, 10993, 189, 875, 63826, 10558, 9517],
 'DB00134': [4548, 4552, 635, 10988, 23743],
 'DB00135': [8565, 51067, 7054, 6898],
 'DB00136': [7421],
 'DB00138': [1497],
 'DB00139': [5033,
  5351,
  7915,
  6389,
  8801,
  444,
  8630,
  8985,
  8424,
  64175,
  55214,
  10536,
  55217,
  6392,
  8974,
  6390,
  8802,
  5019,
  6391,
  56670,
  64064,
  8803,
  54583],
 'DB00140': [55312, 645],
 'DB00141': [5973, 2683, 4669, 8703, 8702, 8704, 55577, 51172],
 'DB00142': [27165,
  10157,
  2729,
  2746,
  2058,
  440,
  18,
  8833,
  2897,
  2902,
  2571,
  2806,
  2906,
  2677,
  2904,
  2905,
  586,
  2805,
  116444,
  2346,
  2572,
  29968,
  2730,
  2890,
  116443,
  2875,
  6898,
  2356,
  587,
  51166,
  2747,
  2903,
  10841,
  5832,
  2911,
  2744,
  2898,
  2900,
  2901,
  2891,
  2893,
  2892,
  2899,
  2914,
  2917,
  2918,
  56267,
  84706,
  5198,
  5188,
  2752,
  55191,
  26873,
  2895,
  2028,
  124454,
  51557,
  162417,
  23549,
  2894],
 'DB00143': [2937,
  2936,
  2944,
  373156,
  2940,
  2947,
  2941,
  2948,
  221357,
  2950,
  9446,
  2876,
  2877,
  2952,
  2954,
  2880,
  2878,
  2678,
  2739,
  4056,
  2879,
  27306,
  2946,
  3029,
  2939,
  4259,
  51060,
  2938,
  4257,
  2098,
  2745,
  2949,
  257202,
  493869,
  2882,
  4258,
  119391,
  51022],
 'DB00144': [949, 23761, 10396, 9791, 5578, 1608, 8527, 81490, 55627, 55512],
 'DB00145': [2743,
  64902,
  2937,
  6472,
  189,
  6470,
  2628,
  27232,
  211,
  8001,
  2741,
  2905,
  23464,
  116444,
  2731,
  2742,
  2903,
  212,
  2617,
  2653,
  570,
  2841,
  10249,
  219970,
  92292,
  51268],
 'DB00146': [7421],
 'DB00147': [8566],
 'DB00148': [1152, 548596, 1160, 2593, 1158],
 'DB00149': [23395, 51451, 586, 9836, 587, 51520],
 'DB00150': [7453, 10352],
 'DB00151': [51380,
  9054,
  2729,
  2937,
  875,
  2805,
  1036,
  2730,
  833,
  1491,
  4255,
  79587],
 'DB00152': [27010],
 'DB00153': [7421],
 'DB00154': [5742, 5743, 165140],
 'DB00155': [4843,
  4842,
  4846,
  5009,
  23564,
  445,
  23576,
  23569,
  353238,
  29943,
  51702,
  11240],
 'DB00156': [6897, 79896, 80222],
 'DB00157': [3294,
  23530,
  128,
  275,
  3419,
  4731,
  1717,
  4728,
  50814,
  3283,
  3284,
  1737,
  3945,
  10157,
  4705,
  4725,
  4726,
  6307,
  5162,
  92483,
  1645,
  11112,
  3291,
  217,
  501,
  4729,
  4200,
  3948,
  7915,
  1727,
  26227,
  4967,
  4697,
  4718,
  622,
  2746,
  51478,
  4722,
  222,
  3292,
  2819,
  4700,
  4835,
  4694,
  5831,
  124,
  4329,
  4711,
  8659,
  4716,
  7299,
  3030,
  10797,
  4709,
  223,
  4710,
  160287,
  6652,
  4704,
  374291,
  4717,
  3028,
  56901,
  10873,
  3290,
  1719,
  3293,
  4707,
  9563,
  127,
  4702,
  4712,
  3033,
  125,
  4701,
  3295,
  3939,
  4708,
  1109,
  221,
  126,
  4698,
  219,
  4723,
  4719,
  4724,
  4713,
  8854,
  131,
  51079,
  5860,
  126328,
  2597,
  4706,
  4695,
  3248,
  216,
  3420,
  1036,
  5959,
  5160,
  3156,
  7923,
  220,
  1962,
  3163,
  4190,
  8644,
  645,
  4715,
  224,
  4199,
  5161,
  4522,
  1646,
  7358,
  2936,
  7264,
  4714,
  4696,
  218,
  26330,
  3615,
  29920,
  4720,
  3162,
  1738,
  644,
  231,
  55967,
  2747,
  3614,
  35,
  3421,
  4191],
 'DB00159': [5742, 5468, 5743, 2864, 3992, 2182, 5467, 7442, 2181, 165140],
 'DB00160': [64902, 9054, 18, 16, 189, 8942, 2875, 85007, 84706, 57505],
 'DB00161': [7407, 586, 5096],
 'DB00162': [10901,
  5949,
  5947,
  8854,
  216,
  5959,
  220,
  112724,
  145226,
  6017,
  9227,
  9249,
  54884,
  51109,
  57665,
  50700,
  5950],
 'DB00163': [284904, 240, 23541, 266629, 5579, 8856, 5578, 1606, 5516, 5515],
 'DB00165': [8566, 501, 57026, 875],
 'DB00167': [3376, 586, 36, 587, 55699],
 'DB00169': [7421],
 'DB00170': [2147,
  2159,
  4835,
  2155,
  2158,
  5624,
  2677,
  8858,
  79001,
  632,
  5627,
  1728,
  154807,
  3620,
  7052,
  4129,
  994,
  316],
 'DB00171': [25,
  157,
  19,
  10939,
  8883,
  6833,
  440,
  22978,
  90,
  107,
  317,
  156,
  55902,
  207,
  369,
  27,
  65061,
  94,
  10060,
  2180,
  91,
  445,
  269,
  5562,
  8647,
  84532,
  439,
  10188,
  5243,
  1244,
  9619,
  5029,
  5028,
  9261,
  5023,
  5030,
  5024,
  2840,
  5032,
  5025],
 'DB00172': [5033,
  2058,
  5831,
  29920,
  5478,
  10105,
  11212,
  64175,
  55214,
  10536,
  8974,
  5625,
  10465,
  5479,
  5480,
  9360,
  25973,
  112849],
 'DB00173': [353, 32, 4507, 55825, 52, 6733],
 'DB00174': [440, 4677, 80150, 79731],
 'DB00176': [6532, 6531],
 'DB00177': [185],
 'DB00178': [1636],
 'DB00179': [240, 3480, 1588, 239],
 'DB00180': [2908],
 'DB00181': [2550, 9568],
 'DB00182': [9607, 134864, 3350, 1548, 6530, 6532, 6531],
 'DB00184': [57053,
  1135,
  1137,
  1141,
  1139,
  55584,
  1143,
  1136,
  1138,
  8973,
  1142],
 'DB00185': [1131, 1128],
 'DB00186': [2569,
  2555,
  2558,
  2557,
  2556,
  706,
  2559,
  2554,
  2560,
  2562,
  2561,
  2566,
  2565,
  2567,
  2564,
  2568,
  55879,
  2570,
  2563,
  200959],
 'DB00187': [153],
 'DB00188': [5707, 5708, 5689, 5693, 5690],
 'DB00189': [2555, 2558, 2557, 2556, 2559, 2554, 2560, 2562, 2561],
 'DB00191': [4129, 4128, 134864],
 'DB00192': [6331],
 'DB00193': [1131, 4985, 3358, 4986, 116443, 4988, 89832, 6530, 6532],
 'DB00194': [1803],
 'DB00195': [153, 154],
 'DB00196': [1576],
 'DB00197': [5468, 5054, 2182, 2104, 2101, 4129],
 'DB00198': [4663, 4758, 1066, 4759],
 'DB00200': [6947, 166785, 81693, 326625, 4548, 4552, 4594, 8029, 25974],
 'DB00201': [134, 5142, 6261, 135, 43, 3757],
 'DB00202': [1131, 1128, 57053, 1129, 89832],
 'DB00203': [8654, 5148, 5149, 10057, 5146, 28234],
 'DB00204': [3757, 3776, 3768],
 'DB00205': [1719, 55244],
 'DB00208': [64805, 1555, 1557],
 'DB00209': [1128],
 'DB00210': [6257, 5916, 5915, 6256, 5914, 6258],
 'DB00211': [148, 147],
 'DB00212': [5972],
 'DB00213': [6582, 55244, 9429],
 'DB00215': [1128, 6530, 3358, 6532, 148, 3269, 3757],
 'DB00216': [3350, 3357, 3355, 3354, 3363, 3352, 3351],
 'DB00217': [150, 152, 151, 3758],
 'DB00218': [23113, 7153],
 'DB00219': [1128],
 'DB00221': [153, 154],
 'DB00222': [6833, 3758, 3767],
 'DB00223': [2908],
 'DB00227': [3683, 3156, 3066, 8856, 5243],
 'DB00228': [27032, 2741, 513, 3778, 2890, 3736, 2554],
 'DB00230': [773],
 'DB00231': [2569,
  2555,
  2558,
  2557,
  2556,
  706,
  2559,
  2554,
  2560,
  2562,
  2561,
  2566,
  2565,
  2567,
  2564,
  2568,
  55879,
  2570,
  2563,
  200959],
 'DB00232': [759, 760, 762],
 'DB00233': [240, 5743, 30814, 5770],
 'DB00234': [1565, 6530, 3358, 6532],
 'DB00235': [5139, 8654, 5742, 5140],
 'DB00237': [2555, 2558, 2557, 2556, 2559, 2554, 2898, 2891, 1137, 1139],
 'DB00240': [2908],
 'DB00241': [2555, 2558, 2557, 2556, 2559, 2554, 2898, 2891, 1137, 1139],
 'DB00242': [4860, 6240, 5422, 6241, 50484, 5426, 5427, 56655, 54107],
 'DB00244': [5742, 5468, 240, 5743, 4353, 3551],
 'DB00245': [1128, 3269],
 'DB00246': [1812,
  1131,
  1128,
  1816,
  1133,
  150,
  3350,
  3359,
  152,
  1815,
  1132,
  3269,
  3356,
  3354,
  148,
  3358,
  1129,
  151,
  147,
  1814,
  3363,
  3352,
  1813,
  3351,
  3362,
  154,
  153,
  6915,
  6532,
  3757],
 'DB00247': [3350, 3357, 3356, 3358, 3363],
 'DB00248': [1812,
  1816,
  150,
  3350,
  152,
  1815,
  3357,
  3356,
  3358,
  151,
  1814,
  3363,
  3352,
  1813,
  3351],
 'DB00249': [7083],
 'DB00250': [3362],
 'DB00251': [1595],
 'DB00252': [6323, 6331, 1559],
 'DB00253': [2908],
 'DB00255': [2099, 2100, 2104],
 'DB00257': [3783,
  7226,
  1586,
  5243,
  1576,
  1588,
  3738,
  3577,
  554,
  1233,
  3757,
  1595,
  9971],
 'DB00259': [759, 760, 761, 762, 768, 377677],
 'DB00260': [2671],
 'DB00261': [5139, 64805],
 'DB00262': [2936],
 'DB00264': [153, 154, 155],
 'DB00266': [79001, 1728, 1429, 1559, 9159, 2859],
 'DB00268': [1812,
  1816,
  150,
  3350,
  152,
  1815,
  3357,
  3356,
  3358,
  151,
  1814,
  3352,
  1813,
  3351,
  3363],
 'DB00269': [2099],
 'DB00270': [775, 781, 8912, 783, 779, 776, 9254],
 'DB00272': [3274],
 'DB00273': [6323, 760, 2897, 762, 2554, 771, 759, 763, 766, 768, 377677],
 'DB00275': [185],
 'DB00276': [3757, 7153, 6580, 1565, 316],
 'DB00277': [134, 8654, 136, 5139, 5142, 135, 5141],
 'DB00278': [2147],
 'DB00279': [7068, 7067],
 'DB00280': [1131, 1128, 6331, 1129, 3751, 3752, 6582],
 'DB00281': [6336, 6331, 1956, 6335],
 'DB00282': [2224],
 'DB00283': [3269, 6580],
 'DB00284': [8972, 2548, 6476, 279],
 'DB00285': [1129, 150, 1128, 6530, 4886, 3356, 3358, 6532, 3362, 6531],
 'DB00286': [2099],
 'DB00287': [5737],
 'DB00288': [301, 2908],
 'DB00289': [6530, 6532, 6531, 3757],
 'DB00290': [3980, 3978],
 'DB00292': [151, 2554, 1584, 1585],
 'DB00293': [7298, 2356],
 'DB00294': [2099, 5241, 6462],
 'DB00295': [4985, 4986, 4988, 4987],
 'DB00296': [6336],
 'DB00297': [5731, 6336],
 'DB00298': [148, 147, 146],
 'DB00302': [5340],
 'DB00304': [2099, 5241, 6462],
 'DB00306': [2555, 2558, 2557, 2556, 2559, 2554, 2898, 2891, 1137, 1139],
 'DB00307': [6257, 6256, 6258, 5914, 5915, 5916],
 'DB00308': [3757, 3775, 782, 775, 81033, 786, 9424, 781, 90134, 3767],
 'DB00309': [81027],
 'DB00311': [759, 760, 762, 766, 771, 761, 765, 768, 23632],
 'DB00312': [2555, 2558, 2557, 2556, 2559, 2554, 2898, 2891, 1137, 1139],
 'DB00313': [18, 36, 9734, 3065],
 'DB00315': [3350, 3355, 3352, 3351],
 'DB00316': [5742, 5743, 771, 761, 766],
 'DB00317': [1956,
  2580,
  2051,
  8767,
  8986,
  9262,
  6793,
  11200,
  25,
  2064,
  3932,
  5979,
  4233,
  3055,
  2268,
  3815,
  6714,
  5261,
  2065,
  2042,
  4058,
  558,
  3791,
  2322,
  27,
  5601,
  1453,
  1454,
  1022,
  3654,
  5602,
  2044,
  2050,
  2047,
  5607,
  5587,
  2066,
  388228,
  80122,
  50488,
  147746,
  79837,
  4215,
  85443,
  81788,
  9748,
  2872,
  27148,
  51135,
  51701,
  9263,
  285220,
  23043,
  9429,
  10746],
 'DB00318': [4985, 4986, 4988],
 'DB00320': [150, 3357, 3352, 3351, 1576, 55244],
 'DB00321': [1131,
  1128,
  1133,
  150,
  3350,
  1132,
  4985,
  3269,
  3356,
  148,
  1129,
  4986,
  146,
  3736,
  3785,
  4914,
  3751,
  3752,
  1813,
  1812,
  1816,
  6530,
  3274,
  3358,
  6532,
  1814,
  3362,
  6531,
  6331,
  6335,
  6326,
  59340,
  11255],
 'DB00322': [7298],
 'DB00323': [1312],
 'DB00324': [2908],
 'DB00325': [43],
 'DB00327': [4985, 4986, 4988],
 'DB00328': [5742,
  5468,
  5743,
  2739,
  5320,
  145482,
  11251,
  240,
  3576,
  367,
  231,
  6916,
  8644,
  5732,
  9356,
  9376,
  10599],
 'DB00331': [5564],
 'DB00332': [1131, 1128, 1129],
 'DB00333': [57053, 4985, 116443, 4988, 5243, 4986, 3757],
 'DB00334': [1812,
  1131,
  1128,
  1816,
  1133,
  150,
  3350,
  3359,
  152,
  1815,
  1132,
  3269,
  3356,
  3354,
  148,
  3358,
  1129,
  151,
  147,
  1814,
  3363,
  3352,
  1813,
  3351,
  3362,
  3757],
 'DB00335': [153, 154],
 'DB00336': [254958],
 'DB00337': [2280, 2475],
 'DB00338': [1576],
 'DB00340': [1131, 1128, 1133, 1132, 1129],
 'DB00341': [3269],
 'DB00342': [1131, 3757, 3269, 5243, 1576, 1128, 1573],
 'DB00343': [786, 1576],
 'DB00344': [6530, 6532, 6531],
 'DB00345': [9356],
 'DB00346': [148, 147, 146],
 'DB00347': [8913],
 'DB00349': [2569,
  2555,
  2558,
  2557,
  2556,
  2559,
  2554,
  2560,
  2562,
  2561,
  2566,
  2565,
  2567,
  2564,
  2568,
  55879,
  2570,
  2563,
  200959],
 'DB00350': [5742, 3758],
 'DB00351': [5241, 2908],
 'DB00353': [1812, 3354, 3355, 3357],
 'DB00354': [1128, 3269],
 'DB00356': [3778],
 'DB00357': [1588],
 'DB00358': [3039, 135, 3757],
 'DB00360': [7166, 4846, 7054, 5053],
 'DB00361': [203068],
 'DB00363': [1812,
  1131,
  1128,
  59340,
  1133,
  150,
  3350,
  3359,
  152,
  1815,
  1132,
  3269,
  3356,
  3354,
  148,
  3358,
  1129,
  151,
  147,
  1814,
  3363,
  3352,
  50632,
  1813,
  3351,
  3362,
  1816,
  6532,
  3361,
  3757,
  11255],
 'DB00364': [2243, 1950, 2247, 2244, 2266, 643834],
 'DB00365': [23113],
 'DB00366': [1128, 3269],
 'DB00367': [2099, 367, 6715, 5241, 6462],
 'DB00368': [153, 150, 152, 148, 151, 147, 154, 146, 5053, 155, 1813],
 'DB00370': [150,
  3359,
  3269,
  3356,
  3358,
  4986,
  3350,
  1813,
  151,
  152,
  1812,
  6530,
  3363,
  148,
  1814],
 'DB00371': [2555, 2558, 2557, 2556, 2559, 2554],
 'DB00372': [1812, 1815, 1813],
 'DB00373': [153, 154, 155],
 'DB00374': [64805, 5739, 5467, 5734, 5733],
 'DB00376': [1131, 1128, 1133, 1132, 1129],
 'DB00377': [3359],
 'DB00378': [5241],
 'DB00379': [6331, 196, 3757, 6326],
 'DB00380': [7153, 7155],
 'DB00381': [759,
  775,
  781,
  774,
  783,
  779,
  776,
  55799,
  782,
  3776,
  146,
  148,
  147],
 'DB00382': [43, 590, 6582, 1544, 1129, 1268, 1269, 1145, 55244],
 'DB00383': [1131, 1128, 1129],
 'DB00384': [6338, 6337, 6339, 6340],
 'DB00385': [7153],
 'DB00387': [1131, 1128, 1132, 1129, 1133],
 'DB00388': [148, 147, 146],
 'DB00389': [7173],
 'DB00390': [476],
 'DB00391': [1814, 1813, 759, 760, 1815, 763, 766, 768, 11238],
 'DB00392': [1128, 1129, 116443, 590, 43],
 'DB00393': [782, 775, 4306, 783, 779, 785, 778, 784, 776, 196, 8856, 9971],
 'DB00396': [2099,
  5241,
  4306,
  6580,
  6581,
  2908,
  6462,
  367,
  1559,
  151306,
  10280],
 'DB00397': [1812, 153, 150, 148],
 'DB00398': [2324,
  5894,
  2322,
  5159,
  3791,
  3815,
  673,
  10733,
  8767,
  6793,
  25,
  4914,
  3643,
  3932,
  2534,
  1436,
  5979,
  3055,
  3350,
  2268,
  2260,
  6714,
  2321,
  2261,
  1017,
  3356,
  3358,
  1969,
  2042,
  2046,
  2053,
  3363,
  7048,
  1445,
  3357,
  27,
  2444,
  5601,
  3361,
  1452,
  1195,
  2932,
  3362,
  3718,
  3984,
  3985,
  6300,
  2044,
  2050,
  2047,
  2043,
  1018,
  1020,
  7010,
  5607,
  2045,
  5600,
  1432,
  4921,
  91807,
  57551,
  204851,
  147746,
  140469,
  11184,
  9212,
  85366,
  9748,
  10114,
  2872,
  27148,
  285220,
  23043,
  9344,
  11183],
 'DB00399': [2224, 9453],
 'DB00400': [203068],
 'DB00401': [775, 781, 783, 779, 776],
 'DB00402': [2555, 2558, 2556, 706, 2554, 2557],
 'DB00404': [2569,
  2555,
  2558,
  2557,
  2556,
  706,
  2559,
  2554,
  2560,
  2562,
  2561,
  2566,
  2565,
  2567,
  2564,
  2568,
  55879,
  2570,
  2563,
  200959,
  23476,
  5724],
 'DB00405': [3269],
 'DB00407': [462, 3053],
 'DB00408': [1812,
  3356,
  3358,
  1813,
  1129,
  1132,
  3350,
  1133,
  150,
  1128,
  151,
  152,
  1131,
  1815,
  3363,
  148,
  3269,
  1814,
  3362,
  57582,
  59340],
 'DB00409': [10280, 1815, 3356, 1814, 1813, 3350],
 'DB00411': [1128, 1129, 1135, 1132, 1133, 1131],

In [177]:
match_count = 0
missing_count = 0

for id in dbids:
    drug_targets = targets.get(id)
    if drug_targets is None:
        missing_count += 1
        print(f'[No targets] {id}')
    else:
        match_count += 1
        print(f"{id}: {drug_targets}")
    
print(f"matching: {match_count}")
print(f"missing:  {missing_count}")

DB01275: [5033, 8639]
[No targets] DB11450
DB00361: [203068]
[No targets] DB00760
DB01219: [6261]
DB00601: [4128]
[No targets] DB01597
[No targets] DB00931
DB00262: [2936]
[No targets] DB00395
[No targets] DB04944
DB08597: [90, 2280, 658, 3932, 7525, 652, 6714, 2321, 1969, 3791, 2322, 657, 94, 7048, 659, 6195, 8569, 5564]
[No targets] DB00662
[No targets] DB05992
[No targets] DB00448
[No targets] DB11641
[No targets] DB13835
DB02266: [5742, 367, 5743, 8644, 7276, 4353, 1646, 54795]
[No targets] DB14674
[No targets] DB06151
DB08943: [1586]
DB00259: [759, 760, 761, 762, 768, 377677]
DB00807: [6336]
[No targets] DB16886
DB00439: [3156]
[No targets] DB09203
[No targets] DB13871
[No targets] DB00207
[No targets] DB00581
[No targets] DB15578
[No targets] DB08908
[No targets] DB11217
[No targets] DB08867
[No targets] DB12245
[No targets] DB09081
DB00751: [3274, 150, 3269, 3356, 148, 3363, 6582, 55244]
DB04855: [3741, 3757]
[No targets] DB12745
DB00356: [3778]
DB01586: [1646, 6554]
[No targets] DB09419
DB00441: [7298, 6240, 51727]
DB00982: [5914]
[No targets] DB06243
[No targets] DB09415
[No targets] DB01026
DB00701: [1576, 1577]
DB04878: [8972, 2548]
[No targets] DB11389
DB01094: [6646, 4547, 1543, 1432, 1545]
DB00763: [7173]
DB00643: [7846, 10383, 25, 3791]
[No targets] DB09009
DB00734: [1812, 150, 3350, 152, 1815, 3269, 3356, 148, 3358, 151, 147, 1814, 3352, 1813, 154, 1129, 1132, 153, 1128, 6915, 1816, 3351, 3354, 3355, 6532, 3363, 3357, 3362, 3757, 55244, 10280]
DB00440: [7298, 1719]
[No targets] DB06808
[No targets] DB15335
DB00414: [3758]
[No targets] DB13855
DB00443: [2908]
[No targets] DB05767
[No targets] DB12332
DB03585: [30814]
[No targets] DB17379
DB00968: [150, 1491]
DB00590: [3757, 81033, 148, 147, 90134, 146, 150, 152]
DB01024: [3615, 3614, 5468]
DB00331: [5564]
DB00659: [116443, 2911, 2912, 2915, 2913]
DB00719: [3269]
DB01012: [846]
[No targets] DB01265
[No targets] DB06436
DB08865: [658, 10733, 8780, 3551, 8573, 6790, 9201, 4593, 2051, 9175, 6885, 8767, 3717, 9475, 8408, 6793, 23683, 25, 1956, 4914, 3643, 3932, 2534, 2242, 1436, 7525, 4067, 5979, 3480, 4233, 6098, 2268, 100130827, 3815, 6714, 3645, 2241, 2321, 5610, 984, 2041, 2261, 6198, 3716, 1969, 2042, 2046, 4058, 7297, 558, 2868, 7075, 2322, 91, 7046, 7294, 27, 2444, 7535, 6850, 5606, 1022, 640, 3654, 660, 3718, 3984, 3985, 2044, 2050, 2047, 2043, 54101, 7010, 90, 4486, 5747, 695, 7301, 10188, 780, 3702, 1760, 5871, 7786, 10461, 6789, 5562, 5598, 6788, 4214, 6093, 8711, 8737, 9641, 2185, 5587, 2045, 7016, 4916, 4915, 22848, 388228, 80122, 51086, 25989, 25778, 389840, 57551, 8491, 167359, 9706, 50488, 166614, 147746, 255239, 91754, 140901, 140609, 8445, 8999, 11184, 79934, 9212, 10645, 6732, 8394, 4215, 83732, 81788, 23235, 9748, 51347, 55589, 51135, 51765, 285220, 29110, 9344, 238, 26576, 728642, 6795, 10746, 11183, 11213]
DB00541: [203068, 7277]
DB00363: [1812, 1131, 1128, 59340, 1133, 150, 3350, 3359, 152, 1815, 1132, 3269, 3356, 3354, 148, 3358, 1129, 151, 147, 1814, 3363, 3352, 50632, 1813, 3351, 3362, 1816, 6532, 3361, 3757, 11255]
DB00783: [2099, 2100, 8856, 6580, 6581, 2103, 6462, 367, 2101, 316, 2852]
[No targets] DB06630
[No targets] DB12881
[No targets] DB08874
DB00621: [367]
[No targets] DB00238
DB00302: [5340]
DB01132: [5468, 4129]
[No targets] DB01638
[No targets] DB00243
[No targets] DB06623
[No targets] DB06469
DB00836: [773, 801, 4985, 4986, 4988, 5443, 5243, 3269, 7010]
DB00951: [3623, 1557]
DB01380: [2908]
[No targets] DB12852
DB00744: [240, 4048, 241, 2053, 1241]
DB01393: [5465, 5468, 5467]
DB00328: [5742, 5468, 5743, 2739, 5320, 145482, 11251, 240, 3576, 367, 231, 6916, 8644, 5732, 9356, 9376, 10599]
DB00351: [5241, 2908]
DB00669: [3350, 3355, 3352, 3351, 3356, 3358, 3354, 3363, 3359, 3361, 3362, 55244]
DB00609: [3623]
[No targets] DB13478
[No targets] DB01053
[No targets] DB03353
DB00468: [3783, 2815, 6582, 1565]
[No targets] DB14507
DB07931: [1645]
[No targets] DB06266
[No targets] DB01150
[No targets] DB12021
[No targets] DB00225
DB01110: [4843, 3757, 4846, 3783, 81033, 3778, 90134, 10242, 3779, 27094, 27345, 3780, 3781, 3782, 2916, 1586, 5243, 1576, 1588, 1595]
DB06813: [1719]
DB00585: [3274]
[No targets] DB06730
[No targets] DB00359
[No targets] DB12183
[No targets] DB13877
[No targets] DB13726
[No targets] DB14512
DB00471: [240, 10800]
DB05424: [658, 5609, 2580, 2051, 6885, 8767, 9262, 6793, 25, 1956, 2064, 3932, 2534, 7525, 4067, 5979, 4233, 3055, 2268, 3815, 6714, 2321, 2065, 2042, 2046, 4058, 5596, 2322, 1445, 27, 2444, 1453, 1454, 640, 3654, 660, 3718, 5602, 2044, 2050, 2047, 2043, 30811, 695, 3702, 1760, 5871, 5607, 1859, 5753, 2066, 2045, 80122, 120892, 25989, 50488, 147746, 140901, 8445, 4215, 83732, 9748, 2872, 27148, 55589, 51135, 9263, 285220, 23043, 238, 6795, 23387, 10746, 11183, 4216]
[No targets] DB12191
DB01213: [124, 125, 126, 847]
[No targets] DB01607
[No targets] DB00168
DB00465: [5742, 5743]
DB01033: [3251]
[No targets] DB11960
DB00819: [759, 760, 762, 358, 761, 766, 23632, 771, 765, 763, 768, 377677]
[No targets] DB04038
DB01030: [116447, 7150, 3091, 146802, 55244, 9429]
DB00487: [23113, 7153]
DB00993: [3251]
[No targets] DB17062
[No targets] DB15584
[No targets] DB09231
DB00730: [23173]
DB00945: [5742, 1645, 5743]
DB01128: [367, 5241]
[No targets] DB13082
[No targets] DB06188
[No targets] DB11886
DB00724: [51284, 51311]
DB00091: [819, 5478, 5535]
DB00376: [1131, 1128, 1133, 1132, 1129]
DB01037: [4129, 4128]
DB00367: [2099, 367, 6715, 5241, 6462]
[No targets] DB12359
DB01131: [1719]
DB00165: [8566, 501, 57026, 875]
[No targets] DB06641
DB01184: [1814, 1813, 6582, 3757, 55244]
[No targets] DB17197
DB06155: [1268, 1559, 1269, 3757]
[No targets] DB00614
DB01032: [24145, 9356, 9376]
DB01108: [3283, 3284, 2099, 2100]
DB00494: [1312]
DB01238: [1812, 1131, 1128, 1816, 1133, 150, 3350, 3359, 152, 1815, 1132, 3269, 3356, 3354, 148, 3358, 1129, 151, 147, 1814, 3363, 3352, 1813, 3351, 3362, 5582, 154, 5243, 153, 6530, 6532, 3357, 3361, 6531, 3757]
[No targets] DB11725
[No targets] DB01263
DB00675: [2099, 2100, 5243, 1576, 2101, 1555, 3362, 3757, 10682, 10280, 84650, 1717]
[No targets] DB05936
DB00943: [7852]
[No targets] DB09079
[No targets] DB00080
[No targets] DB05695
DB00759: [5621]
[No targets] DB00595
DB01202: [9900, 774]
DB00934: [1131, 1128, 1133, 1132, 3269, 148, 1129, 1813, 1812, 1816, 6530, 6532, 1814, 6531, 11255]
[No targets] DB16844
[No targets] DB00507
[No targets] DB00970
DB00342: [1131, 3757, 3269, 5243, 1576, 1128, 1573]
DB07232: [142, 10038]
[No targets] DB06708
[No targets] DB09019
[No targets] DB01147
[No targets] DB16739
DB00232: [759, 760, 762]
[No targets] DB14763
[No targets] DB13510
DB08820: [1080]
[No targets] DB05015
[No targets] DB09144
DB03754: [262, 7422, 124583, 23590, 79661]
DB01007: [1586]
DB00063: [3690]
DB00554: [5742, 5743, 1576, 9376]
[No targets] DB00828
DB07995: [5566, 5569, 83903, 9475, 9252, 5578, 6198, 207, 208, 1452, 1457, 816, 5592, 91807, 10000]
[No targets] DB00602
DB00920: [3269, 5142, 27115, 5150, 5141, 5144, 5143, 5226, 5151, 8622, 3356, 3358, 3357]
[No targets] DB13262
DB04879: [1956, 1436, 5159, 3815, 2321, 2324, 3791, 1024, 5753, 80122, 23097]
[No targets] DB12848
[No targets] DB11816
DB06288: [3356, 1814, 3363, 1813, 150, 152, 1815, 3352, 3351, 3357, 3362]
[No targets] DB00718
[No targets] DB00567
DB04946: [1129, 1132, 3350, 150, 1128, 1813, 151, 152, 1812, 1815, 1816, 6530, 3352, 3356, 3358, 3363, 3269, 1814, 3362, 6531, 10280]
[No targets] DB12484
DB00984: [367]
[No targets] DB12979
[No targets] DB00299
[No targets] DB00531
[No targets] DB00709
[No targets] DB17021
DB01043: [3359, 2904, 116443, 2903, 89832, 2902]
DB00908: [3757, 3775, 6331, 9424, 5243, 1565]
[No targets] DB00916
[No targets] DB04847
DB01064: [153, 154, 5594, 5295, 155, 5296, 8503, 156]
[No targets] DB15588
[No targets] DB16702
DB04845: [10381]
DB08313: [27306]
DB00952: [3350, 3355, 3352, 3351]
DB00388: [148, 147, 146]
DB01954: [5142, 5144]
DB00400: [203068]
DB00755: [190, 6257, 5916, 8854, 216, 5918, 9052, 6258]
DB07352: [8658, 2099, 1543, 1544, 5243, 367, 5292, 1588, 3292, 4128, 4363, 5743, 2322, 3293, 7498, 5602, 1457, 1021, 1020, 3735, 1432, 1545, 2100, 80351, 50507, 9429]
[No targets] DB09053
[No targets] DB04571
[No targets] DB06697
DB00179: [240, 3480, 1588, 239]
DB00642: [7298, 1719, 2618, 471]
DB00863: [3274]
DB01698: [8644]
DB00338: [1576]
DB07118: [771, 3293, 768]
DB00396: [2099, 5241, 4306, 6580, 6581, 2908, 6462, 367, 1559, 151306, 10280]
DB01179: [203068, 7153, 7277]
DB05076: [5950]
[No targets] DB12221
DB00831: [801, 148, 50632, 1813, 7134, 6275, 1129, 5243, 3350, 150, 151, 152, 1131, 1815, 3356, 3358, 3363, 3269, 1814, 3362, 10682, 10280, 84650]
[No targets] DB11336
DB00490: [3350, 1813, 3356, 3358, 1814, 3357, 3757, 55244, 10280]
DB00909: [8911, 6323, 11280, 6331, 759, 760, 8913, 762, 8912, 6335, 771, 6326, 6328, 6329, 4129, 4128, 768, 761, 763, 11238, 766, 767, 56934, 770, 377677, 23632, 6324, 6327, 55800, 6330, 765]
[No targets] DB06061
DB06335: [1803, 54878, 91039]
DB04690: [7150, 1111, 3178]
[No targets] DB11757
[No targets] DB04854
[No targets] DB17058
DB01009: [5742, 5743, 3577, 9356]
[No targets] DB09274
[No targets] DB09075
[No targets] DB12387
[No targets] DB01105
[No targets] DB16567
DB08932: [1910, 1909]
DB01231: [1131, 1128, 1129]
[No targets] DB11413
DB06999: [673, 658, 10733, 6790, 9201, 2051, 8767, 8576, 9943, 9448, 25, 5894, 3932, 2534, 2242, 1436, 7525, 4067, 3055, 5159, 2268, 3815, 2260, 6714, 5156, 2321, 2263, 3791, 5605, 2322, 7048, 1445, 27, 2444, 6416, 1024, 1195, 1196, 640, 4751, 3984, 3985, 150094, 1455, 5604, 5747, 10188, 780, 5058, 5607, 8737, 93, 5753, 8536, 7016, 4921, 340156, 204851, 50488, 147746, 79858, 8445, 23678, 9212, 55781, 23097, 85443, 23235, 9748, 28996, 6725, 10114, 27148, 51776, 440275, 5298, 23043, 6795, 11183]
[No targets] DB06212
DB01050: [5742, 5743, 9356]
DB00949: [2904, 116443, 2903]
[No targets] DB06264
[No targets] DB12291
DB01156: [1136, 6530, 6532, 6531]
[No targets] DB16891
DB00912: [6833, 5468, 6580]
DB01097: [240, 1723, 2185, 196]
[No targets] DB01008
[No targets] DB06169
DB00495: [7083, 7852]
[No targets] DB00305
DB00615: [3320, 7184]
[No targets] DB13307
DB00613: [3176, 3757]
[No targets] DB13022
[No targets] DB17015
DB00322: [7298]
DB00387: [1131, 1128, 1132, 1129, 1133]
DB08868: [8698, 1901, 1903, 53637]
DB04794: [1586, 1595]
DB08877: [658, 10733, 10494, 8780, 3551, 8573, 2580, 9201, 2051, 1613, 6885, 3717, 9475, 8408, 2081, 9252, 8986, 8576, 9262, 9943, 10298, 25, 4914, 5979, 100130827, 3815, 673, 5261, 1459, 3716, 2042, 4058, 7297, 2868, 7272, 5605, 5599, 6416, 5606, 1452, 1196, 1022, 3654, 4752, 3718, 5347, 1612, 54101, 1457, 5581, 5604, 10188, 1760, 5871, 4214, 5593, 6093, 816, 818, 817, 1859, 659, 8536, 9641, 9833, 6196, 6195, 4638, 6011, 4916, 4915, 5260, 22848, 388228, 80122, 120892, 25989, 389840, 2011, 57551, 7444, 204851, 57118, 9706, 166614, 255239, 140609, 131890, 8445, 57172, 6732, 4215, 83732, 55781, 85443, 81788, 51347, 28996, 10114, 1263, 57396, 2872, 56924, 55589, 10769, 57144, 51765, 5298, 9263, 27347, 29110, 23604, 27330, 9344, 238, 26576, 6795, 815, 22983, 23387, 10746]
DB01067: [6833, 5468, 1576]
DB02587: [2778, 108, 111, 6513, 107]
[No targets] DB09056
[No targets] DB00954
[No targets] DB01058
DB00384: [6338, 6337, 6339, 6340]
[No targets] DB06442
[No targets] DB00512
[No targets] DB12092
DB08816: [64805]
DB06725: [5742, 5743]
[No targets] DB00488
DB00715: [1131, 1128, 1133, 1132, 3356, 1129, 150, 1565, 6530, 6869, 6532, 6531, 5025]
DB00227: [3683, 3156, 3066, 8856, 5243]
DB06772: [81027, 7277]
DB06817: [1230]
[No targets] DB06410
DB00796: [185]
DB00860: [2908, 4306, 367, 2752]
[No targets] DB15579
[No targets] DB00853
DB00604: [3360, 3757, 3359, 3356]
[No targets] DB06309
DB00972: [3269, 1565, 11255]
DB00765: [7054]
[No targets] DB09341
DB02262: [1723]
DB00905: [5731, 8644, 5737, 5733]
[No targets] DB06629
DB00255: [2099, 2100, 2104]
DB00421: [367, 4306, 2099, 2908, 5241, 2100]
[No targets] DB12241
[No targets] DB09010
[No targets] DB05969
DB00196: [1576]
DB00697: [150, 152, 151, 11188]
[No targets] DB01126
[No targets] DB09238
DB00855: [210]
DB00928: [1786]
[No targets] DB13036
DB00215: [1128, 6530, 3358, 6532, 148, 3269, 3757]
[No targets] DB06413
DB00382: [43, 590, 6582, 1544, 1129, 1268, 1269, 1145, 55244]
[No targets] DB13132
DB08882: [1803, 2191]
[No targets] DB00529
[No targets] DB00827
DB00401: [775, 781, 783, 779, 776]
[No targets] DB12200
DB04839: [367]
[No targets] DB00894
DB00518: [7846, 10383]
[No targets] DB00634
DB00268: [1812, 1816, 150, 3350, 152, 1815, 3357, 3356, 3358, 151, 1814, 3352, 1813, 3351, 3363]
DB00997: [7153, 6790, 5243, 4313, 1717]
DB01144: [759, 760, 762, 766, 771, 765, 763, 768, 377677, 23632, 11238]
[No targets] DB19138
[No targets] DB09074
[No targets] DB13346
DB00498: [79001]
DB00633: [150, 146]
[No targets] DB04884
[No targets] DB12174
[No targets] DB12449
[No targets] DB06281
DB00412: [5468, 2182, 5916, 4129, 5467, 5465]
DB01023: [801, 775, 4306, 781, 8912, 7134, 783, 779, 776, 9254, 5153, 5136, 7125, 1080, 9971]
DB07767: [771, 759, 760, 765, 763, 766, 768, 23632]
DB06777: [9971, 6555]
DB00350: [5742, 3758]
DB00925: [150, 152, 801, 148, 151, 154, 6582, 6580, 6581]
[No targets] DB00503
[No targets] DB00339
[No targets] DB09101
DB00489: [3757, 153, 154, 155]
[No targets] DB12181
[No targets] DB17043
[No targets] DB12611
[No targets] DB08911
DB00321: [1131, 1128, 1133, 150, 3350, 1132, 4985, 3269, 3356, 148, 1129, 4986, 146, 3736, 3785, 4914, 3751, 3752, 1813, 1812, 1816, 6530, 3274, 3358, 6532, 1814, 3362, 6531, 6331, 6335, 6326, 59340, 11255]
[No targets] DB05500
DB06616: [10494, 11113, 8780, 5609, 1111, 8573, 2580, 2051, 9175, 6885, 8767, 9891, 3717, 9475, 8408, 5063, 6793, 23683, 5218, 9448, 11200, 25, 1956, 2064, 4914, 3932, 2534, 4869, 2242, 1436, 7525, 4067, 5979, 4233, 3055, 5159, 2268, 494551, 3815, 6714, 5261, 5156, 2241, 2041, 2065, 6198, 1969, 2042, 2046, 2048, 4058, 7297, 7465, 558, 2868, 7075, 5605, 2322, 1445, 4145, 7006, 7294, 27, 2444, 7535, 6850, 6416, 5606, 1452, 1453, 1454, 1195, 1196, 1198, 1022, 640, 3654, 6197, 660, 4751, 3718, 5608, 5347, 2049, 2044, 2050, 2047, 2043, 30811, 150094, 4293, 5127, 5581, 5604, 7010, 5588, 4486, 5747, 5580, 695, 7301, 10188, 780, 3702, 1760, 5871, 7786, 10461, 6789, 5562, 5058, 5607, 5598, 5062, 6788, 4214, 6093, 818, 659, 9641, 2185, 2066, 6196, 4638, 4916, 5585, 5586, 4296, 4915, 5260, 4921, 22848, 80122, 51086, 120892, 25989, 25778, 57551, 11011, 7444, 204851, 57118, 8491, 167359, 9706, 50488, 122011, 147746, 53904, 255239, 79858, 140901, 131890, 202374, 140469, 11184, 65061, 10645, 9088, 8394, 4215, 27102, 83732, 83942, 65975, 85443, 81788, 23235, 9748, 51347, 28996, 6725, 10114, 57396, 27148, 55589, 51135, 51776, 10769, 51765, 440275, 51701, 27347, 285220, 29110, 27330, 23043, 9874, 9344, 238, 26576, 815, 22983, 23387, 10746, 11183, 8428, 4216]
[No targets] DB16108
DB00544: [7298]
[No targets] DB11841
[No targets] DB09073
DB00552: [100]
[No targets] DB18965
[No targets] DB12328
DB01085: [1131, 1128, 1129]
DB00320: [150, 3357, 3352, 3351, 1576, 55244]
DB00249: [7083]
[No targets] DB11656
[No targets] DB13024
[No targets] DB09273
DB01083: [5406, 2194, 8513, 7920, 1268, 7941, 26090, 221955, 747]
[No targets] DB17053
[No targets] DB04865
DB00915: [116443, 1813]
DB01667: [4860]
[No targets] DB12645
DB00482: [5743, 5170, 761, 1559, 5742, 1432]
DB01119: [759, 760, 3778, 3767, 476]
DB01120: [7422, 6833]
DB04725: [9536, 240, 5742, 5743]
[No targets] DB01015
[No targets] DB09268
DB01392: [150, 3350, 152, 3356, 3358, 151, 1814, 3352, 1813, 3351, 1565, 146, 3354, 3355, 6532, 148, 147, 3357]
[No targets] DB11457
[No targets] DB13124
[No targets] DB11485
[No targets] DB11696
[No targets] DB11958
DB00380: [7153, 7155]
DB00679: [1812, 3757, 3356, 148, 147, 1813, 1129, 3350, 150, 151, 152, 1131, 1815, 1816, 3358, 3363, 3269, 1814, 3362]
DB00794: [2555, 2558, 2557, 2556, 2559, 2554, 2898, 2891, 1137, 1139]
DB00695: [760, 3290, 2859]
DB01076: [3156, 1803, 196]
DB00370: [150, 3359, 3269, 3356, 3358, 4986, 3350, 1813, 151, 152, 1812, 6530, 3363, 148, 1814]
DB00594: [6338, 6337, 28988, 41, 6339, 6340, 40, 5328]
[No targets] DB05243
DB00967: [3269]
[No targets] DB13044
DB00814: [5742, 5743]
[No targets] DB00879
[No targets] DB05198
[No targets] DB15582
[No targets] DB00352
[No targets] DB11805
[No targets] DB16288
DB01118: [3757, 153, 8912, 9254]
[No targets] DB16877
[No targets] DB12863
DB00307: [6257, 6256, 6258, 5914, 5915, 5916]
DB04841: [8911, 801, 3269, 8913, 8912, 4988, 4985, 4986, 774]
DB00573: [5742, 5743]
[No targets] DB00265
DB00703: [759, 760, 762, 766]
[No targets] DB11899
DB00136: [7421]
DB00181: [2550, 9568]
DB00378: [5241]
DB00451: [7068, 7067]
DB01251: [6833, 3764]
DB02600: [4663]
DB00377: [3359]
DB01208: [23113, 7153]
[No targets] DB00649
[No targets] DB12064
[No targets] DB11793
DB00731: [6833, 5468]
[No targets] DB11911
DB00810: [1128, 1135, 1129, 1132, 1133, 1131]
[No targets] DB12739
[No targets] DB11963
DB00750: [6331]
DB00600: [7299]
DB00878: [6582, 6580, 6581, 4313, 4318, 146802, 55244]
DB03044: [1432, 5603, 6885, 8767, 6793, 25, 1956, 7124, 4914, 3315, 5579, 3932, 7525, 4067, 5979, 3055, 5159, 2268, 3815, 673, 2321, 2041, 2264, 5594, 1969, 2042, 2046, 2048, 7272, 2324, 3791, 2322, 27, 2444, 5599, 5601, 2932, 1022, 6300, 5602, 2049, 2044, 2050, 2047, 2043, 1020, 7010, 5747, 5580, 8621, 2185, 2045, 5600, 4915, 4921, 50488, 8569, 9748, 2872, 285220, 23043]
[No targets] DB01610
[No targets] DB06626
[No targets] DB00267
[No targets] DB12116
[No targets] DB15477
DB01590: [2475]
DB01234: [4843, 190, 301, 2908, 5319, 5241, 4306, 367, 5743]
DB00551: [4321]
DB01250: [3458, 7172]
[No targets] DB09257
DB02424: [3320, 3326]
DB08806: [3274]
DB00959: [2908]
DB04838: [781, 1066]
[No targets] DB05223
[No targets] DB09083
[No targets] DB01048
[No targets] DB11666
DB00444: [7153]
[No targets] DB12027
[No targets] DB01104
DB00433: [1813, 1129, 150, 1815, 3358, 3269, 1814]
[No targets] DB01582
[No targets] DB16008
DB00989: [43, 590]
[No targets] DB09026
[No targets] DB12686
DB00432: [7298]
[No targets] DB11663
[No targets] DB12369
DB08860: [3156]
[No targets] DB06174
DB00357: [1588]
DB06207: [148]
DB01065: [2099, 4835, 4544, 801, 4543, 4353, 811, 438, 6096, 8288, 4504, 3357]
[No targets] DB16871
[No targets] DB06097
[No targets] DB19357
[No targets] DB06195
[No targets] DB13919
[No targets] DB12529
DB04942: [5915, 5914, 5916]
DB00864: [2280]
DB01166: [5139, 5140]
DB00252: [6323, 6331, 1559]
[No targets] DB16346
DB00641: [3156, 3689, 5243, 10599]
DB00230: [773]
DB00975: [8654, 10846, 5141, 100, 5138, 6582, 10257, 5151, 58497, 2030, 50940, 27115]
[No targets] DB09078
DB00811: [22978, 55193, 5167, 3614, 132, 3615]
DB00804: [1128, 1129]
DB02115: [217, 3558]
[No targets] DB00911
[No targets] DB13551
DB00738: [1787, 6582, 6581, 6285, 5644, 26, 6303, 146802, 55244, 6768]
DB01399: [5742, 5743]
DB00260: [2671]
[No targets] DB12405
DB00580: [5743, 4513, 763, 768, 377677, 23632, 11238]
[No targets] DB06775
DB01039: [5465, 5468]
DB00668: [153, 150, 148, 151, 147, 154, 146, 5053, 155]
DB00631: [6240, 5422, 6241]
[No targets] DB18024
DB08896: [673, 2053, 3791]
[No targets] DB09516
[No targets] DB11259
[No targets] DB05134
DB00657: [1135]
DB00285: [1129, 150, 1128, 6530, 4886, 3356, 3358, 6532, 3362, 6531]
DB00692: [150, 148, 3350, 151, 152, 146, 3269, 147, 10280, 11188]
DB04665: [771, 761, 762, 765, 763, 766, 768, 23632, 11238]
[No targets] DB16021
[No targets] DB11544
[No targets] DB17030
[No targets] DB06769
DB01136: [3757, 7422, 153, 4718, 148, 154, 4879, 2697, 7412, 6582, 5243, 155]
DB00222: [6833, 3758, 3767]
[No targets] DB00779
[No targets] DB11781
DB01098: [3156, 5147]
[No targets] DB06685
[No targets] DB00832
DB00178: [1636]
DB00792: [3269]
DB00947: [2099]
DB08893: [155]
[No targets] DB05239
[No targets] DB13343
[No targets] DB00525
DB00486: [1268, 1269]
DB00502: [1812, 2904, 3356, 1814, 1813, 154, 5243, 3350, 150, 152, 6915, 1815, 1816, 3352, 3351, 3358, 3354, 3355, 6532, 3363, 148, 3269, 3357, 3362, 3757, 10682, 10280]

In [61]:
db_targets = pd.read_csv(CANONICAL_DATA_DIR_2 + "drugbank/targets.csv").set_index('drugbank_id')['target_gene'].dropna()
db_targets

Series([], Name: target_gene, dtype: float64)